#!/bin/sh
sfp_check=`uci get env.rip.sfp`
uci add_list network.lan.pppoerelay="wanptm0"
if [ $sfp_check != "1" ]; then
uci add_list network.lan.pppoerelay="waneth4"
uci add_list network.lan.pppoerelay="atmwan"
uci add_list network.lan.pppoerelay="ptm0"
uci add_list network.lan.pppoerelay="eth4"
fi
uci commit network

exit 0
