#!/bin/sh

rip_init() {
   insmod tommath
   insmod tomcrypt
   # for BRCM ARM and newer platforms, use the otp kernel module from BRCM
   if [[ -f /lib/modules/$(uname -r)/otp.ko ]]; then
	   insmod otp
   fi
   insmod platform-gpl
   insmod platform
   insmod ripdrv
}

boot_hook_add preinit_main rip_init

