#!/bin/sh

boardname_init() {
    BOARDNAME=$(cat /proc/rip/0040)
    BOARDNAMELOWER=$(echo "${BOARDNAME}" | awk '{print tolower($0)}')
    # symlink /etc/board to /etc/boards/${BOARDNAME}
    rm -f /etc/board
    ln -sf "/etc/boards/${BOARDNAME}" /etc/board
    # make sure we have the correct banner (rbi upgrade)
    [ "$(awk '/Version: / {print $2}' /etc/banner)" == "$(awk '/Version: / {print $2}' /rom/etc/banner)" ] || cp -f /rom/etc/banner /etc/banner
    # Adapt banner and /etc/config/version
    sed -i /etc/banner -e "s|\(Product: \)[a-z0-9]\{4,4\}-[a-z0-9]|\1$BOARDNAMELOWER|g"
    sed -i /etc/config/version -e "s|\(option product '\)[a-z0-9]\{4,4\}-[a-z0-9]|\1$BOARDNAMELOWER|g"
    # Adapt banner if a demo build
    if ! grep "Demo build, unofficial Technicolor SW, not suitable for deployment!" /etc/banner >/dev/null \
        && grep "^Version: [0-9]\{2,2\}\.[0-9]\{2,2\}\.[0-9a-z]\+-[0-9]\{2,2\}\([13579][0-9]\|[0-9]9\)[0-9]\{3,3\}-[0-9]\{14,14\}-[a-f0-9]\{40,40\}\$" /etc/banner >/dev/null
    then
        awk '{print} /Version: / {print "\n\e[1;33m\e[41m                                                                     \n Demo build, unofficial Technicolor SW, not suitable for deployment! \n                                                                     \e[0m"}' /etc/banner > /etc/banner.demo && mv /etc/banner.demo /etc/banner
    fi
    # symlinks to correct config
    CONFIGROOTPATH='/etc/board/config'
    if [ -d "${CONFIGROOTPATH}" ]
    then
        for i in $(find ${CONFIGROOTPATH} -follow -type f)
        do
            DIR=$(dirname ${i#${CONFIGROOTPATH}}) # strip first occurence of CONFIGROOTPATH from $i
            [ -d "${DIR}" ] || mkdir -p "${DIR}"
            cp -f ${i} ${i#${CONFIGROOTPATH}} # mv, we only want to do this on firstboot
        done
        # remove sources, we only want to do this on firstboot
        rm -rf "${CONFIGROOTPATH}"
    fi
    # symlinks to wlan_common files
    WLANCOMMONPATH='/etc/wlan_common'
    if [ -d "$WLANCOMMONPATH" ]
    then
        for i in $(find $WLANCOMMONPATH -type f)
        do
           WLANPATH='/etc/wlan'
           FILE=`basename ${i}` 
           if [ ! -e "${WLANPATH}/${FILE}" ]
           then
               ln -s ${WLANCOMMONPATH}/${FILE} ${WLANPATH}/${FILE}
           fi
        done
    fi
}

boot_hook_add preinit_main boardname_init

