#!/bin/sh

# To install any EasyMesh IPKs available as part of the homeware-ipks folder
# This reduces the overhead of adding firstboot script in custo session
# Just copy the IPKs to /usr/share/homeware-ipks/

# make a copy of the default values of multiap
map_agent_enabled=`uci get multiap.agent.enabled`
map_ctrlr_enabled=`uci get multiap.controller.enabled`

# disable the multiap agent and controller
uci set multiap.agent.enabled=0
uci set multiap.controller.enabled=0
uci commit multiap

# install the IPKs if available
if [ -f /usr/share/homeware-ipks/multiap_libplatform_*.ipk ]; then
    filename=`ls /usr/share/homeware-ipks/multiap_libplatform_*.ipk`
    opkg install $filename --force-reinstall
    rm $filename
fi

if [ -f /usr/share/homeware-ipks/ieee1905_wt382_*.ipk ]; then
    filename=`ls /usr/share/homeware-ipks/ieee1905_wt382_*.ipk`
    opkg install $filename --force-reinstall
    rm $filename
fi

if [ -f /usr/share/homeware-ipks/mesh_wee_controller_*.ipk ]; then
    filename=`ls /usr/share/homeware-ipks/mesh_wee_controller_*.ipk`
    opkg install $filename --force-reinstall
    rm $filename
fi

if [ -f /usr/share/homeware-ipks/multiap_agent_*.ipk ]; then
    filename=`ls /usr/share/homeware-ipks/multiap_agent_*.ipk`
    opkg install $filename --force-reinstall
    rm $filename
fi

if [ -f /usr/share/homeware-ipks/multiap_controller_*.ipk ]; then
    filename=`ls /usr/share/homeware-ipks/multiap_controller_*.ipk`
    opkg install $filename --force-reinstall
    rm $filename
fi

# restore the default configs of multiap
uci set multiap.agent.enabled=$map_agent_enabled
uci set multiap.controller.enabled=$map_ctrlr_enabled
uci commit multiap
