#!/bin/sh

[ "$ACTION" = ifup -o "$ACTION" = ifdown ] || exit 0

. /usr/lib/qos/functions.sh

# basic check if QoS started
qos_started || exit 0

/usr/lib/qos/generate.sh firewall start | sh
/usr/bin/qos -q reload
