#!/bin/sh
[ "$ACTION" = ifup -o "$ACTION" = ifdown ] || exit 0

# basic check if QoS started
iptables -t mangle -L QoS_FW -n >/dev/null 2>&1 || exit 0

/usr/lib/qos/generate.sh firewall start | sh
/usr/bin/qos -q reload
