#!/bin/sh

if [ "${INTERFACE}" = "hotspot" ] && [ "${ACTION}" = "ifup" ]; then
    echo 1 > /sys/devices/virtual/net/br-hotspot/bridge/nf_call_iptables
    echo 1 > /sys/devices/virtual/net/br-hotspot/bridge/nf_call_ip6tables
fi

