#!/bin/sh

if [ "${INTERFACE}" = "hotspot" ] && [ "${ACTION}" = "ifup" ]; then
    echo 1 > /sys/devices/virtual/net/br-hotspot/bridge/nf_call_iptables
    echo 1 > /sys/devices/virtual/net/br-hotspot/bridge/nf_call_ip6tables
    iptables -t mangle -A FORWARD -i br-hotspot -j SKIPLOG
    iptables -t mangle -A FORWARD -o br-hotspot -j SKIPLOG
    ip6tables -t mangle -A FORWARD -i br-hotspot -j SKIPLOG
    ip6tables -t mangle -A FORWARD -o br-hotspot -j SKIPLOG
fi

