#!/bin/sh

case "$ACTION" in
	ifup)
		/usr/lib/qos/interface-remarking.sh "up" "$INTERFACE" "$DEVICE" | sh
        ;;
        ifdown)
		/usr/lib/qos/interface-remarking.sh "down" "$INTERFACE" | sh
        ;;
esac
