#!/bin/sh
# (C) NETDUMA Software 2016
# Start the daemon when the interface comes up.

# this file depends on getting called from hotplug
#-- @depends hotplug

#-- @depends test
#-- @test test 1
[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$INTERFACE" = "lan" ] || exit 0

/etc/init.d/arpwatch stop
/etc/init.d/arpwatch start
