#!/bin/sh

. $IPKG_INSTROOT/lib/functions/network.sh
. $IPKG_INSTROOT/usr/lib/lot/functions.sh


_hotplug_lot() {
   lot_hotplug "$ACTION" "$INTERFACE" "$DEVICE"
}

case "$ACTION" in
    ifup)
        [ "$(lot_state_get wan)" != "up" ] && _hotplug_lot
    ;;
    ifdown)
        [ "$(lot_state_get wan)" = "down" ] || _hotplug_lot
    ;;
esac

