#!/bin/sh
# do not run during /etc/init.d/network boot()
# pppoe-relay will be reloaded only once in /etc/init.d/pppoe-relay
[ -f /var/state/bootnetwork ] && exit 0

/etc/init.d/pppoe-relay enabled && {
    local iface
    logger -t pppoe-relay-hotplug "Interface $INTERFACE $ACTION"
    for iface in $(uci_get pppoerelayd config server_intf wan ; uci_get pppoerelayd config client_intf lan); do
	[ "$INTERFACE" = "$iface" ] && [ "$ACTION" = "ifup" ] && /etc/init.d/pppoe-relay start
	[ "$INTERFACE" = "$iface" ] && [ "$ACTION" = "ifdown" ] && /etc/init.d/pppoe-relay stop
    done
}
