#!/bin/sh

# depends on hotplug to call this script
#-- @depends hotplug

#-- @depends test
#-- @test test 1
if [ "$ACTION" == "ifup" ] && [ "$INTERFACE" == "lan" ]; then
  /etc/init.d/ctwatch restart
fi
