#!/bin/sh

# depends on hotplug to call this script
#-- @depends hotplug

#-- @depends test
#-- @test test 1
if [ "$3" != "RDKB" ]; then
  if [ "$ACTION" == "ifup" ] && [ "$INTERFACE" == "lan" ]; then
    /etc/init.d/ctwatch restart
  fi
else
    systemctl restart ctwatch
fi
