#!/bin/sh

if [ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wan" ]; then
  ubus call com.netdumasoftware.autoadmin fw_restart '{"reload_zone":true}'
  ubus call com.netdumasoftware.qos wan_restart
fi

if [ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "lan" ]; then
  ifconfig br0 txqueuelen 1000
fi
