#!/bin/sh

if [ -n "$INTERFACE" ]; then
	local servaction
	if [ ! -h /etc/rc.d/S*dropbear  ]; then
		servaction=stop
	elif [ "$ACTION" = "ifup" ]; then
		servaction=restart
	elif [ "$ACTION" = "ifdown" ]; then
		servaction=stop
	fi

	[ -n "$servaction" ] && /etc/init.d/dropbear $servaction $INTERFACE
fi
