#!/bin/sh

if [ ! -e "/proc/prozone/panic" ]; then
        exit 0
fi

. $IPKG_INSTROOT/lib/functions.sh
wan=$(uci_get network wan ifname)
size=`cat /proc/prozone/panic | wc -c`

[ $size -gt 0 ] && {
        [ ifup = "$ACTION" -a "$DEVICE" = $wan ] && {
                sh /usr/sbin/kernel-core-handler
        }
}
