#!/bin/sh /etc/rc.common

START=50
STOP=20
USE_PROCD=1
TRANSFORMER_PID_FILE=/var/run/transformer.pid
TRACE=0

trace_required() {
  local section="${1}"
  config_get TRACE "${section}" trace_requests 0
}

start_service() {
  config_load "transformer"
  config_foreach trace_required main
  if [ "${TRACE}" -eq 1 ]; then
    procd_open_instance "transformer_fwd"
    procd_set_param command socat -v -x ABSTRACT-RECVFROM:transformer,fork,setsockopt-int=1:16:1 ABSTRACT-CONNECT:debug_transformer,nonblock=1,type=2,setsockopt-int=1:16:1
    procd_set_param stderr 1
    procd_close_instance
  fi
  procd_open_instance
  procd_set_param command /usr/bin/transformer
  procd_set_param pidfile "${TRANSFORMER_PID_FILE}"
  procd_close_instance
}

stop_service() {
  if [ -r ${TRANSFORMER_PID_FILE} ]; then
    kill -KILL $(cat ${TRANSFORMER_PID_FILE})
    rm -f ${TRANSFORMER_PID_FILE}
  fi
}
