#!/bin/sh
# Copyright (C) 2015 Technicolor Delivery Technologies, SAS

. $IPKG_INSTROOT/lib/functions/network.sh

# See man pppd for positioning of passed parameters
local device="$1"
local ipaddress="$4"

network_get_device wan_dev wan

# Only setup routing for interfaces which belong to L2TP/IPSec server, so not the WAN interface
if [ "$device" != "$wan_dev" ]; then
    . $IPKG_INSTROOT/lib/functions/firewall-l2tp-ipsec-server-route.sh
    setup $device $ipaddress
fi
