return {
    {
        name = "pppoe",
        default = true,
        description = "Modo Ruteado PPPoE",
        view = "internet-pppoe-routed.lp",
        card = "003_internet_pppoe_routed.lp",
        check = {
            { "uci.network.interface.@wan.proto", "^pppoe$"},
        },
        operations = {
            { "uci.network.interface.@wan.proto", "pppoe"},
        },
    },
    {
        name = "bridge",
        default = false,
        description = "Modo Puente",
        view = "internet-bridged.lp",
        card = "003_internet_bridged.lp",
        check = {
            { "uci.network.interface.@wan.ifname","^eth0 eth1 eth2 eth3 atm_8_35 atm_8_81 ptm0_v881 eth4_v881$"},
            { "uci.network.interface.@wan.auto", "^1$"},
        },
        operations = {
            { "uci.network.interface.@ppp_8_35.auto", "0"},
            { "uci.network.interface.@ppp_8_81.auto", "0"},
            { "uci.network.interface.@wan.type", "bridge"},
            { "uci.network.interface.@wan.ifname","eth0 eth1 eth2 eth3 atm_8_35 atm_8_81 ptm0_v881 eth4_v881"},
            { "uci.network.interface.@wan.auto", "1"},
			{ "uci.ledfw.brightness.@wan.green", "0"},
			{ "uci.ledfw.brightness.@wan.red", "0"},
            { "uci.network.interface.@wan.proto", ""},
            { "uci.network.interface.@lan.ifname",""},
            { "uci.dhcp.dhcp.@lan.ignore", "1" },
            { "uci.wireless.wifi-device.@radio_2G.state", "0"},
            { "uci.wireless.wifi-device.@radio_5G.state", "0"},
            { "uci.wireless.wifi-iface.@wl0.state", "0"},
            { "uci.wireless.wifi-iface.@wl1.state", "0"},
            { "uci.ethernet.port.@eth0.speed", "auto"},
            { "uci.ethernet.port.@eth1.speed", "auto"},
            { "uci.ethernet.port.@eth2.speed", "auto"},
            { "uci.ethernet.port.@eth3.speed", "auto"},
        },
    },
    {
        name = "tpv_10",
        default = false,
        description = "Punto de Venta 10/FD",
        view = "internet-bridged.lp",
        card = "003_internet_bridged.lp",
        check = {
            { "uci.network.interface.@wan.ifname","^eth0 eth1 eth2 eth3 atm_8_81 ptm0 eth4_v881$"},
            { "uci.network.interface.@wan.auto", "^1$"},
        },
        operations = {
            { "uci.network.interface.@ppp_8_35.auto", "0"},
            { "uci.network.interface.@ppp_8_81.auto", "0"},
            { "uci.network.interface.@wan.type", "bridge"},
            { "uci.network.interface.@wan.ifname","eth0 eth1 eth2 eth3 atm_8_81 ptm0 eth4_v881"},
            { "uci.network.interface.@wan.auto", "1"},
			{ "uci.ledfw.brightness.@wan.green", "0"},
			{ "uci.ledfw.brightness.@wan.red", "0"},
            { "uci.network.interface.@wan.proto", ""},
            { "uci.network.interface.@lan.ifname",""},
            { "uci.dhcp.dhcp.@lan.ignore", "1" },
            { "uci.wireless.wifi-device.@radio_2G.state", "0"},
            { "uci.wireless.wifi-device.@radio_5G.state", "0"},
            { "uci.wireless.wifi-iface.@wl0.state", "0"},
            { "uci.wireless.wifi-iface.@wl1.state", "0"},
	    { "uci.ethernet.port.@eth0.speed", "10"},
	    { "uci.ethernet.port.@eth1.speed", "10"},
	    { "uci.ethernet.port.@eth2.speed", "10"},
	    { "uci.ethernet.port.@eth3.speed", "10"},
        },
    },
	{
        name = "tpv_100",
        default = false,
        description = "Punto de Venta 100/FD",
        view = "internet-bridged.lp",
        card = "003_internet_bridged.lp",
        check = {
            { "uci.network.interface.@wan.ifname","^eth0 eth1 eth2 eth3 atm_8_81 ptm0 eth4_v881$"},
            { "uci.network.interface.@wan.auto", "^1$"},
        },
        operations = {
            { "uci.network.interface.@ppp_8_35.auto", "0"},
            { "uci.network.interface.@ppp_8_81.auto", "0"},
            { "uci.network.interface.@wan.type", "bridge"},
            { "uci.network.interface.@wan.ifname","eth0 eth1 eth2 eth3 atm_8_81 ptm0 eth4_v881"},
            { "uci.network.interface.@wan.auto", "1"},
			{ "uci.ledfw.brightness.@wan.green", "0"},
			{ "uci.ledfw.brightness.@wan.red", "0"},
            { "uci.network.interface.@wan.proto", ""},
            { "uci.network.interface.@lan.ifname",""},
            { "uci.dhcp.dhcp.@lan.ignore", "1" },
            { "uci.wireless.wifi-device.@radio_2G.state", "0"},
            { "uci.wireless.wifi-device.@radio_5G.state", "0"},
            { "uci.wireless.wifi-iface.@wl0.state", "0"},
            { "uci.wireless.wifi-iface.@wl1.state", "0"},
	    { "uci.ethernet.port.@eth0.speed", "100"},
	    { "uci.ethernet.port.@eth1.speed", "100"},
	    { "uci.ethernet.port.@eth2.speed", "100"},
	    { "uci.ethernet.port.@eth3.speed", "100"},
        },
    },
}
