#!/bin/sh /etc/rc.common

START=00

boot() {
	for pin in 73 100; do
		if ! [ -e "/sys/class/gpio/gpio$pin" ]; then
			echo "$pin" >"/sys/class/gpio/export"
			echo out >"/sys/class/gpio/gpio$pin/direction"
			echo 0 >"/sys/class/gpio/gpio$pin/value"
		fi
	done
}
