#!/bin/sh

#get build version
build_version=`uci get version.@version[0].version`

#get short build version (first 14 characters of build version)
short_build_version=${build_version:0:14}

#Populate user-agent
#user-agent format: PRODUCT_NAME_FRIENDLY_NAME Build SHORT_BUILD_VERSION -- SERIAL_NUMBER
uci set mmpbxrvsipnet.sip_net.user_agent="$(uci get env.var.prod_friendly_name) Build $short_build_version -- $(uci get env.rip.factory_id)$(uci get env.rip.serial)"
