#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

NANOCDN_CONF_FILE=/etc/broadpeak/nanocdn.conf

start_service()
{
    enable=$(uci get system.mabr.enabled 2>/dev/null)
    [ $enable -eq 1 ] || return 0

    procd_open_instance nanocdn-core 
    procd_set_param command /usr/bin/nanocdn-core --conf $NANOCDN_CONF_FILE
    procd_set_param respawn 3600 5 0
    procd_set_param user nanocdn 
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance

    procd_open_instance nanocdn-rr 
    procd_set_param command /usr/bin/nanocdn-rr --conf $NANOCDN_CONF_FILE
    procd_set_param respawn 3600 5 0
    procd_set_param user nanocdn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
service_triggers()
{
         procd_add_interface_trigger "interface.*" lan /etc/init.d/nanocdn restart
}
 
