#!/bin/sh

# Install packages before booting
for ipk in $(ls -1 /etc/ipks/*.ipk); do
  opkg install --force-depends --force-reinstall ${ipk} && rm ${ipk}
done
ls /etc/custo/config/* &>/dev/null && mv /etc/custo/config/* /etc/config

/etc/init.d/rcS S boot

trap "{ run_scripts K shutdown }" SIGPWR

while true; do
  # Doing nothing
  sleep 10
done
