#!/bin/sh

[ "$ACTION" = stratum ] || [ "$ACTION" = step ] || exit 0

# set uci.system.ntp.synced to 1 if it hasn't already been set
config_load "system"
config_get ntpsynced ntp synced 0

if [ $ntpsynced = "0" ]; then
	uci_set_state system ntp synced 1
fi

#inform datausaged
ubus send datausaged.ntp_synced
