#!/bin/sh

[ "$ACTION" = stratum ] || [ "$ACTION" = step ] || exit 0

#Notify the time change
if [ $offset ]; then
        newtime=`date +%s`
	offset=${offset%%.*}
	oldtime=$(echo $newtime $offset | awk 'END { print $1 - int($2)}')
        ubus send time.changed '{"newtime":'"$newtime"',"oldtime":'"$oldtime"'}'
fi
