#!/bin/sh

SECTION=$2
HOOKTYPE=$3
EVENT=${SECTION}_${HOOKTYPE}

if [ "$SECTION" = "net" ]; then
  NETTYPE=$4
  PEER=$5
fi

if [ "$EVENT" = "net_up" ]; then
  if [ "$NETTYPE" = "veth" ]; then
    uci -P /var/state set lxc.${LXC_NAME}.${NET_SECTION}_veth_pair=$PEER
  fi
fi
