#!/bin/sh

mount_point=$1
if [ -f "${mount_point}/.rtfd_all_in_progress" ]; then
	logger -t RTFD -s "rtfd failed, completing it now"
	for f in $(ls -A ${mount_point}); do
		rm -rf ${mount_point}/$f
	done
	# signal that reboot is needed
	exit 1
fi