# /etc/ipsec.l2tp-ipsec-server.conf - strongSwan IPsec configuration file for Technicolor's L2TP/IPsec server.
# This file must be included by etc/ipsec.conf to instantiate this config.

config setup
        charondebug="ike 2, mgr 4, net 4"

conn %default
        ikelifetime=60m
        keylife=20m
        rekeymargin=3m
        keyingtries=1
        keyexchange=ike
        authby=secret

conn l2tp-server
        leftfirewall=yes
        type=transport
        rekey=no
        left=%any
        right=%any
        leftsubnet=0.0.0.0/0[udp/l2tp]
        # Port 'any' to accommodate clients which do not use default port 1701 for l2tp
        rightsubnet=0.0.0.0/0[udp/%any]
        auto=add
