#ifndef NETDUMA_ADBLOCKER_DEFINES_H
#define NETDUMA_ADBLOCKER_DEFINES_H

#define MIN_RESERVED_ID ( 1 )
#define MAX_RESERVED_ID ( 20 )
#define MAX_ENCODING_MEM_USE ( 1024 * 32 )
#define MAX_ENCODING_FILESIZE ( 1024 * 32 )

#ifdef USE_FIRMWARE_LISTS
	#define FIRMWARE_LIST_PATTERN ND_SYSROOT(ADBLOCKER_FIRMWARE_LIST_PATTERN)
#endif

#define LIST_FILE_PATTERN ND_SYSROOT(ADBLOCKER_LIST_FILE_PATTERN)

#ifdef USE_CLOUD_SYNC
	#define CLOUD_JSON_PATH ND_SYSROOT(ND_CUSTOM_DOCUMENT_ROOT .. ADBLOCKER_CLOUD_JSON_PATH)
#endif

#endif
