#!/bin/sh

# workaround for non-customized things
cp /etc/uci-defaults/.workaround/dscp2pbit-tch /etc/init.d/dscp2pbit
ln -s /etc/init.d/dscp2pbit-tch /etc/rc.d/S90dscp2pbit
cp /etc/uci-defaults/.workaround/dscp2pbit-tch.iface.hotplug /etc/hotplug.d/iface/10-dscp2pbit
