#!/bin/sh

uci -q batch <<-EOT
	delete firewall.wol
	set firewall.wol=include
	set firewall.wol.type=script
	set firewall.wol.path=/lib/functions/firewall-wol.sh
	set firewall.wol.reload=1
	commit firewall
EOT

exit 0
