#!/bin/sh

uci -q batch <<-EOT
	delete firewall.cwmpd
	set firewall.cwmpd=include
	set firewall.cwmpd.type=script
	set firewall.cwmpd.path=/lib/functions/firewall-cwmpd.sh
	set firewall.cwmpd.reload=1
	commit firewall
EOT

exit 0
