#!/bin/sh

uci -q batch <<-EOT
	delete firewall.dhcpsnooper
	set firewall.dhcpsnooper=include
	set firewall.dhcpsnooper.type=script
	set firewall.dhcpsnooper.path=/lib/functions/firewall-dhcpsnooper.sh
	set firewall.dhcpsnooper.reload=0
	commit firewall
EOT

exit 0
