#!/bin/sh

uci -q batch <<-EOT
	delete firewall.igmpproxy
	set firewall.igmpproxy=include
	set firewall.igmpproxy.type=script
	set firewall.igmpproxy.path=/lib/functions/firewall-igmpproxy-tch.sh
	set firewall.igmpproxy.reload=1
	commit firewall
EOT

exit 0
