#!/bin/sh

uci -q batch <<-EOT
	delete firewall.mldproxy
	set firewall.mldproxy=include
	set firewall.mldproxy.type=script
	set firewall.mldproxy.path=/lib/functions/firewall-mldproxy-tch.sh
	set firewall.mldproxy.reload=1
	commit firewall
EOT

exit 0
