#!/bin/sh

uci -q batch <<-EOT
	delete firewall.osgi
	set firewall.osgi=include
	set firewall.osgi.type=script
	set firewall.osgi.path=/lib/functions/firewall-osgi.sh
	set firewall.osgi.reload=1
	commit firewall
EOT

exit 0
