#!/bin/sh
# Copyright (C) 2015 Technicolor Delivery Technologies, SAS

uci -q batch <<-EOT
	delete firewall.l2tpipsecserver
	set firewall.l2tpipsecserver=include
	set firewall.l2tpipsecserver.type=script
	set firewall.l2tpipsecserver.path=/lib/functions/firewall-l2tp-ipsec-server.sh
	set firewall.l2tpipsecserver.reload=1
	commit firewall
EOT

exit 0
