#!/bin/sh
# Copyright (C) 2016 Technicolor Delivery Technologies

uci -q batch <<-EOT
	delete firewall.vpncommon
	set firewall.vpncommon=include
	set firewall.vpncommon.type=script
	set firewall.vpncommon.path=/lib/functions/vpn_common_firewall.sh
	set firewall.vpncommon.reload=1
	commit firewall
EOT

exit 0
