#!/bin/sh

uci -q batch <<-EOT
	delete firewall.net-snmp
	set firewall.snmpd=include
	set firewall.snmpd.type=script
	set firewall.snmpd.path=/lib/functions/firewall-net-snmp.sh
	set firewall.snmpd.reload=1
	commit firewall
EOT

exit 0
