#!/bin/sh

uci -q batch <<-EOT
	delete firewall.mmpbx
	set firewall.mmpbx=include
	set firewall.mmpbx.type=script
	set firewall.mmpbx.path=/lib/functions/firewall-mmpbx.sh
	set firewall.mmpbx.reload=1
	commit firewall
EOT

exit 0
