#!/bin/sh
#
# Copyright (C) 2012 OpenWrt.org
#

[ -e /etc/config/network ] && exit 0

touch /etc/config/network

. /lib/functions/uci-defaults.sh

ucidef_set_interface_loopback

uci commit network

exit 0
