#!/bin/sh
uci show dmordering >/dev/null 2>/dev/null || touch /etc/config/dmordering
uci set dmordering.qos=ordering
uci add_list dmordering.qos.order=W_Q7
uci add_list dmordering.qos.order=W_Q6
uci add_list dmordering.qos.order=W_Q5
uci add_list dmordering.qos.order=W_Q4
uci add_list dmordering.qos.order=W_Q3
uci add_list dmordering.qos.order=W_Q2
uci add_list dmordering.qos.order=W_Q1
uci add_list dmordering.qos.order=W_Q0

uci commit dmordering
