#!/bin/sh
uci set dumaos.tr69=tr69; uci set dumaos.tr69.dumaos_enabled=0; uci set dumaos.tr69.dumaos_upstream_plan_rate=20000000; uci set dumaos.tr69.dumaos_downstream_plan_rate=50000000;uci commit dumaos
exit 0
