#!/bin/sh
[ -f /etc/config/firewall ] && uci -q batch <<-EOF
	set firewall.incaa=include
	set firewall.incaa.path='/dumaos/apps/system/com.netdumasoftware.autoadmin/firewall_reloaded.sh'
	set firewall.incaa.enabled='1'
	set firewall.incaa.type='script'
	set firewall.incaa.family='any'
	set firewall.incaa.reload='1'
	commit firewall
EOF
exit 0
