#!/bin/sh

UI_SERVER_CONF=/etc/nginx/ui_server.conf
BODY_SIZE_MARGIN=524288

get_banksize() {
	hexsize=$(grep bank_1 /proc/mtd | cut -d ' ' -f 2)
	echo $((0x$hexsize))
}

echo "client_max_body_size $(($(get_banksize) + $BODY_SIZE_MARGIN));" > $UI_SERVER_CONF

