#!/bin/sh

. /lib/functions/uci-defaults.sh

if [ $(uci get env.rip.sw_flag) = "F2" ]; then
  server2=`uci get system.ntp.server | awk -F ' ' '{print $2}' `
  server3=`uci get system.ntp.server | awk -F ' ' '{print $3}' `
  server4=`uci get system.ntp.server | awk -F ' ' '{print $4}' `
  uci delete system.ntp.server
  uci add_list system.ntp.server='ntp.internode.on.net'
  if [ $server2 ]; then
	  uci add_list system.ntp.server=$server2
  fi
  if [ $server3 ]; then
	  uci add_list system.ntp.server=$server3
  fi
  if [ $server4 ]; then
	  uci add_list system.ntp.server=$server4
  fi
  uci commit system
fi
