#!/bin/sh

#Make custom folder if not present
if [ ! -d "/www/docroot/img/custom" ]; then
  mkdir /www/docroot/img/custom
fi
#Netlynk Logo from 16.3 to ispconfig folder
if [ -f /www/docroot/img/custom/logo.gif ]; then
  cp /www/docroot/img/custom/logo.gif /etc/ispconfig/
fi
if [ -f /etc/ispconfig/logo.gif ]; then 
  cp /etc/ispconfig/logo.gif /www/docroot/img/custom/ 
fi



exit 0
