#!/bin/sh
#GHG-2749

uci set wifi_conductor.global.enabled='0'
uci set wifi_doctor_agent.config.enabled='0'
uci set wifi_doctor_agent.config.cs_url='https://coll-v2-ap.wifi-doctor.org/'
uci set wifi_doctor_agent.config.enable_friendly_name='1'

uci set wifi_doctor_agent.as_config.url='https://device-auth-ap.wifi-doctor.org/oauth/token'
uci set wifi_doctor_agent.as_config.client_id='wifidr-agent'
uci set wifi_doctor_agent.as_config.client_secret='ViEi6MuygPcrF54I8qO8qhsSmbVNcZGl'
uci set wifi_doctor_agent.as_config.passwd='0ae7177c-dd06-4ef0-b991-49ea5ae80a40$Gle65pPgD0j9MxxQQlzvL1JfNWPgyGai'

uci set wifi_doctor_agent.fhc=fhc
uci set wifi_doctor_agent.fhc.enable='1'
uci set wifi_doctor_agent.app_support=app_support
uci set wifi_doctor_agent.app_support.enable_onboarding='1'
uci set wifi_doctor_agent.app_support.lan_msg_dev='br-lan'
uci set wifi_doctor_agent.app_support.is_broker='1'
uci set wifi_doctor_agent.app_support.enable='1'
uci set wifi_doctor_agent.fhc_master=fhc_master
uci set wifi_doctor_agent.fhc_master.enable='1'

uci set wifi_conductor.debug.trace_level='quiet'
uci set wifi_conductor.controller.log='1'
uci set wifi_conductor.algo.log='1'
uci set wifi_conductor.roamer.log='1'


uci set wifi_doctor_agent.config.ssl_cert='/proc/rip/011a.cert'
uci set wifi_doctor_agent.config.ssl_key='engine:keystore:1'
uci set wifi_doctor_agent.as_config.challenge_url='https://device-auth-ap.wifi-doctor.org/challenge'

uci set fhcd.fhcd=fhcd
uci set fhcd.fhcd.enable='1'
uci set fhcd.fhcd.tls_cert='/tmp/certs/chain.pem'
uci set fhcd.fhcd.tls_key='/tmp/certs/key.pem'
uci set fhcd.fhcd.tls_castore='/tmp/certs/ca'
uci set fhcd.fhcd.interface='lan'


uci commit wifi_conductor
uci commit wifi_doctor_agent
uci commit fhcd
