#!/bin/sh

#uci set network.gt0=interface
#uci set network.gt0.proto='gretap'
#uci set network.gt0.mtu='1500'

#uci set network.hotspot=interface
#uci set network.hotspot.type='bridge'
#uci set network.hotspot.proto='static'
#uci set network.hotspot.igmp_snooping='0'
#uci set network.hotspot.ifname='@gt0'

#uci commit network

#uci set wireless.ap2=wifi-ap
#uci set wireless.ap2.iface='wl0_1'
#uci set wireless.ap2.state='1'
#uci set wireless.ap2.public='1'
#uci set wireless.ap2.ap_isolation='1'
#uci set wireless.ap2.station_history='1'
#uci set wireless.ap2.max_assoc='8'
#uci set wireless.ap2.security_mode='none'
#uci set wireless.ap2.pmf='disabled'
#uci set wireless.ap2.pmksa_cache='1'
#uci set wireless.ap2.wps_state='0'
#uci set wireless.ap2.wps_w7pbc='1'
#uci set wireless.ap2.wsc_state='configured'
#uci set wireless.ap2.wps_ap_setup_locked='0'
#uci set wireless.ap2.acl_mode='unlock'
#uci set wireless.ap2.acl_registration_time='60'
#uci set wireless.ap2.trace_modules=' '
#uci set wireless.ap2.trace_level='some'

#uci set wireless.wl0_1=wifi-iface
#uci set wireless.wl0_1.device='radio_2G'
#uci set wireless.wl0_1.mode='ap'
#uci set wireless.wl0_1.ssid='Hotspot'
#uci set wireless.wl0_1.network='hotspot'
#uci set wireless.wl0_1.state='0'

#uci commit wireless
