#!/bin/sh
#for telstra in common
#set -x
/bin/tar -xvf /usr/lib/ipk/thor.tar -C /usr/lib/ipk/
/bin/opkg install /usr/lib/ipk/Dependencies/*
/bin/opkg install /usr/lib/ipk/THOR/*
rm -rf /usr/lib/ipk/thor.tar
