#!/bin/sh

uci set network.fonopen.ipv6=1
uci set dhcp.Guest1_5GHz_private.limit=125
uci commit dhcp
uci -q get wireless.bs0 && exit 0
uci set wireless.ap0.bandsteer_id=off
uci set wireless.ap1.bandsteer_id=off
uci set wireless.ap2.bandsteer_id=off
uci set wireless.ap3.bandsteer_id=off
uci set wireless.ap4.bandsteer_id=off
uci set wireless.ap5.bandsteer_id=off
uci set wireless.ap6.bandsteer_id=off
uci set wireless.ap7.bandsteer_id=off
uci commit wireless
uci -q get parental.redirect && exit 0
uci set parental.general.ipv6_enable='0'
uci add_list parental.general.lan_intf='lan'
uci add_list parental.general.lan_intf='Guest1'
uci add_list parental.general.lan_intf='Guest1-5GHz'
uci set parental.redirect=parental
uci commit parental
exit 0
