#!/bin/sh

uci set dhcp.opassthrud=opassthrud
uci set dhcp.opassthrud.passthruscript='/lib/dhcpopassthrud/dnsmasq.sh'
uci set dhcp.opassthrud.options_needed=0

uci set dhcp.STBoptions=passthru
uci set dhcp.STBoptions.dhcp_pool=STB
uci set dhcp.STBoptions.interface=iptv
uci add_list dhcp.STBoptions.dhcp_option=42
uci add_list dhcp.STBoptions.dhcp_option=43

uci commit dhcp

exit 0
