#!/bin/sh

#get build version
build_version=`uci get version.@version[0].version`

#get short build version (first 14 characters of build version)
short_build_version=${build_version:0:14}

#Populate user-agent
#user-agent format for TI: vendorname / <HWversion>/ <FWversion> / <SWversion>
uci set mmpbxrvsipnet.sip_net.user_agent="$(uci get env.var.company_name) / $(uci get env.var.hardware_version) / $short_build_version / $short_build_version"
