#!/bin/sh
new_layout=`uci get env.var.em_new_ui_layout`
old_files="/www/docroot/modals/easy-mesh-configuration.lp /www/docroot/modals/wifi-extender-status.lp /www/docroot/modals/wifi-devices-info.lp /www/docroot/js/wireless-analyzer.js /www/docroot/js/easy-mesh-configuration.js /www/cards/004_wireless.lp /www/lua/wirelessSSID_helper.lua /www/docroot/modals/wireless-modal.lp"
new_files="/www/docroot/modals/easymesh-configuration-modal-newEM.lp /www/docroot/modals/easymesh-topology-modal-newEM.lp /www/docroot/modals/easymesh-devices-info-modal-newEM.lp /www/docroot/js/wireless-analyzer-newEM.js /www/docroot/modals/wireless-ap-modal-newEM.lp /www/docroot/modals/wireless-radio-modal-newEM.lp /www/docroot/modals/wireless-wps-modal-newEM.lp /www/docroot/js/easymesh-configuration-modal-newEM.js /www/cards/004_wireless-newEM.lp /www/lua/wireless-card_helper-newEM.lua"
if [ $new_layout == 1 ] ; then
  for file in $old_files
  do
    if [ -f $file ] ; then
      rm $file
    fi
  done
else
  for file in $new_files
  do
    if [ -f $file ] ; then
      rm $file
    fi
  done
fi

