#!/bin/sh

uci set network.gt0=interface
uci set network.gt0.proto='gretap'
uci set network.gt0.mtu='1500'
uci set network.gt0.ipv6='0'

uci set network.hotspot=interface
uci set network.hotspot.type='bridge'
uci set network.hotspot.proto='static'
uci set network.hotspot.igmp_snooping='0'
uci set network.hotspot.ifname='@gt0'

uci commit network

#Default
AP_NUM=2

#Detect radio2
DUMMY=`uci get wireless.radio2`

if [ "$?" == "0" ] ; then
  AP_NUM=3
fi

uci set wireless.ap$AP_NUM=wifi-ap
uci set wireless.ap$AP_NUM.iface='wl0_1'
uci set wireless.ap$AP_NUM.state='1'
uci set wireless.ap$AP_NUM.public='1'
uci set wireless.ap$AP_NUM.ap_isolation='1'
uci set wireless.ap$AP_NUM.station_history='1'
uci set wireless.ap$AP_NUM.max_assoc='8'
uci set wireless.ap$AP_NUM.security_mode='none'
uci set wireless.ap$AP_NUM.pmf='disabled'
uci set wireless.ap$AP_NUM.pmksa_cache='1'
uci set wireless.ap$AP_NUM.wps_state='0'
uci set wireless.ap$AP_NUM.wps_w7pbc='1'
uci set wireless.ap$AP_NUM.wsc_state='configured'
uci set wireless.ap$AP_NUM.wps_ap_setup_locked='0'
uci set wireless.ap$AP_NUM.acl_mode='unlock'
uci set wireless.ap$AP_NUM.acl_registration_time='60'
uci set wireless.ap$AP_NUM.trace_modules=' '
uci set wireless.ap$AP_NUM.trace_level='some'

uci set wireless.wl0_1=wifi-iface
uci set wireless.wl0_1.device='radio_2G'
uci set wireless.wl0_1.mode='ap'
uci set wireless.wl0_1.ssid='Hotspot'
uci set wireless.wl0_1.network='hotspot'
uci set wireless.wl0_1.state='1'

uci commit wireless
