#!/bin/sh

uci set network.fonopen.ipv6=1
uci -q delete network.ipoe.neighreachabletime
uci commit network
uci set dhcp.Guest1_5GHz_private.limit=125
uci commit dhcp
uci -q get wireless.bs0 && exit 0
uci set wireless.ap0.bandsteer_id=off
uci set wireless.ap1.bandsteer_id=off
uci set wireless.ap2.bandsteer_id=off
uci set wireless.ap3.bandsteer_id=off
uci set wireless.ap4.bandsteer_id=off
uci set wireless.ap5.bandsteer_id=off
uci set wireless.ap6.bandsteer_id=off
uci set wireless.ap7.bandsteer_id=off
uci commit wireless
uci -q get parental.redirect && exit 0
uci set parental.general.ipv6_enable='0'
uci add_list parental.general.lan_intf='lan'
uci add_list parental.general.lan_intf='Guest1'
uci add_list parental.general.lan_intf='Guest1-5GHz'
uci set parental.redirect=parental
uci commit parental
uci -q get network.eth4 && exit 0
uci add_list hotspotd.whitelist.domain=fonglobal.users.api.fon.com
uci add_list hotspotd.whitelist.domain=fonglobal.billing.api.fon.com
uci add_list hotspotd.whitelist.domain=pagosweb.vodafone.es
uci add_list hotspotd.whitelist.domain=corp.fon.com
uci add_list hotspotd.whitelist.domain=boku.com
uci add_list hotspotd.whitelist.domain=buy.boku.com
uci add_list hotspotd.whitelist.domain=buy2.boku.com
uci commit hotspotd
exit 0
