#!/bin/sh

if [ ! -f /etc/config/transformer ]; then
	touch /etc/config/transformer
fi

uci show transformer.@main[0] >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
	uci add transformer main
fi

uci add_list transformer.@main[0].ignore_patterns='^InternetGatewayDevice%.'
uci add_list transformer.@main[0].vendor_patterns='X_FASTWEB_'
uci add_list transformer.@main[0].ignore_patterns='X_FASTWEB_ONTmode'
uci add_list transformer.@main[0].ignore_patterns='X_FASTWEB_ONTmodeGUIbutton'
uci commit transformer
