#!/bin/sh


wireless_init_uci_env.sh

# cred0 - Fronthaul
# cred 1 - 5G Fronthaul . This will be in disabled state in config and will
# be used only when there is a requirement for different SSID for 2G and 5G
# cred 2 - Backhaul only

# Set controller_credentials for FH

uci set multiap.cred0.ssid=`uci get env.var.ssid_prefix``uci get env.var.ssid_mac_postfix_r0`
uci set multiap.cred1.ssid=`uci get env.var.ssid_prefix``uci get env.var.ssid_mac_postfix_r1`

uci set multiap.cred0.wpa_psk_key=`uci get env.var.default_key_r0_s0`
uci set multiap.cred1.wpa_psk_key=`uci get env.var.default_key_r1_s0`

# Set controller_credentials for BH

uci set multiap.cred2.ssid="BH-$(uci get env.var.ssid_mac_postfix_r0)"
uci set multiap.cred2.wpa_psk_key=`uci get env.var.default_key_r0_s1`

# Commit the changes

uci commit multiap

