#!/bin/bash
READWRITE=`cat /proc/mounts | grep ubi0_1`
if [ $(expr "$READWRITE" : ".*ro.*") -gt 0 ]; then
        echo "found overlay on ubifs is corrupted moved to  ro"
        umount /overlay
        ubiupdatevol -t /dev/ubi0_1
        sync
        reboot -f
else
        echo "overlay is rw, normal"
fi
