#!/bin/sh

# Disabled the coredump upload for now.
# To check whether it is needed.

#if echo $(uci get version.@version[0].version) | grep -q -v dev
#then
    # It's not a dev build so upload coredump
#    uci set system.@coredump[0].action=upload
#    uci set system.@coredump[0].url=https://coredump.stg.wifi-doctor.org/
#    uci commit system
#fi

acs_allowed_channels=`uci get wireless.radio_5G.acs_allowed_channels`
uci set wifi_doctor_agent.default_acs_list_cache_bandlock.radio_5G="$acs_allowed_channels"
