#!/bin/sh

_HOTSPOT_NETWORK=fonopen

#hotspotd settings
macaddr=`uci get env.rip.wifi_mac`
nas=${macaddr//:/-}
uci set hotspotd.main.nasid=$nas

uci commit hotspotd

#fon wireless settings
uci set wireless.ap4=wifi-ap
uci set wireless.ap4.iface=wl0_2
uci set wireless.ap4.state=1
uci set wireless.ap4.ap_isolation=1
uci set wireless.ap4.station_history=1
uci set wireless.ap4.max_assoc=2
uci set wireless.ap4.security_mode=none
uci set wireless.ap4.pmf=disabled
uci set wireless.ap4.pmksa_cache=1
uci set wireless.ap4.wps_state=0
uci set wireless.ap4.wps_w7pbc=1
uci set wireless.ap4.wsc_state=configured
uci set wireless.ap4.wps_ap_setup_locked=0
uci set wireless.ap4.acl_mode=unlock
uci set wireless.ap4.acl_registration_time=60
uci set wireless.ap4.trace_level=some
uci set wireless.ap4.bandsteer_id='off'

uci set wireless.wl0_2=wifi-iface
uci set wireless.wl0_2.device=radio_2G
uci set wireless.wl0_2.mode=ap
uci set wireless.wl0_2.state=0
uci set wireless.wl0_2.reliable_multicast=0
uci set wireless.wl0_2.ssid='Telstra Air'
uci set wireless.wl0_2.network="${_HOTSPOT_NETWORK}"

uci set wireless.ap5=wifi-ap
uci set wireless.ap5.iface=wl0_3
uci set wireless.ap5.state=1
uci set wireless.ap5.ap_isolation=1
uci set wireless.ap5.station_history=1
uci set wireless.ap5.max_assoc=2
uci set wireless.ap5.security_mode=none
uci set wireless.ap5.pmf=disabled
uci set wireless.ap5.pmksa_cache=1
uci set wireless.ap5.wps_state=0
uci set wireless.ap5.wps_w7pbc=1
uci set wireless.ap5.wsc_state=configured
uci set wireless.ap5.wps_ap_setup_locked=0
uci set wireless.ap5.acl_mode=unlock
uci set wireless.ap5.acl_registration_time=60
uci set wireless.ap5.trace_level=some
uci set wireless.ap5.bandsteer_id='off'

uci set wireless.wl0_3=wifi-iface
uci set wireless.wl0_3.device=radio_2G
uci set wireless.wl0_3.mode=ap
uci set wireless.wl0_3.state=0
uci set wireless.wl0_3.reliable_multicast=0
uci set wireless.wl0_3.ssid='Fon WiFi'
uci set wireless.wl0_3.network="${_HOTSPOT_NETWORK}"

uci set wireless.ap6=wifi-ap
uci set wireless.ap6.iface=wl1_2
uci set wireless.ap6.state=1
uci set wireless.ap6.ap_isolation=1
uci set wireless.ap6.station_history=1
uci set wireless.ap6.max_assoc=2
uci set wireless.ap6.security_mode=none
uci set wireless.ap6.pmf=disabled
uci set wireless.ap6.pmksa_cache=1
uci set wireless.ap6.wps_state=0
uci set wireless.ap6.wps_w7pbc=1
uci set wireless.ap6.wsc_state=configured
uci set wireless.ap6.wps_ap_setup_locked=0
uci set wireless.ap6.acl_mode=unlock
uci set wireless.ap6.acl_registration_time=60
uci set wireless.ap6.trace_level=some
uci set wireless.ap6.bandsteer_id='off'

uci set wireless.wl1_2=wifi-iface
uci set wireless.wl1_2.device=radio_5G
uci set wireless.wl1_2.mode=ap
uci set wireless.wl1_2.state=0
uci set wireless.wl1_2.reliable_multicast=0
uci set wireless.wl1_2.ssid='Telstra Air-5G'
uci set wireless.wl1_2.network="${_HOTSPOT_NETWORK}"

uci set wireless.ap7=wifi-ap
uci set wireless.ap7.iface=wl1_3
uci set wireless.ap7.state=1
uci set wireless.ap7.ap_isolation=1
uci set wireless.ap7.station_history=1
uci set wireless.ap7.max_assoc=2
uci set wireless.ap7.security_mode=none
uci set wireless.ap7.pmf=disabled
uci set wireless.ap7.pmksa_cache=1
uci set wireless.ap7.wps_state=0
uci set wireless.ap7.wps_w7pbc=1
uci set wireless.ap7.wsc_state=configured
uci set wireless.ap7.wps_ap_setup_locked=0
uci set wireless.ap7.acl_mode=unlock
uci set wireless.ap7.acl_registration_time=60
uci set wireless.ap7.trace_level=some
uci set wireless.ap7.bandsteer_id='off'

uci set wireless.wl1_3=wifi-iface
uci set wireless.wl1_3.device=radio_5G
uci set wireless.wl1_3.mode=ap
uci set wireless.wl1_3.state=0
uci set wireless.wl1_3.reliable_multicast=0
uci set wireless.wl1_3.ssid='Fon WiFi-5G'
uci set wireless.wl1_3.network="${_HOTSPOT_NETWORK}"

uci set wireless.bs2=wifi-bandsteer
uci set wireless.bs2.rssi_threshold='-40'
uci set wireless.bs2.rssi_5g_threshold='-80'
uci set wireless.bs2.policy_mode='5'

uci set wireless.bs3=wifi-bandsteer
uci set wireless.bs3.rssi_threshold='-40'
uci set wireless.bs3.rssi_5g_threshold='-80'
uci set wireless.bs3.policy_mode='5'

uci commit wireless

#fon network settings
uci set network.${_HOTSPOT_NETWORK}=interface
uci set network.${_HOTSPOT_NETWORK}.auto=0
uci set network.${_HOTSPOT_NETWORK}.type=bridge
uci set network.${_HOTSPOT_NETWORK}.proto=static
uci set network.${_HOTSPOT_NETWORK}.ipaddr=192.168.20.1
uci set network.${_HOTSPOT_NETWORK}.netmask=255.255.255.0
uci set network.${_HOTSPOT_NETWORK}.ipv6=1
uci set network.${_HOTSPOT_NETWORK}.ip6class=wan6
uci set network.${_HOTSPOT_NETWORK}.force_link=0

uci commit network

#fon dhcp settings
#fon dnsmasq instance
uci set dhcp.hotspot='dnsmasq'
uci set dhcp.hotspot.disabled='0'
uci set dhcp.hotspot.nonwildcard='1'
uci set dhcp.hotspot.domainneeded='1'
uci set dhcp.hotspot.boguspriv='1'
uci set dhcp.hotspot.filterwin2k='0'
uci set dhcp.hotspot.localise_queries='1'
uci set dhcp.hotspot.rebind_protection='0'
uci set dhcp.hotspot.rebind_localhost='1'
uci set dhcp.hotspot.local='/hotspot/'
uci set dhcp.hotspot.expandhosts='1'
uci set dhcp.hotspot.nonegcache='0'
uci set dhcp.hotspot.authoritative='1'
uci set dhcp.hotspot.readethers='1'
uci set dhcp.hotspot.leasefile='/tmp/dhcp.leases.hotspot'
uci set dhcp.hotspot.strictorder='1'
uci set dhcp.hotspot.dhcpscript='/lib/dhcp/dhcp-event.sh'
uci set dhcp.hotspot.domain='hotspot'
uci add_list dhcp.hotspot.interface='fonopen'
uci add_list dhcp.hotspot.notinterface='loopback'
uci add_list dhcp.hotspot.notinterface='lan'
uci add_list dhcp.hotspot.notinterface='Guest1'
uci add_list dhcp.hotspot.notinterface='Guest1_5GHz'
uci set dhcp.hotspot.resolvfile='/tmp/resolv.conf.hotspot'

#fon dhcp pool
uci set dhcp.fonopen=dhcp
uci set dhcp.fonopen.instance='hotspot'
uci set dhcp.fonopen.interface="${_HOTSPOT_NETWORK}"
uci set dhcp.fonopen.start=1
uci set dhcp.fonopen.limit=37
uci set dhcp.fonopen.force=1
uci set dhcp.fonopen.leasetime=20m
uci set dhcp.fonopen.dhcpv6=server
uci set dhcp.fonopen.ra=server
uci set dhcp.fonopen.ra_management=0
uci set dhcp.fonopen.ra_min_interval=200
uci set dhcp.fonopen.ra_max_interval=600
uci set dhcp.fonopen.ra_lifetime=1800
uci set dhcp.fonopen.ra_hoplimit=64

uci commit dhcp


