#!/bin/sh

###########################################################################################
#	this config is needed on SFP based CPE
#	will be used dynamically, to avoid misunderstanding while debugging on NON GPON CPE
###########################################################################################

board=`uci get env.rip.sfp`

if [ $board == "1" ]; then

	uci set ethernet.globals=globals
	uci set ethernet.globals.eth4lanwanmode='0'
	
fi	

uci commit ethernet
exit 0