#!/bin/sh

. /lib/functions/uci-defaults.sh

ucidef_set_interface_lan "eth0 eth1 eth2 eth3"

uci set network.lan.ip6assign=64
uci set network.lan.ip6hint=0
uci set network.lan.netmask=255.255.255.0
uci set network.lan.ipaddr=10.0.0.138
uci set network.lan.force_link=0

uci set network.Guest1=interface
uci set network.Guest1.proto=static
uci set network.Guest1.ip6assign=64
uci set network.Guest1.ip6hint=1
uci set network.Guest1.netmask=255.255.255.128
uci set network.Guest1.ipaddr=192.168.2.126
uci set network.Guest1.ifname=wl0_1
uci set network.Guest1.force_link=0

uci set network.Guest1_5GHz=interface
uci set network.Guest1_5GHz.proto=static
uci set network.Guest1_5GHz.ip6assign=64
uci set network.Guest1_5GHz.ip6hint=2
uci set network.Guest1_5GHz.netmask=255.255.255.128
uci set network.Guest1_5GHz.ipaddr=192.168.2.254
uci set network.Guest1_5GHz.ifname=wl1_1
uci set network.Guest1_5GHz.force_link=0

ucidef_set_switch "bcmsw" "1" "0"
uci set network.bcmsw.qosimppauseenable=0
uci commit network

exit 0
