#!/bin/sh

###########################################################################################
#	this config is needed on SFP based CPE
#	will be used dynamically, to avoid misunderstanding while debugging on NON GPON CPE
###########################################################################################

board=`uci get env.var.hardware_version`

if [ $board == "VBNT-K_SFP" ]; then

	uci set ethernet.globals=globals
	uci set ethernet.globals.eth4lanwanmode='1'
	
fi	

uci commit ethernet
exit 0