#!/bin/sh
# Tiscali Env Vars
uci set env.custovar=envvars
uci set env.custovar.URL='www.tiscali.it'
uci set env.custovar.cwmpd_enabled='1'
uci set env.var.rtfds='1'


#Set env prefix for WiFi SSID
uci set env.var.ssid_prefix='TISCALI-'
uci set env.var.ssid_prefix_5G='TISCALI5G-'
#uci set env.var.ssid_prefix_guest='Ospiti-TISCALI-'
#uci set env.var.ssid_prefix_guest_5G='Ospiti-TISCALI5G-'
uci set env.var.prod_name='MediaAccess TG789vac Xtream 35b'
uci set env.var.prod_number='MediaAccess TG789vac Xtream 35b'


uci commit env

#Workaround for Voice not restarting correctly
uci set mmpbx.global.enabled=1
uci commit mmpbx

#Disabled dropear LAN
uci set dropbear.lan.enable='0'
uci commit dropbear

