#!/bin/sh

#get firmware version
FirmwareVersion=`uci get env.var.friendly_sw_version_activebank`

#get short firmware version (first 12 characters of firmware version)
FirmwareSimple=${FirmwareVersion:0:12}

#Populate user-agent
#user-agent format: CPE_MODEL/short_firmware_version (serial number happening is disabled)
uci set mmpbxrvsipnet.sip_net.user_agent=`uci get env.var.CPE_MODEL`"/"$FirmwareSimple

uci commit mmpbxrvsipnet
