#!/bin/sh

#init env
wireless_init_uci_env.sh

#Update parameters

# To make sure it is set to the correct vendor

#2.4GHz Default Config
uci set wireless.radio_2G.type=`wireless_get_radio_type.sh radio_2G`

uci set wireless.wl0.ssid='TeliaGateway'`uci get env.rip.wifi_mac |tr : -`

uci set wireless.ap0.wep_key=`uci get env.var.default_key_r0_s0`

uci set wireless.ap0.wpa_psk_key=`uci get env.var.default_key_r0_s0`

uci set wireless.ap0.wps_ap_pin=`uci get env.var.default_wps_ap_pin_r0_s0`

uci set wireless.ap0_auth0.secret=`uci get env.var.default_key_r0_s0`

uci set wireless.wl0_1.ssid='GuestAccess'`uci get env.rip.wifi_mac | awk 'BEGIN {FS= ":"}  {print $4 $5 $6}'`

uci set wireless.ap1.wpa_psk_key=`uci get env.var.default_key_r0_s1`

uci set wireless.ap1_auth0.secret=`uci get env.var.default_key_r0_s0`

uci commit wireless
