#!/bin/sh

# point to the one time executed lua script
FIRSTBOOT_CLASH=/usr/lib/lua/tch/firstboot/opendropbear.lua

# if script does no longer exists , we stop here
[ ! -e "${FIRSTBOOT_CLASH}" ] && exit

# execute the script as part of the firstboot only when board is open
if grep -q -- allow_root_shell_access  /proc/efu/allowed ; then
    lua "${FIRSTBOOT_CLASH}"
fi

# Destroy the script; as it is used only for first boot
rm "${FIRSTBOOT_CLASH}"
