#!/bin/sh
# DHCP option 125
uci add_list dhcp.lan.dhcp_option=tag:cpewan-id,vi-encap:3561,6,\""`uci get env.var.prod_number`"\"
uci add_list dhcp.lan.dhcp_option=tag:cpewan-id,vi-encap:3561,5,\"`uci get env.rip.factory_id``uci get env.rip.serial`\"
uci add_list dhcp.lan.dhcp_option=tag:cpewan-id,vi-encap:3561,4,\"`uci get env.var.oui`\"
uci commit dhcp
