#!/bin/sh

#Populate modelNumber
uci set upnpd.config.model_number="$(uci get env.var.prod_number)"

#Populate serialNumber
uci set upnpd.config.serial_number="$(uci get env.rip.serial)"

#Populate friendlyName changed to address NG-71142
uci set upnpd.config.friendly_name="Modem TIM"

#Populate manufacturer
uci set upnpd.config.manufacturer="$(uci get env.var.company_name)"

#Populate model_name changed to address NG-71142
uci set upnpd.config.model_name="$(uci get env.var.variant_friendly_name)"

uci commit

