#!/bin/sh
#NG-71142

#Populate uuid
uci set minidlna.config.uuid="4d696e69-444c-164e-9d41-$(uci get env.rip.eth_mac | sed 's/[\:]//g' | awk '{print tolower($0)}')"
uci set minidlna.config.model_name='AGEVO'			#added NG-71142
uci set minidlna.config.friendly_name='Modem TIM'	#added NG-71142
uci commit minidlna
