#!/bin/sh
# Copyright (C) 2016 Technicolor Delivery Technologies

uci -q batch <<-EOT
	delete firewall.weburl
	set firewall.weburl=include
	set firewall.weburl.type=script
	set firewall.weburl.path=/lib/functions/weburl-tch.sh
	set firewall.weburl.reload=1
	commit firewall
EOT

exit 0
