#!/bin/sh
DUMMY=`uci get wireless.radio_5G`

set_channel() {
  CHANNEL=36

  # Check content of country map
  if [ -e "/etc/wlan/brcm_country_map_5G" ] ; then
    if [ "`cat /etc/wlan/brcm_country_map_5G | grep \"MX 49\" `" != "" ] ; then
      CHANNEL=52
    fi
  fi

}

if [ "$?" == "0" ] ; then

  #If dev SW is running on the board, then force channel 36
  DEV=`uci get version.@version[0].version |cut -d '.' -f 3|cut -d '-' -f 1`
    
  if [ "$DEV" == "dev" ] ; then

    set_channel

    uci set wireless.radio_5G.channel=$CHANNEL
    uci commit wireless
  fi  
fi

