#!/bin/sh
uci set network.fonopen.ipv6=1
uci commit network
uci set dhcp.Guest1_5GHz_private.limit=125
uci commit dhcp
uci -q get nfc.@nfc[0] && exit 0
uci add_list parental.general.lan_intf='Guest1'
uci add_list parental.general.lan_intf='Guest1-5GHz'
uci commit parental
exit 0
