#!/bin/sh

. /lib/functions/uci-defaults.sh

# Internet
uci set network.wan=interface
uci set network.wan.proto=dhcp
uci set network.wan.ifname=eth4
uci set network.wan.vendorid=TCH_Broadband_TG389
uci set network.wan.ip4table=main
uci set network.wan.reqopts='1 3 6 51'

# mobile backup
uci set network.wwan=interface
uci set network.wwan.auto='0'

# voip
uci set network.voip=interface
uci set network.voip.proto=dhcp
uci set network.voip.defaultroute=0
uci set network.voip.dnsset=voipdns
uci set network.voip.ifname=eth4_voip
uci set network.voip.auto=1
uci set network.voip.reqopts='1 3 121'
uci set network.voip.macaddr=`uci get env.rip.wifi_mac`

# iptv
uci set network.iptv=interface
uci set network.iptv.proto=dhcp
uci set network.iptv.ifname=eth4_iptv
uci set network.iptv.reqopts='1 42 43 121 128 241'
uci set network.iptv.auto=1
uci set network.iptv.vendorid=TEO_FR
uci set network.iptv.macaddr=`uci get env.var.local_wifi_mac`

#vlan device voip
uci set network.vlan_voip=device
uci set network.vlan_voip.type=8021q
uci set network.vlan_voip.ifname=eth4
uci set network.vlan_voip.name=eth4_voip
uci set network.vlan_voip.vid=5
uci set network.vlan_voip.macaddr=`uci get env.rip.wifi_mac`

#vlan device iptv
uci set network.vlan_iptv=device
uci set network.vlan_iptv.type=8021q
uci set network.vlan_iptv.ifname=eth4
uci set network.vlan_iptv.name=eth4_iptv
uci set network.vlan_iptv.igmpversion=2
uci set network.vlan_iptv.vid=6
uci set network.vlan_iptv.macaddr=`uci get env.var.local_wifi_mac`
uci set network.vlan_iptv.acceptlocal=1

uci set network.wan6=interface
uci set network.wan6.ifname=@wan
uci set network.wan6.proto=dhcpv6
uci set network.wan6.reqopts='12 21 22 23 24 25 31 56 64 67 82 83'
uci set network.wan6.noslaaconly=1

uci commit network

exit 0
