#!/bin/sh

eth_mac2=`uci get env.rip.eth_mac`
eth_mac=`echo $eth_mac2 | sed -e 's/.*\(........\)$/\1/' | sed 's/\://g'`

uci set uci-defaults.general.wifi_low_ssid=`uci get env.var.ssid_prefix`$eth_mac
uci set uci-defaults.general.wifi_high_ssid=`uci get env.var.ssid_prefix`$eth_mac"-5"
uci set uci-defaults.general.wifi_low_password=`uci get env.var.default_key_r0_s0`
uci set uci-defaults.general.wifi_high_password=`uci get env.var.default_key_r0_s0`
uci commit
