#!/bin/sh

UI_SERVER_CONF=/etc/nginx/ui_server.conf
BODY_SIZE_MARGIN=524288

get_banksize() {
        if ( grep -q bank_1 /proc/mtd ) ; then
                hexsize=$(grep bank_1 /proc/mtd | cut -d ' ' -f 2)
                echo $((0x$hexsize))
        else
                for volume in kernelA rootfsA; do
                        volumesize=`ubinfo -d 0 -N $volume | grep Size | cut -d ' ' -f 11 | cut -d '(' -f 2`
                        totalsize=$((totalsize + volumesize))
                done
                echo $totalsize
        fi
}

echo "client_max_body_size $(($(get_banksize) + $BODY_SIZE_MARGIN));" > $UI_SERVER_CONF

