#!/bin/sh

eth_mac2=`uci get env.rip.eth_mac`
eth_mac=`echo $eth_mac2 | sed -e 's/.*\(........\)$/\1/' | sed 's/\://g'`

uci set uci-defaults.general.wifi_low_ssid=`uci get env.var.ssid_prefix`$eth_mac
uci set uci-defaults.general.wifi_high_ssid=`uci get env.var.ssid_prefix`$eth_mac"-5"
uci set uci-defaults.general.wifi_low_password=`uci get env.var.default_key_r0_s0`
uci set uci-defaults.general.wifi_high_password=`uci get env.var.default_key_r0_s0`

high_dfs_channel=$(uci get wireless.radio_5G.allowed_channels 2>/dev/null || echo 36 40 44 48)

if [[ "$high_dfs_channel" == '36 40 44 48' ]]; then
   uci set uci-defaults.settings.wifihigh_dfschannel="0"
else
   uci set uci-defaults.settings.wifihigh_dfschannel="1"
fi

uci set uci-defaults.lan.hostname=`uci get env.var.hostname`
uci commit
