#!/bin/sh
lua /usr/lib/lua/tch/firstboot/opendropbear.lua

# Destroy the script; to be used only for first boot
rm /usr/lib/lua/tch/firstboot/opendropbear.lua

uci set dropbear.wan.enable='0'
uci commit dropbear
