#!/bin/sh
#get firmware version
FirmwareVersion=`uci get env.var.friendly_sw_version_activebank`

#get short firmware version (first 9 characters of firmware version)
FirmwareSimple=${FirmwareVersion:0:9}

# set xdsl EOC serial number to the serial number from RIP
uci set xdsl.dsl0.eoc_serial_number="`uci get env.var.CPE_MODEL`_"$FirmwareSimple"_`uci get env.var.serial`"
#ADSL eoc_version format : HWVersion_SWVersion_SN.
uci set xdsl.dsl0.eoc_version=`uci get env.var.serial`
uci commit xdsl
