#!/bin/ash

isppath="/etc/ispconfig/"
certpath="/etc/ssl/certs/"

for file in $isppath* 
do
      if [ -d $file ]
      then
		          echo "Directory found - No Action"
      elif [ -f $file ]
      then
              if [ ${file#*.} -eq "0" ]
              then
                     cp $file $certpath
                     echo "Copying $file to $certpath"
                     chmod 755 $file 
              fi
      fi
done;
