#!/bin/sh
# set xdsl EOC serial number to the serial number from RIP
#uci set xdsl.dsl0.eoc_serial_number="$(uci get env.rip.factory_id)$(uci get env.rip.serial) $(uci get env.var.prod_number) $(uci get version.@version[0].marketing_version)"

# Proximus specific : same as env.var.serial; compose EOC full serial number (with optional suffix)
uci set xdsl.dsl0.eoc_serial_number="$(uci get env.var.serial)"

#TODO update with correct string after agreement with Belgacom. Current stub is the old string(static) but usable on production network
#uci set xdsl.dsl0.eoc_version="589Bvn.A.10A0DFJ"
uci set xdsl.dsl0.eoc_version="$(uci get env.var.PXS_productname|cut -c1-6).$(uci get env.var.hardware_version).$(uci get env.var.friendly_sw_version_activebank|tr -d "." )"
uci commit xdsl
