#!/bin/sh

_store_passwords() {
        local usr="$1"
        local name=$(uci get web.$usr.name)

        if [[ ! -z "$usr" ]] && [[ ! -z "$name" ]]; then
                local SALT=$(uci get web.$usr.srp_salt)
                local VERIFIER=$(uci get web.$usr.srp_verifier)
		local HASHED=$(grep "^$name:" /etc/shadow | cut -d':' -f2)

                # storing default SALT and VERIFIER, hashed_password to uci-defaults
                uci set uci-defaults.$usr="user"
                uci set uci-defaults.$usr.name=$name
                uci set uci-defaults.$usr.srp_salt=$SALT
                uci set uci-defaults.$usr.srp_verifier=$VERIFIER
                # storing hashed password for CLI users
                if [ ! -z "$HASHED" ]; then
                        uci set uci-defaults.$usr.hash_pwd=$HASHED
                fi
                uci commit uci-defaults
        else
                logger "Error: Could not store $usr password for GUI, user or name is empty"
                exit 1
        fi
}

# stores default passwords in uci-defaults for all the users

_store_passwords "usr_user"

_store_passwords "usr_support"

#_store_passwords "usr_admin"
