#!/bin/sh
board=`uci get env.var.hardware_version`
ethstate=`uci get ethernet.globals.eth4lanwanmode`
classgroup='TO_LAN'
[ $board == "VBNT-S" ] && [ -n "$ethstate" -a $ethstate == 0 ] && classgroup='TO_WAN'
uci set qos.eth3.classgroup=$classgroup
uci commit qos
