#!/bin/sh

config="clash"

# Custom passwords are temporarily stored to /var/state
# A next (!) firstboot script (tch_0073-clash) then creates the user with that password
_set_pw() {
	local usr="$1"
	local passw="$2"
	uci -P /var/state set ${config}.${usr}.passw=${passw}
}

# User support takes fixed password `support`
_set_pw "engineer" "engineer"
