#!/bin/sh
#GHG-2749

uci set wifi_doctor_agent.config.enabled='0'
uci set wifi_doctor_agent.config.cs_url='https://coll-v2-ap.wifi-doctor.org/'

uci set wifi_doctor_agent.as_config.url='https://device-auth-ap.wifi-doctor.org/oauth/token'
uci set wifi_doctor_agent.as_config.client_id='wifidr-agent'
uci set wifi_doctor_agent.as_config.client_secret='ViEi6MuygPcrF54I8qO8qhsSmbVNcZGl'
uci set wifi_doctor_agent.as_config.passwd='0ae7177c-dd06-4ef0-b991-49ea5ae80a40$Gle65pPgD0j9MxxQQlzvL1JfNWPgyGai'

uci commit wifi_doctor_agent
