#!/bin/sh

##ZTE reliable multicast sends unicast IGMP queries, this command is needed to allow proper querier port discovery in the snooper
echo "ebtables -t nat -I PREROUTING -p ipv4 --ip-destination 224.0.0.1 -d ! 01:00:5e:00:00:00/ff:ff:ff:00:00:00 -j dnat --to-destination 01:00:5e:00:00:01" >>/etc/firewall.user
