#!/bin/sh

#Populate uuid
uci set minidlna.config.uuid="4d696e69-444c-164e-9d41-$(uci get env.rip.eth_mac | sed 's/[\:]//g' | awk '{print tolower($0)}')"
#Set friendly_name
uci set minidlna.config.friendly_name="$(uci get env.var.prod_friendly_name)"
uci commit minidlna
