#!/bin/sh

_SSH=`uci get env.var.default_key_r0_s0`
uci set env.var.ssh="${_SSH}"

#passwordssh needs to be hashed (MD5, length of 10)
uci set env.var.passwordssh=`echo -n $_SSH | md5sum | cut -c 1-10`

uci commit env
