#!/bin/sh
#NG-71142

uci set dlnad.config.model_name="$(uci get env.var.variant_friendly_name)"
uci set dlnad.config.friendly_name="$(uci get env.var.prod_friendly_name_TIM)" #added NG-71142
uci set dlnad.config.uuid="$(cat /proc/sys/kernel/random/uuid)"
uci commit dlnad
