#!/bin/sh

#Wireless Guest_24GHz_xxxxxx and Guest_5GHz_xxxxxx
PRE="Guest_24GHz_"

uci set wireless.wl0_1=wifi-iface
uci set wireless.wl0_1.device='radio_2G'
uci set wireless.wl0_1.mode='ap'
uci set wireless.wl0_1.state='1'
uci set wireless.wl0_1.network='wlnet_b_24'
uci set wireless.wl0_1.ssid=$PRE`uci get env.var.ssid_mac_postfix_r0`
uci set wireless.wl0_1.reliable_multicast='0'

uci set wireless.ap2=wifi-ap
uci set wireless.ap2.iface='wl0_1'
uci set wireless.ap2.state='0'
uci set wireless.ap2.public='1'
uci set wireless.ap2.ap_isolation='1'
uci set wireless.ap2.station_history='1'
uci set wireless.ap2.max_assoc='0'
uci set wireless.ap2.security_mode='wpa2-psk'
uci set wireless.ap2.supported_security_modes='none wep wpa2-psk wpa-wpa2-psk wpa2 wpa-wpa2'
uci set wireless.ap2.pmf='disabled'
uci set wireless.ap2.wep_key=`uci get env.var.default_wep_key_r0_s0`
uci set wireless.ap2.wpa_psk_key=`uci get env.var.default_key_r0_s0`

uci set wireless.ap2.pmksa_cache='1'
uci set wireless.ap2.wps_state='0'
uci set wireless.ap2.wps_w7pbc='1'
uci set wireless.ap2.wsc_state='configured'
uci set wireless.ap2.wps_ap_setup_locked='1'
uci set wireless.ap2.wps_ap_pin='SET_BY_SCRIPT'
uci set wireless.ap2.acl_mode=disabled
uci set wireless.ap2.acl_registration_time='60'
uci set wireless.ap2.acl_accept_list=
uci set wireless.ap2.acl_deny_list=
uci set wireless.ap2.trace_modules=
uci set wireless.ap2.trace_level='some'
uci set wireless.ap2.display_connected_devices='1'
uci set wireless.ap2.wps_ap_pin=`uci get env.var.default_wps_ap_pin_r0_s1`
uci set wireless.ap2_auth0.secret=`uci get env.var.default_key_r0_s1`


# Is there a dual radio config ?
DUMMY=`uci get wireless.radio_5G`

if [ "$?" == "0" ] ; then


PRE5="Guest_5GHz_"
uci set wireless.wl1_1=wifi-iface		
uci set wireless.wl1_1.device='radio_5G'
uci set wireless.wl1_1.mode='ap'
uci set wireless.wl1_1.state='1'
#Quantenna Specific Setting
uci set wireless.wl1_1.vlan_id='3'
uci set wireless.wl1_1.network='wlnet_b_5'
uci set wireless.wl1_1.ssid=$PRE5`uci get env.var.ssid_mac_postfix_r0`  
uci set wireless.wl1_1.reliable_multicast='0'

uci set wireless.ap3=wifi-ap
uci set wireless.ap3.iface='wl1_1'
uci set wireless.ap3.state='0'
uci set wireless.ap3.public='1'
uci set wireless.ap3.ap_isolation='1'
uci set wireless.ap3.station_history='1'
uci set wireless.ap3.max_assoc='0'
uci set wireless.ap3.security_mode='wpa2-psk'
uci set wireless.ap3.supported_security_modes='none wpa2-psk wpa-wpa2-psk wpa2 wpa-wpa2'
uci set wireless.ap3.pmf='disabled'
uci set wireless.ap3.wep_key=`uci get env.var.default_wep_key_r0_s0`
uci set wireless.ap3.wps_ap_pin=`uci get env.var.default_wps_ap_pin_r1_s1`
uci set wireless.ap3.wpa_psk_key=`uci get env.var.default_key_r0_s0`
uci set wireless.ap3.pmksa_cache='1'
uci set wireless.ap3.wps_state='0'
uci set wireless.ap3.wps_w7pbc='1'
uci set wireless.ap3.wsc_state='configured'
uci set wireless.ap3.wps_ap_setup_locked='1'
uci set wireless.ap3.wps_ap_pin='SET_BY_SCRIPT'
uci set wireless.ap3.acl_mode=disabled
uci set wireless.ap3.acl_registration_time='60'
uci set wireless.ap3.acl_accept_list=
uci set wireless.ap3.acl_deny_list=
uci set wireless.ap3.trace_modules=
uci set wireless.ap3.trace_level='some'
uci set wireless.ap3.display_connected_devices='1'
uci set wireless.ap3_auth0.secret=`uci get env.var.default_key_r1_s1`
	
fi

uci commit wireless
