#!/bin/sh

if [ ! -f /etc/config/transformer ]; then
	touch /etc/config/transformer
fi

uci show transformer.@main[0] >/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
	uci add transformer main
fi

uci add_list transformer.@main[0].ignore_patterns='^Device%.'
uci add_list transformer.@main[0].ignore_patterns='DeviceInfo%.SoftwareBank%.'
uci add_list transformer.@main[0].ignore_patterns='DeviceInfo%.NewSoftwareBank$'
uci add_list transformer.@main[0].ignore_patterns='X_000E50_EnableIPv6$'
uci add_list transformer.@main[0].ignore_patterns='InternetGatewayDevice.DeviceInfo.ProcessStatus.Process'
uci add_list transformer.@main[0].ignore_patterns='X_TELSTRA_'
uci add_list transformer.@main[0].ignore_patterns='X_FASTWEB_'
uci add_list transformer.@main[0].ignore_patterns='X_BELGACOM_'
uci add_list transformer.@main[0].ignore_patterns='X_TESSARES_'
uci add_list transformer.@main[0].ignore_patterns='X_0876FF_' 
uci add_list transformer.@main[0].ignore_patterns='X_000E50_ACSBssList'
uci add_list transformer.@main[0].ignore_patterns='X_0876FF_ALG'
uci add_list transformer.@main[0].ignore_patterns='WANDSLDiagnostics'
uci add_list transformer.@main[0].ignore_patterns='X_000E50_Syslog'
uci add_list transformer.@main[0].ignore_patterns='X_000E50_Connection'
uci add_list transformer.@main[0].ignore_patterns='Layer2Bridging'
uci add_list transformer.@main[0].vendor_patterns='X_Management'
uci add_list transformer.@main[0].vendor_patterns='X_HostName'
uci add_list transformer.@main[0].vendor_patterns='X_List'
uci add_list transformer.@main[0].vendor_patterns='X_Port'
uci add_list transformer.@main[0].vendor_patterns='X_Call'
uci add_list transformer.@main[0].vendor_patterns='X_Three'
uci add_list transformer.@main[0].vendor_patterns='X_Auto'
uci add_list transformer.@main[0].vendor_patterns='X_ALG'
uci add_list transformer.@main[0].vendor_patterns='X_QoS'
uci add_list transformer.@main[0].vendor_patterns='X_AutoChannelReselectionEnable'
uci add_list transformer.@main[0].vendor_patterns='X_AutoChannelReselectionTimeout'
uci add_list transformer.@main[0].vendor_patterns='X_WPS_V2_ENABLE'
uci add_list transformer.@main[0].vendor_patterns='X_Status'
uci add_list transformer.@main[0].vendor_patterns='X_LastDataUplinkRate'
uci add_list transformer.@main[0].vendor_patterns='X_LastDataDownlinkRate'
uci add_list transformer.@main[0].vendor_patterns='X_Stats'
uci add_list transformer.@main[0].vendor_patterns='X_Scan'
uci add_list transformer.@main[0].vendor_patterns='X_HPSAInfo'
uci add_list transformer.@main[0].vendor_patterns='X_PBIT'
uci add_list transformer.@main[0].vendor_patterns='X_Connections'
uci add_list transformer.@main[0].vendor_patterns='X_WANDHCPOption12'
uci add_list transformer.@main[0].vendor_patterns='X_NumberOfCuts'
uci commit transformer
