#!/bin/sh

. /lib/functions/uci-defaults.sh

uci set system.config.enable_usb3_support='0'

if [ $(uci get env.rip.sw_flag) = "F2" ]; then
  uci delete system.ntp.server
  uci add_list system.ntp.server='ntp.internode.on.net'
  uci set system.@system[0].zonename='Australia/Adelaide'
  uci set system.@system[0].timezone='ACST-9:30ACDT,M10.1.0,M4.1.0/3'
fi

uci commit system
