#!/bin/sh
# UK Env Vars
uci set env.custovar=envvars
uci set env.var.first='1'
uci set env.var.WS='0'
uci set env.var.mtu_adsl='1500'
uci set env.var.mtu_vdsl='1492'
uci set env.var.mtu_eth='1492'
uci set env.var.vpi='0'
uci set env.var.vci='38'
uci set env.var.enc='vcmux'
uci set env.var.ulp='ppp'
uci set env.var.wan_vlan_enabled='1'
uci set env.var.wan_vlan_default='101'
uci set env.var.wan_vlan='101'
uci set env.var.setup='VDSL'
uci set env.var.ISP='your ISP'
uci set env.var.URL='www.technicolor.com'
uci set env.var.provisioning_code='Netlynk MST'
uci set env.var.rtfds='1'
uci set env.var.cwmpd_enabled='1'
uci set env.var.usbpower='0'
uci commit env

#FW SUFFIX
#uci set versioncusto.override=override
#uci set versioncusto.override.fwversion_suffix="-MST_1"
#uci commit versioncusto

#Samba
uci set samba.@samba[0].name="TG$(uci get env.var.prod_number)_Share"
uci set samba.@samba[0].description="$(uci get env.var.prod_friendly_name)"
uci set samba.@samba[0].enabled="$(uci get env.var.usbpower)"
uci commit samba

#MiniDLNA
uci set minidlna.config.enabled="$(uci get env.var.usbpower)"
uci commit minidlna

#Systemlog
uci set system.@system[0].log_prefix="$(uci get env.rip.factory_id)$(uci get env.rip.serial)"
uci commit system

#Workaround for WANSENSING not restarting correctly
sed -i 's/TERM/KILL/g' /etc/init.d/wansensing



