#!/bin/sh

opkg install /root/nanocdn.ipk
mv /root/temp_nanoCDN/nanocdn /etc/init.d/
mv /root/temp_nanoCDN/nanocdn.conf /etc/broadpeak/
rmdir /root/temp_nanoCDN/
##added to allow multicast traffic to be intercepted by IP host
echo "iptables -t raw -I PREROUTING -d 224.0.0.0/4 -j SKIPLOG" >>/etc/firewall.user
/etc/init.d/nanocdn restart
rm /root/nanocdn.ipk
