#!/bin/sh
set_time_reference() {
  local profile="$1"
  rand_sec=154$(tr -Cd "0-9" < /dev/urandom | head -c 7) 2>/dev/null
  local time_reference=$(date -d @$rand_sec -u +%FT%TZ)
  uci set bulkdata.${profile}.time_reference=$time_reference
}
config_load bulkdata
config_foreach set_time_reference profile
uci commit bulkdata
