#!/bin/sh
# UK Env Vars
uci set env.custovar=envvars
uci set env.custovar.first='1'
uci set env.custovar.WS='0'
uci set env.custovar.mtu_adsl='1500'
uci set env.custovar.mtu_vdsl='1492'
uci set env.custovar.mtu_eth='1492'
uci set env.custovar.vpi='0'
uci set env.custovar.vci='38'
uci set env.custovar.enc='vcmux'
uci set env.custovar.ulp='ppp'
uci set env.custovar.wan_vlan_enabled='1'
uci set env.custovar.wan_vlan_default='101'
uci set env.custovar.wan_vlan='101'
uci set env.custovar.setup='VDSL'
uci set env.custovar.ISP='your ISP'
uci set env.custovar.URL='www.technicolor.com'
uci set env.custovar.cwmpd_enabled='1'
uci set env.custovar.usbpower='0'
uci set env.var.provisioning_code='Netlynk MST'
uci set env.var.rtfds='1'

uci commit env

#FW SUFFIX
#uci set versioncusto.override=override
#uci set versioncusto.override.fwversion_suffix="-MST_1"
#uci commit versioncusto

#Samba
uci set samba.@samba[0].name="TG$(uci get env.var.prod_number) Share"
uci set samba.@samba[0].description="$(uci get env.var.prod_friendly_name)"
uci set samba.@samba[0].enabled="$(uci get env.custovar.usbpower)"
uci commit samba

#MiniDLNA
uci set minidlna.config.enabled="$(uci get env.custovar.usbpower)"
uci set minidlna.config.friendly_name="TG$(uci get env.var.prod_number) DLNA Share"
uci commit minidlna

#Systemlog
uci set system.@system[0].log_prefix="$(uci get env.rip.factory_id)$(uci get env.rip.serial)"
uci commit system

#mobiled
uci set mobiled.device_defaults.enabled="$(uci get env.custovar.usbpower)"
uci set mobiled.platform.power_on="$(uci get env.custovar.usbpower)"
uci commit mobiled

#lte-doctor
uci set lte-doctor.logger.enabled="$(uci get env.custovar.usbpower)"
uci commit lte-doctor


