#!/bin/sh

# if config file does not exist, create it
[ -f /etc/config/env ] || touch /etc/config/env

#if env.var does not exist, create it
uci get env.var || uci set env.var=envvars

#create generated variables
_OUI=`uci get env.rip.eth_mac | awk 'BEGIN {FS= ":"}  {print $1 $2 $3}'`
_OUI_OVERRIDE=`uci get env.var.oui_override_igd`
_SNPREFIX=`uci get env.var.prefix_serial_nbr`
_SERIAL=`uci get env.rip.serial`
uci set env.var.oui="${_OUI}"
uci set env.var.hardware_version=`uci get env.rip.board_mnemonic`
uci set env.var.pppuser="${_OUI_OVERRIDE}L${_SNPREFIX}${_SERIAL}@"`uci get env.var.pppdomainname`
_PPPPASSWD="${_OUI_OVERRIDE}${_SNPREFIX}${_SERIAL}"
uci set env.var.ppppasswd="${_PPPPASSWD}"
uci set env.var.cwmpuser="${_OUI_OVERRIDE}-${_SNPREFIX}${_SERIAL}"
uci set env.var.cwmppassw=`uci get env.rip.modem_access_code`
uci set env.var.friendly_sw_version_activebank=`lua -e "t=require'transformer.shared.banktable' print(t.getCurrentVersion())"`
uci set env.var.friendly_sw_version_passivebank=`lua -e "t=require'transformer.shared.banktable' print(t.getOtherVersion())"`
uci set env.var.prod_description="`uci get env.var.company_name` Internet Gateway Device"

homeware_banksize=`grep \"bank_1\" /proc/mtd | cut -d' ' -f2`
lte_kernel=`grep \"kernel1\" /proc/mtd | cut -d' ' -f2`
lte_root=`grep \"root1\" /proc/mtd | cut -d' ' -f2`
ubi=`grep \"ubi\" /proc/mtd | cut -d' ' -f2`
if [ -n "$homeware_banksize" ]; then
  uci set env.var.banksize="$(printf "%d" 0x$homeware_banksize)"
elif [ -n "$lte_kernel" ] && [ -n "$lte_root" ]; then
  uci set env.var.banksize="$(printf "%d" $((0x$lte_kernel + 0x$lte_root)))"
elif [ -n "$ubi" ]; then
  #currently set to the size of ubi directly. Needs to be changed in the future
  uci set env.var.banksize="$(printf "%d" 0x$ubi)"
else
  uci set env.var.banksize=134217728
fi

#ppppassword needs to be hashed (MD5, length of 30)
uci set env.var.ppppassword=`echo -n $_PPPPASSWD | md5sum | cut -c 1-30`

serial_suffix=''
uci set env.var.serial=$(uci get env.rip.factory_id)$(uci get env.rip.serial)${serial_suffix}

uci commit env
