#!/bin/sh

#Populate modelNumber
uci set upnpd.config.model_number="$(uci get env.var.prod_number)"

#Populate serialNumber
uci set upnpd.config.serial_number="$(uci get env.rip.serial)"

#Populate friendlyName changed to address NG-71142 #TCOMITAGW-2000
uci set upnpd.config.friendly_name="$(uci get env.var.prod_friendly_name_TIM)"

#Populate manufacturer
uci set upnpd.config.manufacturer="$(uci get env.var.company_name)"

#Populate model_name changed to address NG-71142
uci set upnpd.config.model_name="$(uci get env.var.variant_friendly_name)"

#Populate deny_cwmp.ext_ports
cwmp_port=`uci get cwmpd.cwmpd_config.connectionrequest_port`
if [ "$cwmp_port" == "" ] ; then
  cwmp_port=51007
fi
uci set upnpd.deny_cwmp.ext_ports="$cwmp_port"
uci set upnpd.config.enable_natpmp='0'
uci set upnpd.config.enable_upnp='0'
uci set upnpd.deny_cwmp.ext_ports='7170'
uci commit

