#!/bin/sh

. /lib/functions/uci-defaults.sh

# /etc/config/network

#set CWMP acs_user to OUI + Serial number:
uci set cwmpd.cwmpd_config.acs_user=$(uci get env.var.oui)-$(uci get env.rip.factory_id)$(uci get env.rip.serial)
#set CWMP acs_pass to $SRMPASSWORD:
uci set cwmpd.cwmpd_config.acs_pass=$(hexdump -v -n 5 -e '/1 "%02X"'  /proc/rip/0088; echo)

uci commit cwmpd
exit 0

