#!/bin/sh

mkdir -p /etc/ssl/paired

cat > /etc/config/generic_app <<EOF

config pnpserver pnpserver
	option registered '0'
	option gen_id '$(uci get env.var.serial)'
	option opco 'uk'
	option newdevice_timeout '7200'
	option log_level '3'
	option retryinterval '1'
EOF
