#!/bin/sh

# create smaller key for engineering boards to lower boot time

efu_allowed='/proc/efu/allowed'
dropbear_dir='/tmp/dropbear'
dropbear_rsa_key="${dropbear_dir}/dropbear_rsa_host_key"

[ ! -e "${dropbear_rsa_key}" -a -r "${efu_allowed}" ] && \
  grep -q 'skip_signature_check' "${efu_allowed}" && \
  grep -q 'allow_root_shell_access' "${efu_allowed}" && \
  mkdir -p "${dropbear_dir}" && \
  /usr/bin/dropbearkey -t rsa -s 768 -f "${dropbear_rsa_key}"

exit 0
