#!/bin/sh
#Remove files for boards that do not support DSL
xdsl_supported=`uci -q show xdsl`

if [ -z "$xdsl_supported" ]; then
  [ -f /usr/lib/lua/clash/modules/command/xdslctl_command.lua ] && rm -rf /usr/lib/lua/clash/modules/command/xdslctl_command.lua
  [ -f /usr/lib/lua/clash/modules/command/dsldiagd_command.lua ] && rm -rf /usr/lib/lua/clash/modules/command/dsldiagd_command.lua
fi

#Remove files for boards that do not support WiFi
wifi_supported=`uci -q show wireless`

if [ -z "$wifi_supported" ]; then
  [ -f /usr/lib/lua/clash/modules/command/wireless_autochannel_command.lua ] && rm -rf /usr/lib/lua/clash/modules/command/wireless_autochannel_command.lua
fi

#Remove files for boards that do not support WiFi_Conductor

wifi_conductor_supported=`uci -q show wifi_conductor`

if [ -z "$wifi_supported" ]; then
  [ -f /usr/lib/lua/clash/modules/command/wifi_conductor_command.lua ] && rm -rf /usr/lib/lua/clash/modules/command/wifi_conductor_command.lua
fi

