#!/bin/sh
# set xdsl EOC serial number to the serial number from RIP

version=$(uci get version.@version[0].version)

version="${version%%-*}"

uci set xdsl.dsl0.eoc_serial_number="$(uci get env.rip.factory_id)$(uci get env.rip.serial) $(uci get env.var.hardware_version) $version"

uci commit xdsl
