#!/bin/sh

. /lib/functions/uci-defaults.sh

uci set network.ppp=interface
uci set network.ppp.proto=pppoe
uci set network.ppp.metric=10

uci set network.ppp.username=newdsluser@bigpond.com
uci set network.ppp.password=new2dsl

uci set network.ppp.keepalive=4,20
uci set network.ppp.iface6rd=0
uci set network.ppp.graceful_restart=1

uci set network.ipoe=interface
uci set network.ipoe.proto=dhcp
uci set network.ipoe.metric=1
uci set network.ipoe.reqopts='1 3 6 43 51 58 59'
uci set network.ipoe.release='1'
uci set network.ipoe.iface6rd=0
uci set network.ipoe.vendorid=technicolor

uci set network.wan6=interface
uci set network.wan6.auto=0
uci set network.wan6.proto=dhcpv6
uci set network.wan6.reqopts='23 17'
uci set network.wan6.reqaddress=force
uci set network.wan6.noslaaconly=1
uci set network.wan6.iface_464xlat=0
uci set network.wan6.forceprefix=1
uci set network.wan6.soltimeout=240

uci set network.wwan=interface
uci set network.wwan.enabled=0

uci set network.wan=interface
uci set network.wan.auto=0

uci set network.eth4=device
uci set network.eth4.name=eth4
uci set network.eth4.mtu=1500
uci set network.eth4.mtu6=1500
uci set network.eth4.neighreachabletime=1200000
uci set network.eth4.neighgcstaletime=2400

uci set network.atm_8_35=device
uci set network.atm_8_35.name=atm_8_35
uci set network.atm_8_35.neighreachabletime=1200000
uci set network.atm_8_35.neighgcstaletime=2400

uci set network.ptm0=device
uci set network.ptm0.name=ptm0
uci set network.ptm0.neighreachabletime=1200000
uci set network.ptm0.neighgcstaletime=2400

uci add network ppp_placeholder
uci set network.@ppp_placeholder[0].uciname=pppoe-wan

uci commit network

exit 0
