#!/bin/sh

rm /etc/init.d/nanocdn
opkg install /root/nanocdn.ipk
mv /root/temp_nanoCDN/nanocdn /etc/init.d/
mkdir /etc/broadpeak/
mv /root/temp_nanoCDN/nanocdn.conf /etc/broadpeak/
mv /root/temp_nanoCDN/certs/ /etc/broadpeak/ 
rmdir /root/temp_nanoCDN/
##added to allow multicast traffic to be intercepted by IP host
echo "iptables -t raw -I PREROUTING -d 224.0.0.0/4 -j SKIPLOG" >>/etc/firewall.user
chmod 777 /etc/init.d/nanocdn
/etc/init.d/nanocdn start
rm /root/nanocdn.ipk
