#!/bin/sh

uci batch <<END
add firewall_helpers helper
set firewall_helpers.@helper[-1].name='ipsec'
set firewall_helpers.@helper[-1].description='IPsec connection tracking'
set firewall_helpers.@helper[-1].module='nf_conntrack_ipsec'
set firewall_helpers.@helper[-1].family='ipv4'
set firewall_helpers.@helper[-1].proto='udp'
set firewall_helpers.@helper[-1].port='500'
commit firewall_helpers
END
