#!/bin/sh
uci set cwmpd.cwmpd_config.connectionrequest_username="0018F6-Technicolor-CR-AG3play"
uci set cwmpd.cwmpd_config.connectionrequest_password="ChejEnEDetraprAzE3ESTuwruxerEmay"
uci set cwmpd.cwmpd_config.acs_user="0018F6-Thomson-AGBasAdv"
uci set cwmpd.cwmpd_config.acs_pass="C72hjT7Bol8x76hnKoP3Yi2a"
uci commit cwmpd
