#!/bin/sh

if uci -q get network.wwan; then
	uci set network.wwan.proto='mobiled'
	uci set network.wwan.session_id='0'
	uci set network.wwan.profile='1'
	uci set network.wwan.iface_464xlat='0'
	uci commit network
fi
