#!/bin/sh
status=$(uci get env.var.unlockedstatus)
if [ $status == "1" ] && [[ -f /etc/init.d/nanocdn ]]; then
     uci set system.mabr.enabled=0
     uci commit system
     /etc/init.d/nanocdn stop
fi
