#!/bin/sh

uci batch <<END
add firewall_helpers helper
set firewall_helpers.@helper[-1].name='huawei_fcc'
set firewall_helpers.@helper[-1].description='RTCP Huawei FCC connection tracking'
set firewall_helpers.@helper[-1].module='nf_conntrack_huawei_fcc'
set firewall_helpers.@helper[-1].family='ipv4'
set firewall_helpers.@helper[-1].proto='udp'
set firewall_helpers.@helper[-1].port='8027'
commit firewall_helpers
END
