#!/bin/sh

uci -q batch <<-EOT
        delete firewall.dropbear
        set firewall.dropbear=include
        set firewall.dropbear.type=script
        set firewall.dropbear.path=/lib/functions/firewall-dropbear.sh
        set firewall.dropbear.reload=1
        commit firewall
EOT

exit 0
