#!/bin/sh
DUMMY=`uci get wireless.radio_5G`

if [ "$?" == "0" ] ; then
  #If dev SW is running on the board, then force channel 36
  DEV=`uci get version.@version[0].version |cut -d '.' -f 3|cut -d '-' -f 1`
    
  if [ "$DEV" == "dev" ] ; then
    uci set wireless.radio_5G.channel=36
    uci commit wireless
  fi  
fi

