#!/bin/sh

config="clash"

# Custom passwords are temporarily stored to /var/state
# A next (!) firstboot script (tch_0073-clash) then creates the user with that password
_set_pw() {
	local usr="$1"
	local passw="$2"
	uci -P /var/state set ${config}.${usr}.passw=${passw}
}

# User support takes fixed password `support`
_set_pw "support" "support"

# User admin takes password based on gateway model
# The password Vodafone specifies is their commercial product name `VFH500-t`, prefixed with `VF-NZ`.
# At time of creation, Technicolor's VANT-9 is the only Vodafone board,
# hence this file is installed from that board-specific folder.
# If more Vodafone products are to be created, more customization may be needed.
_set_pw "admin" "VF-NZVFH500-t"
