#!/bin/sh

myserial="$(uci get env.rip.serial)"

#Populate serialNumber
uci set mqttjson_services.config.myThing_Name="$myserial"
uci set mqttjson_services.config.thing_shadow_path="\$aws/things/$myserial/shadow/update"
uci commit mqttjson_services
