#!/bin/sh
#NG-88913

. /lib/functions/provision.sh

# open root access on closed builds.
sed -i 's#\(root.*\)/bin/false#\1/bin/ash#' /etc/passwd

#Add serial, actually only possible be direct change of init.tab
#sed -i s/#tty/tty/g /etc/inittab
#sed -i s/#::ask/::ask/g /etc/inittab
# Send signal `HUP` to process ID `1` (the init process), to apply the changes made to /etc/inittab
#kill -HUP 1 

#Open Dropbear and enable for root
uci set dropbear.lan.enable='1'
uci set dropbear.lan.RootPasswordAuth='on'
uci set dropbear.lan.RootLogin='1'
uci commit







