#!/bin/sh

. /lib/functions/uci-defaults.sh

uci set network.globals=globals
uci set network.globals.default_ps='0'
#add this to avoid dscp2pbit script create rule since we do not using dscp2pbit
uci set network.globals.vlanmode='bcmvopi'

uci commit network

exit 0
