#!/bin/sh

. /lib/functions/provision.sh

# if config file does not exist, create it
[ -f /etc/config/ucidefaults ] || touch /etc/config/ucidefaults

_store_network_defaults() {
  local intf="$1"
  local section=$intf"_reset"
  uci set ucidefaults.$section=interface
  uci set ucidefaults.$section.ipaddr=$(uci get network.$intf.ipaddr)
  uci set ucidefaults.$section.netmask=$(uci get network.$intf.netmask)
  uci set ucidefaults.$section.ipv6=$(uci get network.$intf.ipv6)
}

_store_dhcp_defaults() {
  local intf="$1"
  local section=$intf"_reset"
  uci set ucidefaults.$section.start=$(uci get dhcp.$intf.start)
  uci set ucidefaults.$section.limit=$(uci get dhcp.$intf.limit)
  uci set ucidefaults.$section.leasetime=$(uci get dhcp.$intf.leasetime)
  uci set ucidefaults.$section.dhcpv4=$(uci get dhcp.$intf.dhcpv4)
  uci set ucidefaults.$section.dhcpv6=$(uci get dhcp.$intf.dhcpv6)
  uci set ucidefaults.$section.ra=$(uci get dhcp.$intf.ra)
  local dhcpOptions=$(uci get dhcp.$intf.dhcp_option)
  for option in $dhcpOptions; do
    uci add_list ucidefaults.$section.dhcp_option=$option
  done
}

_store_defaults() {
  local lanInterfaces
  local zone="$1"
  local wan=$(uci get firewall.$zone.wan)
  if [ "$wan" != "1" ] ; then
    lanInterfaces=$(uci get firewall.$zone.network)
  fi
  for intf in $lanInterfaces; do
    _store_network_defaults "$intf"
    _store_dhcp_defaults "$intf"
  done
}

config_load firewall

config_foreach _store_defaults zone

uci commit ucidefaults
