#!/bin/sh

mkdir -p /etc/shp_app_config
mkdir -p /etc/shp_app_config_state
touch /etc/shp_app_config/shp
uci -q set -c /etc/shp_app_config shp.global='shp'
uci -q set -c /etc/shp_app_config shp.global.serial="$(uci get env.var.serial)"
uci -q set -c /etc/shp_app_config shp.global.model_name="$(uci get env.var.prod_friendly_name)"
uci -q set -c /etc/shp_app_config shp.global.base_mac="$(uci get env.rip.eth_mac)"
uci -q set -c /etc/shp_app_config shp.global.lan_interface='br-lan'
uci -q set -c /etc/shp_app_config shp.global.wan_interface="$(uci get network.wan.ifname)"
uci -q set -c /etc/shp_app_config shp.global.country="$(uci get wireless.radio_2G.country)"
uci -q commit -c /etc/shp_app_config shp
