#!/usr/bin/lua

local duma_rules = {
	"/bower.json",
	"/ndindex.html",

	-- apps
	"/apps/com.netdumasoftware.adblocker/desktop/Scripts/lists.js",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/dayview.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-add-list-dialog.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-bubble-chart.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-chart-wrapper.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-day-view.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-device-entry.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-device-key.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-domain-burst-dialog.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-list.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-list-page.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-list-row.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-pause-button.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-queries-blocked-entry.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-status.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/DomModules/adblock-top-blocked.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/lists.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/overview.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/Scripts/index.js",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/Scripts/overview.js",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/Scripts/utillity.js",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/status.html",
	"/apps/com.netdumasoftware.adblocker/frontend/desktop/top_blocked.html",
	"/apps/com.netdumasoftware.adblocker/rpc/",
	"/apps/com.netdumasoftware.benchmark/desktop/tour.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/benchmark-add-scheduled.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/benchmark-graph.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/benchmark-history.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/benchmark-history-entry.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/benchmark-rating-icon.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/benchmark-schedule-entry.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/benchmark-schedules.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/benchmark-time.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/duma-bloat-rating.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/duma-ping-rating.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/duma-speed-rating.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/DomModules/rating.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/overview.html",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/Scripts/index.js",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/Scripts/overview.js",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/Scripts/shared.js",
	"/apps/com.netdumasoftware.benchmark/frontend/desktop/tour.html",
	"/apps/com.netdumasoftware.benchmark/rpc/",
	"/apps/com.netdumasoftware.burstwatch/rpc/",
	"/apps/com.netdumasoftware.config/rpc/",
	"/apps/com.netdumasoftware.ctwatch/rpc/",
	"/apps/com.netdumasoftware.desktop/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.desktop/frontend/desktop/index.js",
	"/apps/com.netdumasoftware.desktop/rpc/",
	"/apps/com.netdumasoftware.devicemanager/frontend/desktop/device-tree.html",
	"/apps/com.netdumasoftware.devicemanager/frontend/desktop/device-tree.js",
	"/apps/com.netdumasoftware.devicemanager/frontend/desktop/device-wifi-stats.html",
	"/apps/com.netdumasoftware.devicemanager/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.devicemanager/frontend/desktop/index.js",
	"/apps/com.netdumasoftware.devicemanager/frontend/desktop/radio-scan.html",
	"/apps/com.netdumasoftware.devicemanager/rpc/",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/allow-deny.html",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/allow-deny.js",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/devices.js",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/geo-filter.html",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/geofilter-device-selector.html",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/geo-map.html",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/geo-map.js",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/index.js",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/ping.html",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/ping.js",
	"/apps/com.netdumasoftware.geofilter/frontend/desktop/tour.html",
	"/apps/com.netdumasoftware.geofilter/rpc/",
	"/apps/com.netdumasoftware.internetmeasurer/rpc/",
	"/apps/com.netdumasoftware.networkmonitor/rpc/",
	"/apps/com.netdumasoftware.ngportal/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.networkmonitor/desktop/first-level-breakdown-graph.html",
	"/apps/com.netdumasoftware.networkmonitor/desktop/first-level-breakdown-graph.js",
	"/apps/com.netdumasoftware.networkmonitor/desktop/network-monitor.html",
	"/apps/com.netdumasoftware.networkmonitor/desktop/snapshot-graph.html",
	"/apps/com.netdumasoftware.networkmonitor/desktop/snapshot-graph.js",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/first-level-breakdown-graph.html",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/first-level-breakdown-graph.js",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/index.js",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/network-monitor.html",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/overview-graph.html",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/overview-graph.js",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/second-level-breakdown-graph.html",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/second-level-breakdown-graph.js",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/snapshot-graph.html",
	"/apps/com.netdumasoftware.networkmonitor/frontend/desktop/snapshot-graph.js",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/add-to-list.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/bulk-add-ip.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/index.js",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/ping-custom-list.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/ping-graph.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/ping-graph.js",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/ping-history.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/ping-history-range.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/ping-map.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/ping-map.js",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/ping-log.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/ping-servers-svg.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/set-tracking.html",
	"/apps/com.netdumasoftware.pingheatmap/frontend/desktop/util.html",
	"/apps/com.netdumasoftware.pingheatmap/rpc/",
	"/apps/com.netdumasoftware.procmanager/rpc/",
	"/apps/com.netdumasoftware.qos/desktop/lane-information.html",
	"/apps/com.netdumasoftware.qos/desktop/qos.html",
	"/apps/com.netdumasoftware.qos/frontend/desktop/device.html",
	"/apps/com.netdumasoftware.qos/frontend/shared/device-icons.html",
	"/apps/com.netdumasoftware.qos/frontend/desktop/device.js",
	"/apps/com.netdumasoftware.qos/frontend/desktop/flower.html",
	"/apps/com.netdumasoftware.qos/frontend/desktop/flower.js",
	"/apps/com.netdumasoftware.qos/frontend/desktop/hyper-lane.html",
	"/apps/com.netdumasoftware.qos/frontend/desktop/hyper-lane.js",
	"/apps/com.netdumasoftware.qos/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.qos/frontend/desktop/index.js",
	"/apps/com.netdumasoftware.qos/frontend/desktop/lane-information.html",
	"/apps/com.netdumasoftware.qos/frontend/desktop/lane-information.js",
	"/apps/com.netdumasoftware.qos/frontend/desktop/qos.html",
	"/apps/com.netdumasoftware.qos/frontend/desktop/qos-auto-setup.html",
	"/apps/com.netdumasoftware.qos/frontend/desktop/sliders.html",
	"/apps/com.netdumasoftware.qos/frontend/desktop/sliders.js",
	"/apps/com.netdumasoftware.qos/frontend/desktop/tour.html",
	"/apps/com.netdumasoftware.qos/rpc/",
	"/apps/com.netdumasoftware.systeminfo/desktop/system-information.html",
	"/apps/com.netdumasoftware.systeminfo/desktop/system-information.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/cpu-usage.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/cpu-usage.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/flash-usage.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/flash-usage.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/guest-wireless-status.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/guest-wireless-status.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/index.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/installed-apps.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/installed-apps.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/internet-status.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/internet-status.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/logs.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/logs.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/network-status.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/network-status.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/ram-usage.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/ram-usage.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/system-information.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/system-information.js",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/wireless-status.html",
	"/apps/com.netdumasoftware.systeminfo/frontend/desktop/wireless-status.js",
	"/apps/com.netdumasoftware.systeminfo/rpc/",
	"/apps/com.netdumasoftware.trafficcontroller/frontend/desktop/index.html",
	"/apps/com.netdumasoftware.trafficcontroller/frontend/desktop/index.js",
	"/apps/com.netdumasoftware.trafficcontroller/frontend/desktop/logs.html",
	"/apps/com.netdumasoftware.trafficcontroller/frontend/desktop/logs.js",
	"/apps/com.netdumasoftware.trafficcontroller/frontend/desktop/rule-add-dialog.html",
	"/apps/com.netdumasoftware.trafficcontroller/frontend/desktop/rules.html",
	"/apps/com.netdumasoftware.trafficcontroller/frontend/desktop/rules.js",
	"/apps/com.netdumasoftware.trafficcontroller/frontend/desktop/rules-table.html",
	"/apps/com.netdumasoftware.trafficcontroller/frontend/desktop/traffic_numbers.html",
	"/apps/com.netdumasoftware.trafficcontroller/frontend/desktop/traffic_numbers.js",
	"/apps/com.netdumasoftware.trafficcontroller/rpc/",

	-- desktop
	"/desktop/application-sidebar.html",
	"/desktop/badbrowser.html",
	"/desktop/chrome-https.html",
	"/desktop/ddt.html",
	"/desktop/ddt_back.html",
	"/desktop/telstra_dumaos_disabled.html",
	"/desktop/eula.html",
	"/desktop/index.html",
	"/desktop/index.js",
	"/desktop/language-selector.html",
	"/desktop/network-speeds.html",
	"/desktop/rapp-overview.html",
	"/desktop/services-info.html",
	"/desktop/setup.html",
	"/desktop/setup_main.js",
	"/desktop/setup_util.js",
	"/desktop/time-selector.html",
	"/desktop/tour.html",
	"/desktop/try-the-mobile-app.html",
	"/desktop/unittests.html",
	"/desktop/unsupported.js",

	-- nd-js
	"/nd-js/applications.js",
	"/nd-js/blockadblock.js",
	"/nd-js/bowser.js",
	"/nd-js/browser-setup.js",
	"/nd-js/chart.js",
	"/nd-js/chart-extensions.js",
	"/nd-js/colours.js",
	"/nd-js/connection-processor.js",
	"/nd-js/cron.js",
	"/nd-js/cycle.js",
	"/nd-js/d3.js",
	"/nd-js/d3v5.min.js",
	"/nd-js/devices.js",
	"/nd-js/es5-shim.js",
	"/nd-js/es6-shim.js",
	"/nd-js/es7-shim.js",
	"/nd-js/events.js",
	"/nd-js/gridstack.js",
	"/nd-js/hopscotch.js",
	"/nd-js/jquery.js",
	"/nd-js/jquery-knob.js",
	"/nd-js/jquery-legacy-browsers.js",
	"/nd-js/jquery-ui.js",
	"/nd-js/math.js",
	"/nd-js/moment.js",
	"/nd-js/patternomaly.js",
	"/nd-js/q.js",
	"/nd-js/rpc.js",
	"/nd-js/sampler.js",
	"/nd-js/score-util.js",
	"/nd-js/sprintf.js",
	"/nd-js/stdlib.js",
	"/nd-js/storage.js",
	"/nd-js/svg-injector.js",
	"/nd-js/svg-util.js",
	"/nd-js/time.js",
	"/nd-js/topojson.min.js",
	"/nd-js/tour.js",
	"/nd-js/util.js",
	"/nd-js/vectors2.js",
	"/nd-js/word-type.js",

	-- libs
	"/libs/applications.html",
	"/libs/chart.html",
	"/libs/chart-extensions.html",
	"/libs/colours.html",
	"/libs/connection-processor.html",
	"/libs/cron.html",
	"/libs/cycle.html",
	"/libs/d3.html",
	"/libs/d3v5.html",
	"/libs/devices.html",
	"/libs/events.html",
	"/libs/gridstack.html",
	"/libs/hopscotch.html",
	"/libs/jquery.html",
	"/libs/jquery-knob.html",
	"/libs/jquery-ui.html",
	"/libs/lodash.html",
	"/libs/math.html",
	"/libs/moment.html",
	"/libs/q.html",
	"/libs/required-page-imports.html",
	"/libs/rpc.html",
	"/libs/sampler.html",
	"/libs/score-util.html",
	"/libs/sprintf.html",
	"/libs/storage.html",
	"/libs/svg-injector.html",
	"/libs/svg-util.html",
	"/libs/time.html",
	"/libs/topojson.html",
	"/libs/tour.html",
	"/libs/util.html",
	"/libs/vectors2.html",
	"/libs/word-type.html",

	-- nd-css
	"/nd-css/duma-icons.html",
	"/nd-css/duma-styles.html",
	"/nd-css/duma-application-icons.html",

	-- json
	"/json/categories.json",
	"/json/clusters.json",
	"/json/countries.json",
	"/json/poll.json",
	"/json/qos_categories.json",
	"/json/_services_.json",
	"/json/world-countries-low-detail.json",

	-- custom-elements
	"/custom-elements/web-animations-js/web-animations.html",
	"/custom-elements/web-animations-js/web-animations.min.js",
	"/custom-elements/web-animations-js/web-animations-next.min.js",
	"/custom-elements/web-animations-js/web-animations-next-lite.min.js",
	"/custom-elements/app-layout/app-box/app-box.html",
	"/custom-elements/app-layout/app-drawer/app-drawer.html",
	"/custom-elements/app-layout/app-drawer-layout/app-drawer-layout.html",
	"/custom-elements/app-layout/app-grid/app-grid-style.html",
	"/custom-elements/app-layout/app-header/app-header.html",
	"/custom-elements/app-layout/app-header-layout/app-header-layout.html",
	"/custom-elements/app-layout/app-layout.html",
	"/custom-elements/app-layout/app-scroll-effects/app-scroll-effects.html",
	"/custom-elements/app-layout/app-scroll-effects/app-scroll-effects-behavior.html",
	"/custom-elements/app-layout/app-scrollpos-control/app-scrollpos-control.html",
	"/custom-elements/app-layout/app-toolbar/app-toolbar.html",
	"/custom-elements/app-layout/app-scroll-effects/effects/blend-background.html",
	"/custom-elements/app-layout/app-scroll-effects/effects/fade-background.html",
	"/custom-elements/app-layout/helpers/helpers.html",
	"/custom-elements/app-layout/app-scroll-effects/effects/material.html",
	"/custom-elements/app-layout/app-scroll-effects/effects/parallax-background.html",
	"/custom-elements/app-layout/app-scroll-effects/effects/resize-snapped-title.html",
	"/custom-elements/app-layout/app-scroll-effects/effects/resize-title.html",
	"/custom-elements/app-layout/app-scroll-effects/effects/waterfall.html",
	"/custom-elements/app-layout/patterns/transform-navigation/x-app.html",
	"/custom-elements/drag-table/drag-table.html",
	"/custom-elements/drag-table/dragula.js",
	"/custom-elements/duma-alert/duma-alert.html",
	"/custom-elements/duma-chart/duma-chart.html",
	"/custom-elements/duma-chart-scrollable/duma-chart-scrollable.html",
	"/custom-elements/duma-checkbox-tree/duma-checkbox-tree.html",
	"/custom-elements/duma-clipboard-button/duma-clipboard-button.html",
	"/custom-elements/duma-days/duma-days.html",
	"/custom-elements/duma-device-edit/duma-device-edit.html",
	"/custom-elements/duma-device-selector/duma-device-selector.html",
	"/custom-elements/duma-drag-table/duma-drag-table.html",
	"/custom-elements/duma-flower/duma-flower.html",
	"/custom-elements/duma-font-roboto/roboto.html",
	"/custom-elements/duma-hidden/duma-hidden.html",
	"/custom-elements/duma-icon-tree/duma-icon-tree.html",
	"/custom-elements/duma-image/duma-image.html",
	"/custom-elements/duma-input-behavior/duma-input-behavior.html",
	"/custom-elements/duma-input-behavior/duma-input-inputs-behavior.html",
	"/custom-elements/duma-ip-input/duma-ip-input.html",
	"/custom-elements/duma-ip-input/duma-ip-input-inputs.html",
	"/custom-elements/duma-legend/duma-legend.html",
	"/custom-elements/duma-legend/duma-legend-item-behavior.html",
	"/custom-elements/duma-legend/duma-legend-item.html",
	"/custom-elements/duma-legend/duma-legend-item-horizontal.html",
	"/custom-elements/duma-legend/duma-legend-item-vertical.html",
	"/custom-elements/duma-location-search/duma-location-search.html",
	"/custom-elements/duma-mac-input/duma-mac-input.html",
	"/custom-elements/duma-mac-input/duma-mac-input-inputs.html",
	"/custom-elements/duma-map/duma-map.html",
	"/custom-elements/duma-menu/duma-menu.html",
	"/custom-elements/duma-panels/duma-panel.html",
	"/custom-elements/duma-panels/duma-panels.html",
	"/custom-elements/duma-requires-rapp/duma-requires-rapp.html",
	"/custom-elements/duma-selector/duma-data-selector.html",
	"/custom-elements/duma-selector/duma-device-selector.html",
	"/custom-elements/duma-selector/duma-flat-service-selector.html",
	"/custom-elements/duma-selector/duma-port-selector.html",
	"/custom-elements/duma-selector/duma-schedule-selector.html",
	"/custom-elements/duma-selector/duma-selector.html",
	"/custom-elements/duma-selector/duma-tree-service-selector.html",
	"/custom-elements/duma-sort-behaviour/duma-sort-behaviour.html",
	"/custom-elements/duma-splash/duma-splash.html",
	"/custom-elements/duma-table/duma-table.html",
	"/custom-elements/duma-tick/duma-tick.html",
	"/custom-elements/duma-timewheel/duma-timewheel.html",
	"/custom-elements/duma-zoom-slider/duma-zoom-slider.html",
	"/custom-elements/file-upload/file-upload.html",
	"/custom-elements/file-upload/file-upload-icons.html",
	"/custom-elements/font-roboto/roboto.html",
	"/custom-elements/font-roboto/roboto.html.bac",
	"/custom-elements/granite-led/granite-led.html",
	"/custom-elements/iron-a11y-announcer/iron-a11y-announcer.html",
	"/custom-elements/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html",
	"/custom-elements/iron-autogrow-textarea/iron-autogrow-textarea.html",
	"/custom-elements/iron-behaviors/iron-button-state.html",
	"/custom-elements/iron-behaviors/iron-control-state.html",
	"/custom-elements/iron-checked-element-behavior/iron-checked-element-behavior.html",
	"/custom-elements/iron-collapse/iron-collapse.html",
	"/custom-elements/iron-dropdown/iron-dropdown.html",
	"/custom-elements/iron-dropdown/iron-dropdown-scroll-manager.html",
	"/custom-elements/iron-data-table/array-datasource.js",
	"/custom-elements/iron-data-table/iron-data-table.html",
	"/custom-elements/iron-data-table/data-table-cell.html",
	"/custom-elements/iron-data-table/data-table-checkbox.html",
	"/custom-elements/iron-data-table/data-table-column.html",
	"/custom-elements/iron-data-table/data-table-column-filter.html",
	"/custom-elements/iron-data-table/data-table-column-sort.html",
	"/custom-elements/iron-data-table/default-styles.html",
	"/custom-elements/iron-data-table/data-table-icons.html",
	"/custom-elements/iron-data-table/data-table-row.html",
	"/custom-elements/iron-data-table/data-table-row-detail.html",
	"/custom-elements/iron-data-table/data-table-templatizer-behavior.html",
	"/custom-elements/iron-fit-behavior/iron-fit-behavior.html",
	"/custom-elements/iron-flex-layout/classes/iron-flex-layout.html",
	"/custom-elements/iron-flex-layout/iron-flex-layout.html",
	"/custom-elements/iron-flex-layout/iron-flex-layout-classes.html",
	"/custom-elements/iron-flex-layout/classes/iron-shadow-flex-layout.html",
	"/custom-elements/iron-form-element-behavior/iron-form-element-behavior.html",
	"/custom-elements/iron-icon/iron-icon.html",
	"/custom-elements/iron-icons/av-icons.html",
	"/custom-elements/iron-icons/communication-icons.html",
	"/custom-elements/iron-icons/device-icons.html",
	"/custom-elements/iron-icons/editor-icons.html",
	"/custom-elements/iron-icons/hardware-icons.html",
	"/custom-elements/iron-icons/image-icons.html",
	"/custom-elements/iron-icons/iron-icons.html",
	"/custom-elements/iron-icons/maps-icons.html",
	"/custom-elements/iron-icons/notification-icons.html",
	"/custom-elements/iron-icons/places-icons.html",
	"/custom-elements/iron-icons/social-icons.html",
	"/custom-elements/iron-iconset-svg/iron-iconset-svg.html",
	"/custom-elements/iron-image/iron-image.html",
	"/custom-elements/iron-input/iron-input.html",
	"/custom-elements/iron-list/iron-list.html",
	"/custom-elements/iron-media-query/iron-media-query.html",
	"/custom-elements/iron-menu-behavior/iron-menu-behavior.html",
	"/custom-elements/iron-menu-behavior/iron-menubar-behavior.html",
	"/custom-elements/iron-meta/iron-meta.html",
	"/custom-elements/iron-overlay-behavior/iron-overlay-backdrop.html",
	"/custom-elements/iron-overlay-behavior/iron-overlay-behavior.html",
	"/custom-elements/iron-overlay-behavior/iron-focusables-helper.html",
	"/custom-elements/iron-overlay-behavior/iron-overlay-manager.html",
	"/custom-elements/iron-pages/iron-pages.html",
	"/custom-elements/iron-range-behavior/iron-range-behavior.html",
	"/custom-elements/iron-resizable-behavior/iron-resizable-behavior.html",
	"/custom-elements/iron-scroll-target-behavior/iron-scroll-target-behavior.html",
	"/custom-elements/iron-selector/iron-multi-selectable.html",
	"/custom-elements/iron-selector/iron-selector.html",
	"/custom-elements/iron-selector/iron-selectable.html",
	"/custom-elements/iron-selector/iron-selection.html",
	"/custom-elements/iron-validatable-behavior/iron-validatable-behavior.html",
	"/custom-elements/iron-validator-behavior/iron-validator-behavior.html",
	"/custom-elements/neon-animation/neon-animatable.html",
	"/custom-elements/neon-animation/neon-animatable-behavior.html",
	"/custom-elements/neon-animation/neon-animated-pages.html",
	"/custom-elements/neon-animation/neon-animation.html",
	"/custom-elements/neon-animation/neon-animation-behavior.html",
	"/custom-elements/neon-animation/neon-animation-runner-behavior.html",
	"/custom-elements/neon-animation/neon-animations.html",
	"/custom-elements/neon-animation/animations/cascaded-animation.html",
	"/custom-elements/neon-animation/animations/fade-in-animation.html",
	"/custom-elements/neon-animation/animations/fade-out-animation.html",
	"/custom-elements/neon-animation/animations/hero-animation.html",
	"/custom-elements/neon-animation/animations/opaque-animation.html",
	"/custom-elements/neon-animation/animations/reverse-ripple-animation.html",
	"/custom-elements/neon-animation/animations/ripple-animation.html",
	"/custom-elements/neon-animation/animations/scale-down-animation.html",
	"/custom-elements/neon-animation/animations/scale-up-animation.html",
	"/custom-elements/neon-animation/neon-shared-element-animatable-behavior.html",
	"/custom-elements/neon-animation/neon-shared-element-animation-behavior.html",
	"/custom-elements/neon-animation/animations/slide-down-animation.html",
	"/custom-elements/neon-animation/animations/slide-from-bottom-animation.html",
	"/custom-elements/neon-animation/animations/slide-from-left-animation.html",
	"/custom-elements/neon-animation/animations/slide-from-right-animation.html",
	"/custom-elements/neon-animation/animations/slide-from-top-animation.html",
	"/custom-elements/neon-animation/animations/slide-left-animation.html",
	"/custom-elements/neon-animation/animations/slide-right-animation.html",
	"/custom-elements/neon-animation/animations/slide-up-animation.html",
	"/custom-elements/neon-animation/animations/transform-animation.html",
	"/custom-elements/neon-animation/web-animations.html",
	"/custom-elements/paper-badge/paper-badge.html",
	"/custom-elements/paper-behaviors/paper-button-behavior.html",
	"/custom-elements/paper-behaviors/paper-checked-element-behavior.html",
	"/custom-elements/paper-behaviors/paper-inky-focus-behavior.html",
	"/custom-elements/paper-behaviors/paper-ripple-behavior.html",
	"/custom-elements/paper-button/paper-button.html",
	"/custom-elements/paper-card/paper-card.html",
	"/custom-elements/paper-checkbox/paper-checkbox.html",
	"/custom-elements/paper-dialog/paper-dialog.html",
	"/custom-elements/paper-dialog-behavior/paper-dialog-behavior.html",
	"/custom-elements/paper-dialog-behavior/paper-dialog-common.css",
	"/custom-elements/paper-dialog-scrollable/paper-dialog-scrollable.html",
	"/custom-elements/paper-dialog-behavior/paper-dialog-shared-styles.html",
	"/custom-elements/paper-drawer-panel/paper-drawer-panel.html",
	"/custom-elements/paper-dropdown-menu/paper-dropdown-menu-icons.html",
	"/custom-elements/paper-dropdown-menu/paper-dropdown-menu-light.html",
	"/custom-elements/paper-dropdown-menu/paper-dropdown-menu.html",
	"/custom-elements/paper-dropdown-menu/paper-dropdown-menu-shared-styles.html",
	"/custom-elements/paper-fab/paper-fab.html",
	"/custom-elements/paper-header-panel/paper-header-panel.html",
	"/custom-elements/paper-icon-button/paper-icon-button.html",
	"/custom-elements/paper-icon-button/paper-icon-button-light.html",
	"/custom-elements/paper-input/paper-input.html",
	"/custom-elements/paper-input/paper-input-addon-behavior.html",
	"/custom-elements/paper-input/paper-input-behavior.html",
	"/custom-elements/paper-input/paper-input-char-counter.html",
	"/custom-elements/paper-input/paper-input-container.html",
	"/custom-elements/paper-input/paper-input-error.html",
	"/custom-elements/paper-input/all-imports.html",
	"/custom-elements/paper-input/paper-textarea.html",
	"/custom-elements/paper-item/paper-item.html",
	"/custom-elements/paper-item/paper-item-behavior.html",
	"/custom-elements/paper-item/paper-item-body.html",
	"/custom-elements/paper-item/paper-icon-item.html",
	"/custom-elements/paper-item/all-imports.html",
	"/custom-elements/paper-item/paper-item-shared-styles.html",
	"/custom-elements/paper-listbox/paper-listbox.html",
	"/custom-elements/paper-material/paper-material.html",
	"/custom-elements/paper-material/paper-material-shared-styles.html",
	"/custom-elements/paper-menu/paper-menu.html",
	"/custom-elements/paper-menu-button/paper-menu-button.html",
	"/custom-elements/paper-menu-button/paper-menu-button-animations.html",
	"/custom-elements/paper-menu/paper-menu-shared-styles.html",
	"/custom-elements/paper-menu/paper-submenu.html",
	"/custom-elements/paper-progress/paper-progress.html",
	"/custom-elements/paper-radio-button/paper-radio-button.html",
	"/custom-elements/paper-radio-group/paper-radio-group.html",
	"/custom-elements/paper-range-slider/paper-range-slider.html",
	"/custom-elements/paper-ripple/paper-ripple.html",
	"/custom-elements/paper-slider-shared-behavior/paper-slider-shared-behavior.html",
	"/custom-elements/paper-slider/paper-slider.html",
	"/custom-elements/paper-spinner/paper-spinner.html",
	"/custom-elements/paper-spinner/paper-spinner-behavior.html",
	"/custom-elements/paper-spinner/paper-spinner-lite.html",
	"/custom-elements/paper-spinner/paper-spinner-styles.html",
	"/custom-elements/paper-styles/paper-styles.html",
	"/custom-elements/paper-styles/classes/typography.html",
	"/custom-elements/paper-styles/paper-styles-classes.html",
	"/custom-elements/paper-styles/color.html",
	"/custom-elements/paper-styles/classes/global.html",
	"/custom-elements/paper-styles/classes/shadow.html",
	"/custom-elements/paper-styles/classes/shadow-layout.html",
	"/custom-elements/paper-styles/shadow.html",
	"/custom-elements/paper-styles/default-theme.html",
	"/custom-elements/paper-styles/typography.html",
	"/custom-elements/paper-tabs/paper-tabs.html",
	"/custom-elements/paper-tabs/paper-tabs-icons.html",
	"/custom-elements/paper-tabs/paper-tab.html",
	"/custom-elements/paper-toast/paper-toast.html",
	"/custom-elements/paper-toggle-button/paper-toggle-button.html",
	"/custom-elements/paper-toolbar/paper-toolbar.html",
	"/custom-elements/paper-tooltip/paper-tooltip.html",
	"/custom-elements/paper-tree/paper-tree.html",
	"/custom-elements/paper-tree/paper-tree-node.html",
	"/custom-elements/polymer/polymer.html",
	"/custom-elements/polymer/polymer-micro.html",
	"/custom-elements/polymer/polymer-mini.html",
	"/custom-elements/vertical-progress/vertical-progress.html",
	"/custom-elements/vertical-slider/vertical-slider.html",
	"/custom-elements/webcomponentsjs/webcomponents-lite.min.js",

	-- cgi-bin
	"/cgi-bin/domain_list.has",
	"/cgi-bin/redirect.lua",
	"/cgi-bin/restart.htm",
	"/cgi-bin/runtests.cgi",
	"/cgi-bin/uhttpd.sh",
	"/cgi-bin/url-routing.lua",

	-- data
	"/data/shorthash",

	-- language
	"/language/dumaoslang-English.json",
}

local uci = require("uci")
local cursor = uci.cursor()

local config_name = "web"
local ruleset_name = "ruleset_main"
local rule_list_name = "rules"

local duma_rule_prefix = "dumaos_"
local duma_rule_pattern = "^" .. duma_rule_prefix

-- Remove all existing NetDuma rules.
local rule_names = {}
for _, rule_name in ipairs(cursor:get(config_name, ruleset_name, rule_list_name) or {}) do
	if rule_name:match(duma_rule_pattern) then
		-- The rule is a NetDuma rule. Remove the corresponding rule from the config and
		-- do not copy the rule name to the new rule list of the ruleset.
		cursor:delete(config_name, rule_name)
	else
		-- The rule is not a NetDuma rule. Do not remove the rule from the config and
		-- copy the rule name to the new rule list of the ruleset.
		table.insert(rule_names, rule_name)
	end
end

local function parse_last_word(last_word)
  local short
  for section in last_word:gmatch("[^.-]+") do
    if not short then
      short = section:sub(1,4)
    else
      short = short.."_"..section:sub(1,4)
    end
  end
  if not short then
    short = last_word
  end
  return short
end

local function create_rule_name(rule_target)
  local rule_name, last_word
  for word in rule_target:gmatch("[^/]+") do
    if last_word and not rule_name then
      rule_name = parse_last_word(last_word)
    elseif last_word then
      rule_name = rule_name .. "_" .. parse_last_word(last_word)
    end
    last_word = word
  end
  if not last_word then
    error("Unable to match anything for "..rule_target)
  end
  last_word = last_word:gsub("%-","_")
  last_word = last_word:gsub("%.","_")
  if not rule_name then
    rule_name = last_word
  else
    rule_name = rule_name .. "_" .. last_word
  end
  rule_name = duma_rule_prefix .. rule_name
  return rule_name
end

local duplicate_check = {}

-- Create the new NetDuma rules.
for _, rule_target in ipairs(duma_rules) do
  local rule_name = create_rule_name(rule_target)
  if duplicate_check[rule_name] then
    error("Duplicate name created, should not occur: "..rule_target)
  end
  duplicate_check[rule_name] = true
  -- Create a section for the rule.
  cursor:set(config_name, rule_name, "rule")
  cursor:set(config_name, rule_name, "target", rule_target)
  cursor:set(config_name, rule_name, "roles", {"admin", "guest"})

  -- Add the rule to the rule list of the ruleset.
  table.insert(rule_names, rule_name)
end

cursor:set(config_name, ruleset_name, rule_list_name, rule_names)

cursor:commit(config_name)
