#!/bin/sh /etc/rc.common

START=10
STOP=90

INTERFACE=eth0

start() {
  local hostname=$(uname -n)
  ifconfig $INTERFACE up || return 0
  odhcpc -i $INTERFACE -s /usr/lib/dhcp.sh -h $hostname -p /var/dhcp-$INTERFACE
}

stop() {
  kill $(cat /var/dhcp-$INTERFACE)
  ifconfig $INTERFACE down
}