#!/bin/sh

# This script is to delete the content from the /etc/bulkdata/ of both the bank_1 & bank_2

overlay_dir="/overlay/bank_1/etc/bulkdata"
	if [ -d "$overlay_dir" ]; then
	  #To delete the contents from the bank_1 directory
          rm  -rf "$overlay_dir"/*
          echo "Deleted the $overlay_dir files"
	fi

overlay_dir="/overlay/bank_2/etc/bulkdata"
	if [ -d "$overlay_dir" ]; then
	  #To delete the contents from the bank_2 directory
          rm  -rf "$overlay_dir"/*
          echo "Deleted the $overlay_dir files"
	fi

