#!/bin/sh

# Check if any configuration need to be removed
rm -rf /overlay/*.remove_due_to_upgrade
CURRENT_INACTIVE_BANK=$(cat /proc/banktable/inactive)
echo "removing unnecessary files from inactive bank" $CURRENT_INACTIVE_BANK > /dev/console
greengrass_package_path="$(readlink -f /root/greengrass/ggc/core)"
rm -rf /overlay/$CURRENT_INACTIVE_BANK/$greengrass_package_path/lambda
