#!/bin/sh

RTFD=/overlay/remove_due_to_rtfd

if [ -L $RTFD ]; then
	bank=$(readlink $RTFD)
	if [ ! -z "$(ls $bank/etc/ispconfig 2>/dev/null)" ]; then
		echo "preserving ispconfig for $bank"
		cd $bank/etc/ispconfig
		tar -czf /overlay/ispconfig-$(basename $bank).tgz *
	else
		echo "no ispconfig to preserve"
	fi
fi