#!/bin/sh

RTFD_MARK=/overlay/remove_due_to_rtfd

if [ ! -d /proc/banktable ]; then
	echo "**************************************************"
	echo "* RTFD NOT IMPLEMENTED FOR SINGLE BANK PLATFORMS *"
	echo "**************************************************"
	exit
fi

if [ -L /overlay/remove_due_to_rtfd ]; then
	reset_bank=$(readlink /overlay/remove_due_to_rtfd)
	echo "Applying reset to factory default to $reset_bank"
	rm -rf $reset_bank
fi
