#!/bin/sh

parameter_conversion=1

if [ -L /overlay/remove_due_to_rtfd ]; then
	echo "rtfd was requested, parameter conversion will be skipped"
	parameter_conversion=0
fi

if [ ! -f /proc/banktable/booted ]; then
	echo "******************************************************************"
	echo "* PARAMETER CONVERSION NOT IMPLEMENTED FOR SINGLE BANK PLATFORMS *"
	echo "******************************************************************"
	exit 0
fi

booted_bank=/overlay/$(cat /proc/banktable/booted)
passive_bank=/overlay/$(cat /proc/banktable/notbooted)

mark_parameter_conversion() {
	local config=${1:-$passive_bank}
	if [ "$parameter_conversion" = "1" ]; then
		# Indicate the source configuration for parameter conversion
		echo "Enabling parameter conversion from $config"
		ln -sfn $config /overlay/homeware_conversion
	fi
}

# Check if Homeware configuration is available on the active bank
if [ -d $booted_bank ]; then
	echo "HOMEWARE_CONFIG_ON_ACTIVE_BANK"

# Check if Homeware configuration is available on the passive bank
elif [[ -d $passive_bank ]]; then
	echo "HOMEWARE_CONFIG_ON_PASSIVE_BANK"
	mkdir $booted_bank

	# Check if configuration could be cleaned up (in case of config on root or legacy)
	if [ -d /overlay/etc/config ]; then
		rm -rf $(find /overlay -maxdepth 1 -path "/overlay/bank_*" -prune -o -path /overlay -o -print)
	fi

	# No legacy SW anymore, Homeware on both banks, all legacy config can be erased
	[ -L /overlay/config-bank-lastboot ] &&	rm /overlay/config-bank-lastboot
	[ -d /overlay/config-bank-1 -o -d /overlay/config-bank-2 -o -d /overlay/common ] && \
		rm -rf /overlay/config-bank-[12] /overlay/common && \
		echo "All legacy configuration erased"

	mark_parameter_conversion

# Check if Homeware configuration is available on root jffs2 partition
elif [[ -d /overlay/etc/config ]]; then
	echo "HOMEWARE_CONFIG_ON_ROOT"
	mkdir $booted_bank
	mark_parameter_conversion /overlay

# Check for legacy configuration
elif [ -L /overlay/config-bank-lastboot ]; then
	if [ -d /overlay/$(basename $(readlink /overlay/config-bank-lastboot)) ] && [ "$parameter_conversion" = "1" ]; then
		echo "LEGACY_CONFIG"
		# Remove Legacy configuration of erased SW bank
		unused_legacy_bank=/overlay/$(basename $(readlink /overlay/config-bank-lastboot) | sed 's/1$/2/;t;s/2$/1/')
		[ -d $unused_legacy_bank ] && rm -rf $unused_legacy_bank && echo "Legacy configuration $unused_legacy_bank erased"

		# Set the default value to check migration is needed.
		touch /overlay/legacy_conversion
	fi

# no config found out, possibly running for the 1st time a BLI with an empty userfs
else
	echo "NO_CONFIG_FOUND"
fi
