#! /bin/sh

CONFIG=/etc/config/cwmpd
INITDAY="1970-01-01"
DAY=$(date +"%Y-%m-%d")

if [ $DAY != $INITDAY ] && !(grep -q "firstusedate" $CONFIG 2>/dev/null); then
    TIME=$(date -u +"%Y-%m-%dT%TZ")
    uci set cwmpd.cwmpd_config.firstusedate=$TIME
    uci commit cwmpd
fi
