#!/bin/sh /etc/rc.common
# (C) NETDUMA Software 2016
# Do *NOT* enable this script. We run it from hotplug when the br-lan interface
# comes up.



START=99
PROG=${DUMAOS_SYSROOT}/usr/bin/arpwatch
MODEL="$(cat ${DUMAOS_SYSROOT}/dumaossystem/model)"
ENABLE_COREDUMPS=

# Use procd if available otherwise revert to old method
if type procd > /dev/null; then
  USE_PROCD=1
else
  SERVICE_DAEMONIZE=1
  SERVICE_WRITE_PID=1
fi

get_iface(){
  IFACE=""
  IFIDX=""

  if [ "$(cat ${DUMAOS_SYSROOT}/dumaossystem/odm)" = "SEAL" ];then
    IFACE="br-lan"
  else
    IFACE="$(ubus call network.interface.lan status | grep -i "l3_device" | cut -d ":" -f 2 | tr -d "\" ,")"
    IFACE="${IFACE:?}"
  fi

  #-- @depends test
  #-- @test test 1
  if [ -z "$IFACE" ]; then
    #-- @depends logger; arpwatch
    #-- @test which logger && which arpwatch
    logger -t arpwatch -p 3 -s "Couldn't get LAN interface name."
  fi

  #-- @depends cat
  #-- @test which cat
  IFIDX="$(cat /sys/class/net/${IFACE}/ifindex)"

  #-- @depends test
  #-- @test test 1
  if [ -z "$IFIDX" ]; then
    #-- @depends logger; arpwatch
    #-- @test which logger && which arpwatch
    logger -t arpwatch -p 3 -s "Couldn't get interface number."
  fi
}

set_up_coredumps(){
  sysctl -w "kernel.core_pattern=/tmp/%e.%p.%s.%t.core"
  if [ ! -e "/.init_enable_core"  ];then
    touch /.init_enable_core
    sync
  fi
}

start_service() {
  get_iface

  procd_open_instance
  procd_set_param command "$PROG"
  procd_append_param command -i "$IFIDX"

  # run in own process space, meaning daemon will have pid
  # unfortunately init already binds a RTNETLINK with id 1
  # so we need a unique pid, we can just use this shells id
  procd_append_param command -p "$$"

  procd_append_param command -d
  procd_set_param respawn # respawn on crash
  if [ "$MODEL"  = "R2" ] && [ -n "$ENABLE_COREDUMPS" ];then
    #Set core files size to unlimited
    procd_set_param limits core="unlimited"  # Set ulimit core files blocks
	set_up_coredumps
  fi
  procd_set_param stdout 0 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr

  # jail it - notice it needs no mount points as no files read/written
  procd_add_jail arpwatch ubus log
  procd_close_instance
}

# procd not available
start() {
  #-- @depends cat
  #-- @test which cat
  get_iface
  service_start $PROG -i $IFIDX -p $$ -d
}

stop() {
  service_stop $PROG
}

