#!/bin/sh /etc/rc.common

START=11

boot() {
	. $IPKG_INSTROOT//lib/config/uci.sh

	local MODULE_DIR="/lib/modules/$(uname -r)"
	[ -f "$MODULE_DIR"/xhci-hcd.ko -a "$(uci_get system config enable_usb3_support 1)" -ne 0 ] && {
		insmod xhci-hcd
		[ -f "$MODULE_DIR"/xhci-plat-hcd.ko ] && insmod xhci-plat-hcd
	}
	[ -f "$MODULE_DIR"/ehci-hcd.ko -a "$(uci_get system config enable_usb2_support 1)" -ne 0 ] && {
		insmod ehci-hcd
		[ -f "$MODULE_DIR"/ehci-platform.ko ] && insmod ehci-platform
		[ -f "$MODULE_DIR"/ehci-pci.ko ] && insmod ehci-pci;
	}
	[ -f "$MODULE_DIR"/ohci-hcd.ko -a "$(uci_get system config enable_usb1_support 1)" -ne 0 ] && {
		insmod ohci-hcd
		[ -f "$MODULE_DIR"/ohci-platform.ko ] && insmod ohci-platform
		[ -f "$MODULE_DIR"/ohci-pci.ko ] && insmod ohci-pci;
	}

	return 0
}
