#!/bin/sh /etc/rc.common

START=51

start() {
	# This can make CMS be debugged, but output logs may be too many.
	# Redirect stdin, stdout and stderr to /dev/console
	exec </dev/console >/dev/console 2>&1 

	# Start management system (CMS)
	# echo "Starting CMS smd..." > /dev/console
	if [ -x /bin/smd ]; then
		/bin/smd
	fi
}

stop() {
	echo "stop" > /dev/console
}
