#!/bin/sh /etc/rc.common

START=10

boot() {
	mknod /dev/bcmadsl0 c 208 0
	mknod /dev/bcmadsl1 c 208 1
	mknod /dev/bcmarl c 245 0
	mknod /dev/pcmshim0 c 217 0
	mknod /dev/bcmendpoint0 c 209 0
	mknod /dev/bcmfap c 241 0
	mknod /dev/bcmxtmcfg0 c 228 0
	mknod /dev/bcmvlan c 238 0
	mknod /dev/bpm c 244 0
	mknod /dev/brcmboard c 206 0
	mknod /dev/fcache c 242 0
	mknod /dev/gmac c 249 0
	mknod /dev/ingqos c 243 0
	mknod /dev/p8021ag0 c 227 0
	mknod /dev/pwrmngt c 240 0
	mknod /dev/spu c 233 0
	mknod /dev/bdmf_shell c 215 0
	mknod /dev/tms c 250 0
}

