#!/bin/sh /etc/rc.common

START=10

boot_3_4() {
	mknod /dev/bcmadsl0 c 208 0
	mknod /dev/bcmadsl1 c 208 1
	mknod /dev/bcmarl c 245 0
	mknod /dev/bcmendpoint0 c 209 0
	mknod /dev/bcmfap c 241 0
	mknod /dev/bcmxtmcfg0 c 228 0
	mknod /dev/bcmvlan c 238 0
	mknod /dev/bpm c 244 0
	mknod /dev/brcmboard c 206 0
	mknod /dev/fcache c 242 0
	mknod /dev/gmac c 249 0
	mknod /dev/ingqos c 243 0
	mknod /dev/p8021ag0 c 227 0
	mknod /dev/pwrmngt c 240 0
	mknod /dev/spu c 233 0
	mknod /dev/bcmtm c 239 0
	mknod /dev/bdmf_shell c 215 0
	mknod /dev/tms c 250 0
}


boot_4_1_38() {
	# Create Broadcom Proprietary devices   ALL major numbers not assigned by kernel.org must be > 256
	mknod /dev/dect c 3051 0
	mknod /dev/dectdbg c 3051 1
	mknod /dev/slicslac c 3050 1
	mknod /dev/htsk c 3050 2
	mknod /dev/ac97 c 3060 0

	mknod /dev/pwrmngt c        3000 0
	mknod /dev/bcmfap c         3001 0
	mknod /dev/fcache c         3002 0
	mknod /dev/ingqos c         3003 0
	mknod /dev/bpm c            3004 0
	mknod /dev/bcmarl c         3005 0
	mknod /dev/chipinfo c       3006 0
	mknod /dev/bcm_user_tod c   3007 0
	mknod /dev/tms c            3008 0
	mknod /dev/pktrunner c      3009 0
	mknod /dev/otp c            3010 0
	mknod /dev/ext_bonding c    3011 0
	mknod /dev/fbond c          3012 0
	mknod /dev/bcmepon c        3013 0
	mknod /dev/laser_dev c      3014 0
	mknod /dev/ivi c            3015 0
	mknod /dev/bcmomcipm c      3016 0
	mknod /dev/bcm_user_ploam c 3017 0
	mknod /dev/bcm_omci c       3018 0
	mknod /dev/bcm_ploam c      3019 0
	mknod /dev/opticaldetect c  3020 0
	mknod /dev/bdmf_shell c     3021 0
	mknod /dev/rgs_logger c     3022 0
	mknod /dev/bcmvlan c        3023 0
	mknod /dev/buzzz c          3024 0
	mknod /dev/sysperf c        3025 0
	mknod /dev/gmac c           3026 0
	mknod /dev/bcmtm c          3027 0
	mknod /dev/spdsvc c         3028 0
	mknod /dev/bcmxtmcfg0 c     3029 0
	mknod /dev/bcmprof c        3030 0
	mknod /dev/bcm c            3031 0
	mknod /dev/bcmatm0 c        3032 0
	mknod /dev/bcmadsl0 c       3033 0
	mknod /dev/bcmadsl1 c       3033 1
	mknod /dev/detector c       3034 0
	mknod /dev/astra c   3035 0
	mknod /dev/tzioc c   3036 0
	#node /dev/bcmrdpa c        3037 0 is created by rdpa_cmd.ko
	mknod /dev/blog c           3038 0

	# ADD NEW PROPIETARY DEVICE NODES ABOVE THIS LINE -- ALL MAJOR NUMBERS NOT ASSIGNED BY KERNEL.ORG MUST BE > 256
}

boot_4_1_27() {
	# Create Broadcom Proprietary devices   ALL major numbers not assigned by kernel.org must be > 256
	mknod /dev/detector c 190 0
	mknod /dev/dect c 197 0
	mknod /dev/dectdbg c 197 1
	mknod /dev/fbond c 204 0
	mknod /dev/bcmatm0 c 205 0
	mknod /dev/bcmadsl0 c 208 0
	mknod /dev/bcmadsl1 c 208 1
	mknod /dev/slicslac c 209 1
	mknod /dev/htsk c 209 2
	mknod /dev/bcm c 212 0
	mknod /dev/rgs_logger c 216 0
	mknod /dev/spdsvc c 220 0
	mknod /dev/ac97 c 222 0
	mknod /dev/bcmprof c 224 0
	mknod /dev/sysperf c 227 0
	mknod /dev/bcmxtmcfg0 c 228 0
	mknod /dev/bcmtm c 229 0
	mknod /dev/bcmomcipm c 231 0
	mknod /dev/bcm_user_ploam c 235 0
	mknod /dev/bcm_omci c 236 0
	mknod /dev/bcm_ploam c 237 0
	mknod /dev/bcmvlan c 238 0
	mknod /dev/laser_dev c 239 0
	mknod /dev/pwrmngt c      3000 0
	mknod /dev/bcmfap c       3001 0
	mknod /dev/fcache c       3002 0
	mknod /dev/ingqos c       3003 0
	mknod /dev/bpm c          3004 0
	mknod /dev/bcmarl c       3005 0
	mknod /dev/chipinfo c     3006 0
	mknod /dev/bcm_user_tod c 3007 0
	mknod /dev/tms c          3008 0
	mknod /dev/pktrunner c    3009 0
	mknod /dev/otp c          3010 0
	mknod /dev/ext_bonding c  3011 0
	mknod /dev/ivi c          3015 0
	# ADD NEW PROPIETARY DEVICE NODES ABOVE THIS LINE -- ALL MAJOR NUMBERS NOT ASSIGNED BY KERNEL.ORG MUST BE > 256

	# Create Broadcom Opensource devices -- ALL MAJOR NUMBERS NOT ASSIGNED BY KERNEL.ORG MUST BE > 256
	mknod /dev/bounce c 213 0
	mknod /dev/pmon c 214 0
	mknod /dev/bdmf_shell c 215 0
	mknod /dev/opticaldetect c 230 0
	mknod /dev/spu c 233 0
	mknod /dev/bcmmoca0 c 234 0
	mknod /dev/bcmmoca1 c 234 1
	mknod /dev/bcmepon c 247 0
	mknod /dev/gmac c 249 0
	mknod /dev/buzzz c 253 0
	mknod /dev/baloo c 254 0
}

boot_4_1() {
	boot_$(uname -r | tr . _) >/dev/null 2>&1 || true

	# Create Broadcom Opensource devices -- ALL MAJOR NUMBERS NOT ASSIGNED BY KERNEL.ORG MUST BE > 256
	mknod /dev/btusb0 c 180 194
}

boot() {
	boot_$(uname -r | cut -d. -f1-2 | tr . _)
}
