#!/bin/sh /etc/rc.common

START=10

. $IPKG_INSTROOT/lib/functions.sh

boot() {
    insmod bdmf

    insmod bcmlibs
    insmod rdpa_gpl
    insmod rdpa
    insmod rdpa_mw
    insmod bcm_ingqos
    insmod rdpa_cmd

    /etc/rdpa_init.sh
}
