#!/bin/sh /etc/rc.common

START=17
STOP=92
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
unset SERVICE_MATCH_EXEC

start() {
	service_start /usr/bin/bcmubusbridge
}

stop() {
	service_stop /usr/bin/bcmubusbridge && echo >/var/run/bcmubusbridge.pid
}
