#!/bin/sh /etc/rc.common

START=17
APP=bcmubusbridge
PID_FILE=/var/run/$APP.pid

start() {
        start-stop-daemon -S -x $APP -p $PID_FILE -m -b
}

stop() {
        start-stop-daemon -K -n $APP -p $PID_FILE -s INT
        rm -rf $PID_FILE
}
