#!/bin/sh /etc/rc.common

source /lib/functions/functions-tch.sh

# After modules loaded and XDSL started
START=19

# Match the priorities Broadcom set on several kthreads.
# Information based on eid_bcm_kthreads.txt, wlmngr and running threads.

start() {
    # USB workqueue thread
    setrtprio khubd 5

    # Broadcom Buffer Pool Manager thread
    setrtprio bpm 75

    # Broadcom FAP GSO LOOPBACK thread
    setrtprio fapGsoLoopBk 5

    # Broadcom bcmenet driver threads
    setrtprio bcmsw_rx 5
    setcpumask bcmsw_rx 1
    setrtprio wfd 5

    # Wlan processing threads
    setrtprio wl0-kthrd 5
    setrtprio wl1-kthrd 5

    #############################################
    #Configure priority for Technicolor Packages#
    #############################################

}
