#!/bin/sh /etc/rc.common

. $IPKG_INSTROOT/lib/functions/functions-tch.sh

# After modules loaded and XDSL started
START=19

# Match the priorities Broadcom set on several kthreads.
# Information based on eid_bcm_kthreads.txt, wlmngr and running threads.

setRadioIntAffinity() {
    local radio=$1;
    local affinity=$2;
    local irq=$(cat /proc/interrupts | grep wl$radio | cut -d: -f1 | tr -d ' ');
    if [ ! -z $affinity ]; then
        echo $affinity >/proc/irq/$irq/smp_affinity 2>/dev/NULL
        #nvram kset wl${radio}_interrupt_affinity=${affinity}
    fi
}

start() {
    local BCM_MODEL=`cat /proc/device-tree/model 2>/dev/null`

    # USB workqueue thread
    setrtprio khubd 5

    # Broadcom Buffer Pool Manager thread
    setrtprio bpm 75

    # Broadcom FAP GSO LOOPBACK thread
    setrtprio fapGsoLoopBk 5

    # Broadcom bcmenet driver threads
    setrtprio bcmsw_rx 5
    setcpumask bcmsw_rx 1

    setrtprio bcmxtm_rx 5
    setcpumask bcmxtm_rx 1

    if [ "$BCM_MODEL" == "Broadcom BCM947622" ]; then  # Archer based platforms with 4 cpu cores
        setrtprio bcm_archer_us 0 other
        setcpumask bcm_archer_us 8

        setrtprio bcm_archer_wlan 0 other

        setrtprio bcmsw_recycle 75 fifo

        setrtprio bcmFlwStatsTask 0 other
    elif [ "$BCM_MODEL" == "Broadcom BCM963178" ]; then # Archer based platforms with 3 cpu cores
        setrtprio bcm_archer_us 0 other
        setcpumask bcm_archer_us 4

        setrtprio bcm_archer_wlan 0 other
        setcpumask bcm_archer_wlan 2

        setrtprio bcmsw_recycle 75 fifo
        setcpumask bcmsw_recycle 4

        setrtprio bcmxtm_recycle 75 fifo
        setcpumask bcmxtm_recycle 4

        setrtprio bcmFlwStatsTask 0 other
    fi

    ## WLAN ##
    # Thread prio
    # WFD < 4.16L03
    setrtprio wfd 5

    # WFD >= 4.16L03
    setrtprio wfd0-thrd 5
    setrtprio wfd1-thrd 5

    # Wlan driver
    setrtprio wl0-kthrd 5
    setrtprio wl1-kthrd 5
    if [ "$(process_exists wl2-kthrd)" = "1" ] ; then
        setrtprio wl2-kthrd 5
    fi
    setrtprio dhd0_dpc 5
    setrtprio dhd1_dpc 5
    if [ "$(process_exists dhd2_dpc)" = "1" ] ; then
        setrtprio dhd2_dpc 5
    fi

    # CPU affinity (see logic in userspace/private/apps/wlan/wlmngr.c)
    cpu_type=`uname -m`

    nr_wlan=1
    if [ "$(process_exists wl1-kthrd)" = "1" ] || [ "$(process_exists dhd1_dpc)" = "1" ] ; then
        nr_wlan=2
    fi

    if [ "$nr_wlan" = "1" ] ; then
        #If arm: bind on TP0 + also bind wfd
        #If mips: bind wl on TP1, dhd on TP0

        if [ "$cpu_type" = "armv7l" ] ; then
            setcpumask wl0-kthrd 1
            setcpumask dhd0_dpc  1
            setcpumask wfd0-thrd 1
        else
            setcpumask wl0-kthrd 2
            setcpumask dhd0_dpc  1
        fi
    else
        #If wl0 and dhd1: put dhd1 on tp0 to line up with brcm ref where detection order is different
        #If wl0 and wl1: also fix skbFreeTask to TP0 (to improve 11ac perf)
        #If arm: also bind wfd
        if [ "$(process_exists wl0-kthrd)" = "1" ] && [ "$(process_exists dhd1_dpc)" = "1" ] ; then
            setcpumask wl0-kthrd 2
            setRadioIntAffinity 0 2

            # Line up with brcm ref
            if [ "$BCM_MODEL" == "Broadcom BCM963178" ]; then # Archer based platforms with 3 cpu cores
                setcpumask dhd1_dpc 2
                setRadioIntAffinity 1 2
            else
                setcpumask dhd1_dpc 1
                setRadioIntAffinity 1 1
            fi

            if [ "$cpu_type" = "armv7l" ] || [ "$cpu_type" == "aarch64" ]; then
                setcpumask wfd0-thrd 2
                setcpumask wfd1-thrd 1
            fi
        else
            # Line up with brcm ref
            if [ "$BCM_MODEL" == "Broadcom BCM963178" ]; then # Archer based platforms with 3 cpu cores
                setcpumask wl0-kthrd 2
                setcpumask dhd0_dpc  2

                setRadioIntAffinity 0 2

                setcpumask wl1-kthrd 2
                setcpumask dhd1_dpc  2

                setRadioIntAffinity 1 2
            elif [ "$BCM_MODEL" == "Broadcom BCM96846" ] && [ -e "/etc/dhd_runner_keys" ]; then
                setcpumask dhd0_dpc  2

                setRadioIntAffinity 0 1

                setcpumask dhd1_dpc  1

                setRadioIntAffinity 1 2

            else
                setcpumask wl0-kthrd 1
                setcpumask dhd0_dpc  1

                setRadioIntAffinity 0 1

                setcpumask wl1-kthrd 2
                setcpumask dhd1_dpc  2

                setRadioIntAffinity 1 2

                if [ "$BCM_MODEL" == "Broadcom BCM947622" ]; then  # Archer based platforms with 4 cpu cores
                    setcpumask wl2-kthrd 4
                    setcpumask dhd2_dpc  4

                    setRadioIntAffinity 2 4
                fi
            fi

            setcpumask skbFreeTask   1 #Before 5.02L03
            setcpumask skb_free_task 1 #From   5.02L03

            if [ "$cpu_type" = "armv7l" ] || [ "$cpu_type" == "aarch64" ]; then
                setcpumask wfd0-thrd 1
                setcpumask wfd1-thrd 2
            fi
        fi
    fi

    #Broadcom traffic manager kernel thread affinity(see eid_bcm_kthreads.txt)
    if [ "$(process_exists bcm_tm_thread)" = "1" ] ; then
        setcpumask bcm_tm_thread 2
        setrtprio bcm_tm_thread 99 fifo
    fi

    #############################################
    #Configure priority for Technicolor Packages#
    #############################################
}
