#!/bin/sh /etc/rc.common
# Copyright © 2016 Technicolor

# has to be before nginx, which is currently on S80
START=79

boot() {
	mkdir -p /tmp/ssl/data
	setkey >/tmp/ssl/data/pairing
	if [ $? -eq 0 ]; then
		ln -s /etc/ssl/data/cert.pem /tmp/ssl/data/cert
	else
		# failed to set key, fallback to auto generated
		ln -sf /etc/nginx/server.crt /tmp/ssl/data/cert
		ln -sf /etc/nginx/server.key /tmp/ssl/data/pairing
	fi
}
