#!/bin/sh /etc/rc.common

START=05
USE_PROCD=1

CGCONFIGPARSER_BIN=/usr/sbin/cgconfigparser
CGCLEAR_BIN=/usr/sbin/cgclear
CONFIG_FILE=/etc/cgconfig.conf

start_service()
{
        local is_cgroup_mounted=""

        # if cgroups is already mounted clear it firstly.
        # it's work round soultion to be compatible with procd, for procd will mount cgroups to /sys/fs/cgroup/
        # we should remove it and mount it to our own directory as specified in /etc/cgconfig.conf
        is_cgroup_mounted=`lssubsys`
        if [ -n "$is_cgroup_mounted" ] ; then
            logger -t cgconfig "cgroup is already mounted(subsys:$is_cgroup_mounted),clear it"
            stop_service
        fi

        logger -t cgconfig "Start cgconfig service..."

        if [ ! -s $CONFIG_FILE ] ; then
            logger -t cgconfig "$CONFIG_FILE not exist or empty"
            return 1
        fi

        $CGCONFIGPARSER_BIN -l $CONFIG_FILE
}

stop_service()
{
        logger -t cgconfig "Stop cgconfig service..."
        $CGCLEAR_BIN
}


