#!/bin/sh /etc/rc.common

START=06
USE_PROCD=1

CGRED_BIN=/usr/sbin/cgrulesengd
CGRED_CONF=/etc/cgrules.conf

start_service()
{
        local args="-n -Q -u root"
        logger -t cgred "Starting CGroup Rules Engine Daemon..."

        if [ ! -s $CGRED_CONF ]; then
                logger -t cgred  "$CGRED_CONF not exist or empty"
                return 1
        fi

        procd_open_instance
        procd_set_param command $CGRED_BIN $args
        procd_set_param file $CGRED_CONF
        procd_set_param respawn
        procd_close_instance
}

stop_service()
{
        logger -t cgred "Stopping CGroup Rules Engine Daemon..."
        rm -f /var/run/cgred.socket
}

reload_service()
{
        logger -t cgred "Reloading CGroup Rules Engine Daemon..."
        rc_procd start_service "$@"
        return 0
}


