#!/bin/sh /etc/rc.common

source /lib/functions/functions-tch.sh

START=20

start() {
    if [ -d /cgroups/cpumemblk ];
    then
        cd /cgroups/cpumemblk
        if [ ! -d constrained_rt_processes ];
        then
            mkdir constrained_rt_processes
        fi
        cd constrained_rt_processes

        # Check whether current platform is 11ac platform or not
        if (pidof wl1-kthrd > /dev/null); then
            setcpumask wfd0-thrd 0x02
            setcpumask wfd1-thrd 0x01

            pid_bcmsw_rx=`pidof bcmsw_rx`
            pid_wl0_kthrd=`pidof wl0-kthrd`
            pid_wfd1_thrd=`pidof wfd1-thrd`
            pid_skbfree=`pidof skbFreeTask`

            /bin/echo 11000 > cpu.rt_runtime_us
            /bin/echo 26000 > cpu.rt_period_us
            /bin/echo $pid_bcmsw_rx > tasks
            /bin/echo $pid_wl0_kthrd > tasks
            /bin/echo $pid_wfd1_thrd > tasks
            /bin/echo $pid_skbfree > tasks

            # Move serial interrupt from cpu2 to cpu1, make it more responsive when throtteling is active
            serial_interrupt_num=`cat /proc/interrupts | awk '/serial/{print substr($1, 1, length($1)-1)}'`
            echo 1 > /proc/irq/$serial_interrupt_num/smp_affinity
        fi
    fi
}

stop() {
    if [ -d /cgroups/cpumemblk ];
    then
        cd /cgroups/cpumemblk

        # Check whether current platform is 11ac platform or not
        if (pidof wl1-kthrd > /dev/null); then
            setcpumask wfd0-thrd 0x03
            setcpumask wfd1-thrd 0x03

            pid_bcmsw_rx=`pidof bcmsw_rx`
            pid_wl0_kthrd=`pidof wl0-kthrd`
            pid_wfd1_thrd=`pidof wfd1-thrd`
            pid_skbfree=`pidof skbFreeTask`

            /bin/echo $pid_bcmsw_rx > tasks
            /bin/echo $pid_wl0_kthrd > tasks
            /bin/echo $pid_wfd1_thrd > tasks
            /bin/echo $pid_skbfree > tasks

            rmdir constrained_rt_processes

            # Move serial interrupt back to cpu2
            serial_interrupt_num=`cat /proc/interrupts | awk '/serial/{print substr($1, 1, length($1)-1)}'`
            echo 2 > /proc/irq/$serial_interrupt_num/smp_affinity
        fi
    fi
}

