#!/bin/sh /etc/rc.common

START=11

start()
{
	# Mounting cgroups and creating Technicolor cgroup hierarchy
	# For now combine cpu, memory and blkio subsystem into one hierarchy
	if [ -f /proc/cgroups ];
	then
		mkdir -p /cgroups
		mount -t tmpfs cgroup_root /cgroups
		mkdir -p /cgroups/cpumemblk
		mount -t cgroup -ocpu,memory,blkio cpumemblk /cgroups/cpumemblk/
	fi

}
