#!/bin/sh /etc/rc.common
# (C) NETDUMA Software 2020

START=99
PROG=${DUMAOS_SYSROOT}/usr/bin/connwatch
PROG_PID_FILE=/var/run/connwatch.pid
MODEL="$(cat ${DUMAOS_SYSROOT}/dumaossystem/model)"
ENABLE_COREDUMPS=

if type procd 1>/dev/null
then
	USE_PROCD="1"
else
	SERVICE_DAEMONIZE="1"
	SERVICE_WRITE_PID="1"
fi

set_up_coredumps(){
  sysctl -w "kernel.core_pattern=/tmp/%e.%p.%s.%t.core"
  if [ ! -e "/.init_enable_core"  ];then
    touch /.init_enable_core
    sync
  fi
}

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
    if [ "${MODEL}" = "R2" ] && [ -n "$ENABLE_COREDUMPS" ];then
        #Set core files size to unlimited
        procd_set_param limits core="unlimited"  # Set ulimit core files blocks
        set_up_coredumps
    fi
	procd_set_param respawn
	procd_close_instance
}

start() {
	SERVICE_PID_FILE="$PROG_PID_FILE"
	service_start "$PROG"
}

stop() {
	SERVICE_PID_FILE="$PROG_PID_FILE"
	service_stop "$PROG"
}

