#!/bin/sh /etc/rc.common
# This file is Confidential Information of Cujo LLC.
# Copyright (c) 2018-2019 CUJO LLC. All rights reserved.

# This should be earlier than any of the rabid-oem scripts.
# shellcheck disable=SC2034
START=90

# shellcheck disable=SC2034
USE_PROCD=1

CUJO_USER='cujo'
IPTABLES_LOCK_FILE='/var/run/xtables.lock'
RUN_PATH='/var/run'

start_service()
{
	if [ ! -f ${IPTABLES_LOCK_FILE} ]; then
		touch ${IPTABLES_LOCK_FILE}
	fi
	chown root:${CUJO_USER} ${IPTABLES_LOCK_FILE}
	chmod 660 ${IPTABLES_LOCK_FILE}
	mkdir -m 775 ${RUN_PATH}/cujo
	chown root:${CUJO_USER} ${RUN_PATH}/cujo
}
