#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=75
STOP=36
USE_PROCD=1

start_service() {
        mkdir -m 0755 -p /var/cache/cups
        mkdir -m 0755 -p /var/cups
        mkdir -m 0755 -p /var/spool/cups/tmp
        chmod 700 /usr/lib/cups/backend/usb

        local enabled
        config_load printersharing
        config_get_bool enabled config enabled 0
        if [ $enabled -eq 1 ]; then
                procd_open_instance
                procd_set_param command /usr/sbin/cupsd -f
                procd_set_param respawn
                procd_close_instance
        fi
}

stop_service() {
        # Before stopping cupsd, clear up the printer related jobs
        rm -rf /var/spool/cups/*
}

service_triggers() {
	procd_add_reload_trigger "printersharing"
}

