#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

start() {
	mkdir -m 0755 -p /var/cache/cups
	mkdir -m 0755 -p /var/cups
	mkdir -m 0755 -p /var/spool/cups/tmp
	chmod 700 /usr/lib/cups/backend/usb

	local enabled
	config_load printersharing
	config_get_bool enabled config enabled 0
	if [ $enabled -eq 1 ]; then
	    service_start /usr/sbin/cupsd
	    cupsctl WebInterface=no
	else
	    service_stop /usr/sbin/cupsd
	fi
}

stop() {
	service_stop /usr/sbin/cupsd
}

reload() {
	local enabled
	config_load printersharing
	config_get_bool enabled config enabled 0
	if [ $enabled -eq 1 ]; then
	    service_reload /usr/sbin/cupsd
	    cupsctl WebInterface=no
	else
	    service_stop /usr/sbin/cupsd
	fi
}
