#!/bin/sh /etc/rc.common

START=70
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
unset SERVICE_MATCH_EXEC
SERVICE_SIG_RELOAD="URG"

boot() {
	/etc/init.d/cwmpdboot boot &
}

start() {
	logger -t cwmpd "Starting cwmpd"
	fw3 -q reload
	service_start /usr/bin/cwmpd
	service_start /usr/bin/cwmpevents
}

stop() {
	logger -t cwmpd "Stopping cwmpd"
	service_stop /usr/bin/cwmpd
	service_stop /usr/bin/cwmpevents
}

reload() {
	logger -t cwmpd "Reloading cwmpd"
	fw3 -q reload
	service_reload /usr/bin/cwmpd
}
