#!/bin/sh /etc/rc.common

START=55
USE_PROCD=1

start_service() {
	if [ "$(uci_get datausage global enabled 1)" = "1" ]; then
		procd_open_instance "datausaged"
		procd_set_param command "/usr/bin/datausaged"
		procd_set_param respawn
		procd_set_param stderr 1
		procd_close_instance
	else
		logger -t "$APP" "Data usage monitor disabled"
	fi
}

datausaged_running() {
	json_init
	json_add_string name "datausaged"
	local data="$(ubus call service list "$(json_dump)")"
	json_load "$data"
	# Silence warnings from here on
	local _json_no_warning=1
	local result=1
	json_select "datausaged" && \
	json_select "instances" && \
	json_select "datausaged" && \
	json_get_var running running && \
	[ "$running" = "1" ] && \
		result=0
	json_cleanup
	return $result
}

reload_service() {
	if [ "$(uci_get datausage global enabled 1)" = "1" ]; then
		if datausaged_running; then
			ubus -t 2 call datausage reload
		else
			start
		fi
	elif datausaged_running; then
		stop
	fi
}

service_triggers() {
	[ "$(uci_get datausage global enabled 1)" = "1" ] && procd_add_reload_trigger "datausage"
}
