#!/bin/sh /etc/rc.common

START=55

USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/datausaged
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "datausaged"
}

reload_service() {
	kill -s HUP $(pgrep -f /usr/bin/datausaged)
}
