#!/bin/sh /etc/rc.common

START=50
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	logger -t dhcpopassthrud "Starting DHCP option transfer daemon"

	include /lib/dhcpopassthrud/init

	service_start /usr/bin/dhcpopassthrud
}

reload() {
	pid=$(cat /var/run/dhcpopassthrud.pid)
	[ -n "$pid" ] && {
		logger -t dhcpopassthrud "Reloading DHCP option transfer daemon"
		kill -HUP $pid
	}
}

stop() {
	logger -t dhcpopassthrud "Stopping DHCP option transfer daemon"

	service_stop /usr/bin/dhcpopassthrud
}
