#!/bin/sh /etc/rc.common

START=50
USE_PROCD=1

start_service() {
	logger -t dhcpopassthrud "Starting DHCP option transfer daemon"

	include /lib/dhcpopassthrud/init

	procd_open_instance
	procd_set_param command /usr/bin/dhcpopassthrud
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	killall -HUP dhcpopassthrud
}

service_triggers() {
	procd_add_reload_trigger "dhcp"
}
