#!/bin/sh /etc/rc.common
#set -x

START=90

BCM_VLAN_TOOL=/usr/bin/vlanctl
BCM_VLAN_CMD=--cfg-dscp2pbits
BCM_IF_SELECT=--if

parse_dscp_to_pbit(){
   local rule=$1
   local dscpvalue
   local pbitvalue
   local ip_interface
   local level3_ip_interface
   local vlanmode=$2
   local interface
   config_get dscpvalue "$rule" dscpvalue
   config_get pbitvalue "$rule" pbitvalue
   config_get interface "$rule" interface
   config_get vid "$rule" vid
   config_get ip_interface "$rule" ip_interface
   if [ -z dscpvalue ]; then
     echo "the dscpvalue is not set for dscp2pbit config"
     return
   fi
   if [ -z pbitvalue ]; then
      echo "the pbitvalue is not set for dscp2pbit config"
   fi
   if [ -z interface ]; then
      echo " the interface is not set for dscp2pbit config"
   fi
   if [ "$vlanmode" = "linux" ]; then
      if [ -z ip_interface ]; then
        echo " the interface is not set for dscp2pbit config"
      fi
   fi

   if [ "$vlanmode" = "bcmvopi" ]; then
     $BCM_VLAN_TOOL $BCM_IF_SELECT "$interface" $BCM_VLAN_CMD "$dscpvalue" "$pbitvalue"
   else
     network_get_device level3_ip_interface "$ip_interface"
     iptables -t mangle -A dscp2pbit -o "$level3_ip_interface" -m dscp --dscp "$dscpvalue" -j CLASSIFY --set-class 0:"$dscpvalue"
     vconfig set_egress_map "$interface"  "$dscpvalue" "$pbitvalue"
   fi     
}

start(){
   include /lib/network
   . /lib/functions/network.sh

   local vlanmode
   config_load network
   config_get vlanmode globals vlanmode "linux"
   if [ "$vlanmode" = "linux" ]; then
       iptables -t mangle -D FORWARD -j dscp2pbit
       iptables -t mangle -D OUTPUT -j dscp2pbit
       iptables -t mangle -N dscp2pbit
       iptables -t mangle -A FORWARD -j dscp2pbit
       iptables -t mangle -A OUTPUT -j dscp2pbit
   fi
   config_load dscp2pbit
   config_foreach parse_dscp_to_pbit rule "$vlanmode"

}

stop(){  
  local vlanmode
  config_load network
  config_get vlanmode globals vlanmode "linux"
  if [ "$vlanmode" = "linux" ]; then
     iptables -t mangle -F dscp2pbit 
     iptables -t mangle -D FORWARD -j dscp2pbit
     iptables -t mangle -D OUTPUT -j dscp2pbit
     iptables -t mangle -X dscp2pbit
  fi
}
  
