#!/bin/sh /etc/rc.common
# (C) NETDUMA Software 2020

START=99

can_use() {
	command -v "$1" 1>/dev/null 2>&1 || type "$1" 1>/dev/null 2>&1 || hash "$1" 1>/dev/null 2>&1
	return "$?"
}

start() {
	if can_use "ifconfig"
	then
		ifconfig br0 txqueuelen 1000
	elif can_use "ip"
	then
		ip link set br0 txqueuelen 1000
	fi

	if can_use "chrt"
	then
		chrt -r -p "5" "$(pgrep "bcmxtm_rx")"
		chrt -r -p "5" "$(pgrep "bcmsw_rx")"
	fi
}
