#!/bin/sh /etc/rc.common

START=99

tset() {
  local PARAM="$1"
  local VALUE="$2"

  lua - "$PARAM" "$VALUE" <<EOF
     local dm = require 'datamodel'
     dm.set(arg[1], arg[2])
     dm.apply()
EOF
}

start()
{
  local refurbished_enable=`uci get -q enhancedwifi.global.refurbished_enable`
  if [ "$refurbished_enable" == "1" ]; then
     tset "Device.Services.X_BELGACOM_EnhancedWiFi.Enable" "1"
     uci del enhancedwifi.global.refurbished_enable
     uci commit enhancedwifi
  fi
}

stop()
{
  echo "This is not a real service."
}
