#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	logger -t firmware-upgrade-ext "Starting firmware-upgrade-ext"
	procd_open_instance
	procd_set_param command /usr/sbin/firmware-upgrade-ext.sh
	procd_close_instance
}
