#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1
GENERIC_PNPD_PID_FILE=/var/run/generic_pnpd.pid

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/generic_pnpd
  procd_set_param pidfile "${GENERIC_PNPD_PID_FILE}"
  procd_close_instance
}

stop_service() {
  if [ -r ${GENERIC_PNPD_PID_FILE} ]; then
    kill -KILL $(cat ${GENERIC_PNPD_PID_FILE})
    rm -f ${GENERIC_PNPD_PID_FILE}
  fi
}

