#!/bin/sh /etc/rc.common

. $IPKG_INSTROOT/lib/network/gpon.sh

restart() {
	if ifconfig veip0 | grep UP | grep RUNNING >/dev/null 2>&1; then
		gpon_unload_layer3_interfaces
		gpon_load_layer3_interfaces
	fi
}
