#!/bin/sh /etc/rc.common

START=83

. $IPKG_INSTROOT/lib/network/gpon.sh


start() {
	if [ -x /bin/pspctl ] && [ "$(pspctl dump RdpaWanType | grep 'GBE')" != "" ] ; then
		gpon_load_layer3_ethwan_interface
		/usr/bin/gpon_tm_reload
	fi
}

stop() {
	if [ -x /bin/pspctl ] && [ "$(pspctl dump RdpaWanType | grep 'GBE')" != "" ] ; then
		gpon_unload_layer3_interfaces
	fi
}


