#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1

start_service() {
    gre-hotspotd-reload update
    store_hash
    procd_open_instance
    procd_set_param command /usr/bin/gre-hotspotd.lua
    procd_set_param respawn # 3600,5,5
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    gre-hotspotd-reload update
    ubus call gre-hotspotd reload >/dev/null
}

service_triggers() {
    procd_add_reload_trigger "gre_hotspotd" "network" "wireless"
}
