#!/bin/sh /etc/rc.common

START=50
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
unset SERVICE_MATCH_EXEC

start() {
	service_start /usr/bin/hostmanager.lua
}

stop() {
	service_stop /usr/bin/hostmanager.lua && echo >/var/run/hostmanager.lua.pid
}
