#!/bin/sh /etc/rc.common

START=50
APP=hostmanager.lua
PID_FILE=/var/run/$APP.pid

start() {
        start-stop-daemon -S -x $APP -p $PID_FILE -m -b
}

stop() {
        start-stop-daemon -K -p $PID_FILE -s INT
        rm -rf $PID_FILE
}
