#!/bin/sh /etc/rc.common

START=18
USE_PROCD=1

service_triggers() {
	procd_add_reload_trigger "hostmanager"
}

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/hostmanager.lua
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	ubus call hostmanager reload >/dev/null
}

