#!/bin/sh /etc/rc.common

START=70
SERVICE_DAEMONIZE=1

boot() {
	logger -t igmpproxy "Starting igmpproxy"

	service_start /usr/bin/igmpproxy -p 0
}

start() {
	logger -t igmpproxy "Starting igmpproxy"

	fw3 -q reload
	service_start /usr/bin/igmpproxy -p 0
}

stop() {
	logger -t igmpproxy "Stopping igmpproxy"

	service_stop /usr/bin/igmpproxy
}
