#! /bin/sh /etc/rc.common

START=99

start() {
	logger -t ipks "Installing prebuilt ipks:"

	IPKS=$(find /usr/share/homeware-ipks/ -type f -name '*.ipk')
	for i in $IPKS; do logger -t ipks "Found $i" ; done

	if [ -n "$IPKS" ]
	then
		/bin/opkg install $IPKS && rm $IPKS
	fi

	logger -t ipks "Done installing prebuild ipks"
}
