#!/bin/sh /etc/rc.common

START=50
USE_PROCD=1
PLUGINDIR="/usr/lib/intercept/plugins"

start_service() {
	if [ "$(uci_get intercept config enabled 1)" = "1" ]; then
		procd_open_instance "intercept"
		procd_set_param command "/usr/bin/interceptd"
		procd_set_param respawn
		procd_set_param stderr 1
		procd_close_instance
	else
		logger -t "$APP" "Intercept disabled"
	fi
}

intercept_running() {
	json_init
	json_add_string name "intercept"
	local data="$(ubus call service list "$(json_dump)")"
	json_load "$data"
	# Silence warnings from here on
	local _json_no_warning=1
	local result=1
	json_select "intercept" && \
	json_select "instances" && \
	json_select "intercept" && \
	json_get_var running running && \
	[ "$running" = "1" ] && \
		result=0
	json_cleanup
	return $result
}

reload_service() {
	if [ "$(uci_get intercept config enabled 1)" = "1" ]; then
		if intercept_running; then
			ubus call intercept reload
		else
			start
		fi
	elif intercept_running; then
		stop
	fi
}

service_triggers() {
	[ "$(uci_get intercept config enabled 1)" = "1" ] && {
		procd_open_trigger
		procd_add_raw_trigger "interface.*" 1500 "$PLUGINDIR/wan.sh" ifchanged
		procd_add_raw_trigger "intercept.setup" 1500 "$PLUGINDIR/wan.sh" setup
		if [ "$(uci_get intercept config mobiledenabled)" = "1" ]; then
			procd_add_raw_trigger "interface.*" 1500 "$PLUGINDIR/mobile.sh" ifchanged
			procd_add_raw_trigger "intercept.setup" 1500 "$PLUGINDIR/mobile.sh" setup
		fi
		procd_close_trigger
		procd_add_reload_trigger "intercept"
	}
}
