#!/bin/sh /etc/rc.common

START=50
USE_PROCD=1

. $IPKG_INSTROOT/usr/lib/intercept/functions.sh

start_service() {
   logger -t intercept "start_service"
}

service_started() {
   $INTERCEPT_SETUP boot
   logger -t intercept "service_started"
}

reload_service() {
    logger -t intercept "init RELOAD"
    # by opening and closing the service, procd (scripts) call service_triggers again
    procd_open_service intercept
    procd_close_service
    $INTERCEPT_SETUP reload

}

service_triggers() {
    local enabled
    config_load "intercept"
    procd_open_trigger
    procd_add_reload_trigger "intercept"
    config_get_bool enabled config enabled 0
    [ "$enabled" != "0" ] && {
	procd_add_raw_trigger "interface.*" 1500 $INTERCEPT_SETUP ifchanged
    }
    procd_close_trigger
}
