#!/bin/sh /etc/rc.common

START=70
STOP=10
USE_PROCD=1

. $IPKG_INSTROOT/lib/functions.sh

start_service() {
    local enabled=$(uci_get iperf iperf enabled 0)
    local protocol=$(uci_get iperf iperf proto TCP)
    local port=$(uci_get iperf iperf dest_port 5001)

    if [ "$protocol" = "UDP" ]; then
	proto="-u"
    else
	proto=""
    fi

    if [ "$enabled" = "1" ]; then
	uci_toggle_state "iperf" "iperf" "status" "Enabled"
	procd_open_instance
	procd_set_param command /usr/bin/iperf -s $proto -p $port
	procd_set_param respawn 60, 60, 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
    else
	uci_toggle_state "iperf" "iperf" "status" "Disabled"
    fi
}

stop_service() {
    local enabled=$(uci_get iperf iperf enabled 0)

    if [ "$enabled" == "1" ]; then
	kill -9 `ps | grep '[i]perf -s' | awk '{print $1}'`
    fi
}
