#!/bin/sh /etc/rc.common

START=70
STOP=10
USE_PROCD=1

. $IPKG_INSTROOT/lib/functions.sh

enabled=$(uci_get iperf iperf enable 0)
protocol=$(uci_get iperf iperf proto TCP)
port=$(uci_get iperf iperf dest_port 5001)

start_service() {
  if [ "$protocol" == "UDP" ]; then
    proto="-u"
  else
    proto=""
  fi
  if [ "$enabled" == "1" ]; then
    uci_toggle_state "iperf" "iperf" "status" "Enabled"
    procd_open_instance
    procd_set_param command /usr/bin/iperf -s $proto -p $port
    procd_set_param respawn 60, 60, 0
    procd_close_instance
  else
    uci_toggle_state "iperf" "iperf" "status" "Disabled"
  fi
}

stop_service() {
  if [ "$enabled" == "1" ]; then
    kill -9 `ps | grep '[i]perf -s' | awk '{print $1}'`
  fi
}
