#!/bin/sh /etc/rc.common

START=18
USE_PROCD=1

start_service() {
	ipset-helper start
}

stop_service() {
	ipset-helper stop
}

reload_service()
{
	ipset-helper reload
}

service_triggers() {
	procd_add_reload_trigger "ipset"
}

