#!/bin/sh /etc/rc.common
START=50
STOP=10

SERVICE_SIG_RELOAD="USR1"
SERVICE_SIG_RELOAD_EE_PACKAGES="USR2"

USE_PROCD=1

EXTRA_COMMANDS="reload_ee_packages"
EXTRA_HELP="	reload_ee_packages Iterate over all EE's and add any new packages to the LCM database"

start_service() {
  local enabled
  config_load "lcmd"
  config_get enabled daemon_config enable 0
  [ "$enabled" -eq 0 ] && return 1
  procd_open_instance "lcmd"
  procd_set_param command /usr/bin/lcmd
  procd_close_instance
}

reload_service() {
  procd_send_signal lcmd lcmd $(kill -l "${SERVICE_SIG_RELOAD}")
  if [ $? -ne 0 ]; then
    echo "Reload of lcmd failed. LCMd not yet running?"
  fi
  # make sure the last statement of the reload function is always true
  # otherwise init.d will restart LCMd on failure of the reload function
  # and that can lead to an unwanted racecondition during boot time
  true
}

reload_ee_packages() {
  procd_send_signal lcmd lcmd $(kill -l "${SERVICE_SIG_RELOAD_EE_PACKAGES}")
}
