#!/bin/sh /etc/rc.common
START=50
STOP=10

USE_PROCD=1

start_service() {
  local enabled
  config_load "lcmd"
  config_get enabled daemon_config enable 0
  [ "$enabled" -eq 0 ] && return 1
  procd_open_instance
  procd_set_param command /usr/bin/lcmd
  procd_close_instance
}
