#!/bin/sh /etc/rc.common

START=12
APP=ledfw.lua
PID_FILE=/var/run/$APP.pid

start() {
        insmod technicolor_led 2>/dev/null
        start-stop-daemon -S -x $APP -p $PID_FILE -m -b
}

stop() {
        start-stop-daemon -K -n $APP -p $PID_FILE -s TERM
        rm -rf $PID_FILE
}
