#!/bin/sh /etc/rc.common
. $IPKG_INSTROOT/lib/functions/network.sh

START=90
USE_PROCD=1

lot_control() {
      [ -e "$IPKG_INSTROOT/usr/lib/lot/control.sh" ] && $IPKG_INSTROOT/usr/lib/lot/control.sh $*
}

boot() {
     lot_control boot
     start "$@"
}

PID_FILE=/var/run/lot.pid

start_service() {
     lot_control start
     config_load lot
     config_get enable state deploy
     if [ "$enable" == "true" ]; then
         procd_open_instance
         procd_set_param command /usr/bin/LoTAgent.lua
         procd_set_param respawn  # defaults 3600,5,5
         procd_set_param pidfile "${PID_FILE}"
         procd_set_param stdout 1
         procd_set_param stderr 1
         procd_close_instance
     fi
 }

stop_service() {
     lot_control stop
}
reload_service() {
    lot_control reload
    restart
}

