#!/bin/sh /etc/rc.common

START=60
USE_PROCD=1

start_service() {
	if [ "$(uci_get ltedoctor config enabled 1)" = "1" ]; then
		procd_open_instance "ltedoctor"
		procd_set_param command "/usr/bin/lte-doctor-logger"
		procd_set_param respawn
		procd_set_param stderr 1
		procd_close_instance
	else
		logger -t "$APP" "LTE Doctor disabled"
	fi
}

lte_doctor_running() {
	json_init
	json_add_string name "lte-doctor-logger"
	local data="$(ubus call service list "$(json_dump)")"
	json_load "$data"
	# Silence warnings from here on
	local _json_no_warning=1
	local result=1
	json_select "lte-doctor-logger" && \
	json_select "instances" && \
	json_select "ltedoctor" && \
	json_get_var running running && \
	[ "$running" = "1" ] && \
		result=0
	json_cleanup
	return $result
}

reload_service() {
	if [ "$(uci_get ltedoctor config enabled 1)" = "1" ]; then
		if lte_doctor_running; then
			ubus call ltedoctor reload
		else
			start
		fi
	elif lte_doctor_running; then
		stop
	fi
}
