#!/bin/sh /etc/rc.common

#
#VBNT-J(DJN2130) LTE control GPIO description:
#GPIO_72	LTE_ANT_CTRL1
#GPIO_73	PERSTa
#GPIO_100	LTE_PWR_ON_OFF
#GPIO_101	W_WDISABLE
#GPIO_102	POWER_ON_OFF_OPTION2
#GPIO_134	USB Interface enable
#
START=11

. $IPKG_INSTROOT/lib/functions.sh

boot() {
#1. create gpio node on sysfs
	echo "72" > /sys/class/gpio/export
	echo "73" > /sys/class/gpio/export
	echo "100" > /sys/class/gpio/export
	echo "101" > /sys/class/gpio/export
	echo "102" > /sys/class/gpio/export
	echo "134" > /sys/class/gpio/export
#2.setup direction
	echo "out" > /sys/class/gpio/gpio72/direction
	echo "out" > /sys/class/gpio/gpio73/direction
	echo "out" > /sys/class/gpio/gpio100/direction
	echo "out" > /sys/class/gpio/gpio101/direction
	echo "out" > /sys/class/gpio/gpio102/direction
	echo "out" > /sys/class/gpio/gpio134/direction
#3.setup value
	echo "0" > /sys/class/gpio/gpio72/value
	echo "0" > /sys/class/gpio/gpio73/value
	echo "0" > /sys/class/gpio/gpio100/value
	echo "1" > /sys/class/gpio/gpio101/value
	echo "0" > /sys/class/gpio/gpio102/value
	echo "1" > /sys/class/gpio/gpio134/value
}

