#!/bin/sh /etc/rc.common

START=99
STOP=00

USE_PROCD=1

lxc_path="/srv/lxc"

lxc_instance_start() {
  local lxc="${1}"
  local enabled

  config_get enabled "${lxc}" enabled "0"
  [ "${enabled}" = "0" ] && return 0

  local config_file="${lxc_path}/${lxc}/config"
  procd_open_instance "${lxc}"
  procd_set_param command lxc-start -F -n "${lxc}"
  procd_set_param file "${config_file}"
  procd_close_instance
}

start_service() {
  local global_enabled

  config_load lxc
  config_get global_enabled global enabled "0"
  [ "${global_enabled}" = "0" ] && return 0

  /usr/sbin/update_lxc_config
  config_foreach lxc_instance_start lxc_instance
}

service_triggers()
{
  procd_add_reload_trigger lxc
}
