#!/bin/sh /etc/rc.common

START=60
STOP=44
USE_PROCD=1

parse_interface() {
	[ "$found" -gt 0 ] && return

	config_get state "$1" state "downstream"
	[ "$state" = "downstream" ] && found=1
}

start_service() {
	logger -t mcsnooper "Starting multicast snooper daemon"

	config_load mcastsnooping
	found=0
	config_foreach parse_interface interface

	procd_open_instance
	procd_set_param command /usr/bin/mcsnooper
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "mcastsnooping"
}
