#!/bin/sh /etc/rc.common

START=60
SERVICE_DAEMONIZE=1

args=""

get_multicast_prio_queue() {
	local iface=$1
	local class="Video_$iface"

	config_load qos

	local classgroup enabled
	config_get classgroup $iface classgroup
	[ -z "$classgroup" ] && return 1
	config_get_bool enabled $iface enabled 1
	[ 1 -eq "$enabled" ] || return 1

	local classes
	config_get classes $classgroup classes
	list_contains classes $class || return 1

	local priority
	config_get priority $class priority
	[ -n "$priority" ] && append args "-P $priority"
}

parse_interface() {
	[ "$found" -gt 0 ] && return

	local state
	config_get state "$1" state "downstream"
	[ "$state" == "downstream" ] && get_multicast_prio_queue "$1" && found=1
}

start() {
	logger -t mcsnooper "Starting multicast snooper daemon"

	config_load mcastsnooping
	found=0
	config_foreach parse_interface interface

	service_start /usr/bin/mcsnooper $args
}

stop() {
	logger -t mcsnooper "Stopping multicast snooper daemon"

	service_stop /usr/bin/mcsnooper
}
