#!/bin/sh /etc/rc.common

START=70
SERVICE_DAEMONIZE=1

boot() {
	logger -t mldproxy "Starting mldproxy"

	service_start /usr/bin/mldproxy
}

start() {
	logger -t mldproxy "Starting mldproxy"

	fw3 -q reload
	service_start /usr/bin/mldproxy
}

stop() {
	logger -t mldproxy "Stopping mldproxy"

	service_stop /usr/bin/mldproxy
}
