#!/bin/sh /etc/rc.common

start() {
local path="/etc/lasdb.db"
local tracelevel="4"
args="-p $path -t $tracelevel"
        service_start /usr/bin/mmdbd $args
}

stop() {
        service_stop /usr/bin/mmdbd
}
