#!/bin/sh /etc/rc.common

#Start before mmpbx (interfaces need to be created)
START=98

do_only_once(){
  BRCM_DECT_EVENT_MAJOR=3051
  mknod /dev/dect c $BRCM_DECT_EVENT_MAJOR 0
}

start() {
  if [ -e /dev/dect ] ; then
    exit 0
  fi

  do_only_once
}
