#!/bin/sh /etc/rc.common

source $IPKG_INSTROOT/lib/functions/functions-tch.sh

START=98
STOP=96
APP=mmpbxfwctl
PIDFILE=/var/run/mmpbxfwctl.pid

start() {
    start-stop-daemon -S -x $APP -p $PIDFILE -m -b

    # Set Real time priority
    config_load "mmpbx"
    config_get mmpbxMediaPriority global rt_priority 76
    setrtprio $APP $mmpbxMediaPriority
}

stop() {
    start-stop-daemon -K -p $PIDFILE
}
