#!/bin/sh /etc/rc.common

START=65

USE_PROCD=1
LOGTAG="mobiled"

. "$IPKG_INSTROOT/lib/functions.sh"

start_service() {
   config_load mobiled
   local SERVICE_ENABLED
   config_get SERVICE_ENABLED globals enabled 1
	if [ "$SERVICE_ENABLED" = "1" ]; then
      procd_open_instance "mobiled"
      procd_set_param command /usr/bin/mobiled
      procd_set_param respawn
      procd_set_param stderr 1
      procd_close_instance
	else
      logger -t "$LOGTAG" "Mobiled disabled"
	fi
}

service_triggers() {
	procd_add_reload_trigger "mobiled"
}

reload_service() {
   config_load mobiled
   local SERVICE_ENABLED
   config_get SERVICE_ENABLED globals enabled 1
   if [ "$SERVICE_ENABLED" = "1" ]; then
      # Keep trying to reload mobiled as long as it fails to reload (with a maximum of
      # 10) as reloading might fail when mobiled is blocked on an AT command.
      for try in $(seq 10); do
          if ubus call mobiled reload; then
             break
          fi
      done
	fi
}
