#!/bin/sh /etc/rc.common

START=99
STOP=02
USE_PROCD=1

MQTTJSON_BIN=/usr/sbin/mqttjson_services.lua
MQTTJSON_PID_FILE=/var/run/mqttjson.pid

start_service() {
    local mqttjson_enabled
    config_load mqttjson_services
    config_get mqttjson_enabled config enabled 0

    if [ $mqttjson_enabled == "1" ]; then
        logger -t MQTTJSON "Starting mqttjson_services"
        #Added a extra check for the existence of the mqttjson services process to prevent recursive case
        if ! pgrep -x "mqttjson" > /dev/null; then
        procd_open_instance
        procd_set_param command $MQTTJSON_BIN
        procd_set_param pidfile $MQTTJSON_PID_FILE
        procd_close_instance
        fi
    else
        return 1;
    fi
}

reload_service() {
    local mqttjson_enabled
    config_load mqttjson_services
    config_get_bool mqttjson_enabled config enabled 0

    if [ $mqttjson_enabled == "1" ]; then
        logger -t MQTTJSON "Reload: restarting mqttjson_services"
        restart
    else
        stop
    fi
}

stop_service() {
    logger -t MQTTJSON "Stopping mqttjson_services"
    service_stop $MQTTJSON_BIN
}
