#!/bin/sh /etc/rc.common

START=99
STOP=02
USE_PROCD=1

MQTTJSON_BIN=/usr/bin/mqttjson_services
MQTTJSON_PID_FILE=/var/run/mqttjson.pid
MQTT_PATH=/usr/lib/lua/mqttjson_services

start_service() {
    local mqttjson_enabled
    config_load mqttjson_services
    config_get mqttjson_enabled config enabled 0

    cd $MQTT_PATH
    ls *.lua > /tmp/luafiles.txt
    while read line; do lua $line; done < /tmp/luafiles.txt
    for d in $MQTT_PATH/*; do
      if [ -d "$d" ]; then
        cd "$d"
        ls *.lua > /tmp/luafiles.txt
      fi
    done
    while read line; do lua $line; done < /tmp/luafiles.txt
    rm /tmp/luafiles.txt

    if [ "$mqttjson_enabled" == "1" ]; then
        logger -t MQTTJSON "Starting mqttjson_services"
        #Added a extra check for the existence of the mqttjson services process to prevent recursive case
        if ! pgrep -x "mqttjson" > /dev/null; then
        procd_open_instance
        procd_set_param command $MQTTJSON_BIN
        procd_set_param pidfile $MQTTJSON_PID_FILE
        procd_set_param respawn
        procd_close_instance
        fi
    else
        return 1
    fi
}

reload_service() {
    local mqttjson_enabled
    config_load mqttjson_services
    config_get_bool mqttjson_enabled config enabled 0

    if [ "$mqttjson_enabled" == "1" ]; then
        logger -t MQTTJSON "Reload: restarting mqttjson_services"
        restart
    else
        stop
    fi
}

stop_service() {
    logger -t MQTTJSON "Stopping mqttjson_services"
    service_stop $MQTTJSON_BIN
}
