#!/bin/sh /etc/rc.common

#Start After the Hostapd so that Other Agents can start communication
PROCD_DEBUG=1
USE_PROCD=1
START=99

PID_FILE=/var/run/multiap_agent.pid
RUNNING_FILE=/var/run/mapd_running

start_service() {
  config_load multiap
  config_get_bool map_agent_enabled multiap_agent enabled
  [ $map_agent_enabled -eq 0 ] && return 0
  procd_open_instance

  config_get_bool map_ctrl_enabled multiap_controller enabled

  macaddress=`uci get env.rip.wifi_mac`
  uci set multiap.al_entity.al_mac=$macaddress

  local interfaces=`uci get multiap.al_entity.interfaces`

  [ $map_agent_enabled -eq 1 ] && [ $map_ctrl_enabled -eq 1 ]
  ## Add "lo" interface if both ctrller, agent is enabled
  if [ "$?" -eq "0" ]; then
      eval "echo \$interfaces | grep \"lo\" | grep -v \"grep\""
      if [ "$?" -eq "1" ]; then
          interfaces=`printf "lo,$interfaces"`
      fi
  else
      ##Remove "lo" interface if only one map soln is present
      interfaces=`echo $interfaces | sed 's/lo,//g'`
  fi

  uci set multiap.al_entity.interfaces=$interfaces

  uci set multiap.multiap_agent.macaddress=$macaddress
  uci commit

  procd_set_param command /usr/bin/multiap_agent -m ubus
  procd_set_param limits core="unlimited"  # If you need to set ulimit for your process
  procd_set_param pidfile /var/run/multiap_agent.pid # write a pid file on instance start and remote it on stop
  procd_close_instance

}

