#!/bin/sh /etc/rc.common

USE_PROCD=1

MAP_VE_PID_FILE=/var/run/multiap_vendorextensions.pid

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/multiap_vendorextensions
  procd_set_param pidfile "${MAP_VE_PID_FILE}"
  procd_close_instance
}
