#!/bin/sh /etc/rc.common

START=96
STOP=04

EXTRA_COMMANDS="add_volume del_volume"
EXTRA_HELP=<<EOF
                add_volume is used to add the volume(volume name, mount point) details to the mvfs config file
                del_volume is used to remove the given volume(name) details from mvfs config file
EOF

MVFS_PID_FILE=/var/run/mvfs.pid
MVFS_BIN=/usr/bin/mvfs
MVFS_USER="mvfs"
MVFS_UID=499
MVFS_GROUP="daemon"
MVFS_FS="/usr/bin/mvfs"
MVFS_MOUNT_DIR="/var/mvfs"
MVFS_CONFIG_DIR="/tmp/.mvfs"
MVFS_CONFIG="${MVFS_CONFIG_DIR}/mvfs.ini"
MVFS_TAGDB=".mvfs/tagdb"

_log(){
    logger -t mvfsd "$1"
}

start()
{
  if [ -f $MVFS_PID_FILE ]; then
    return 1
  fi

  if [ -x $MVFS_BIN ]; then
    _log "start mvfsd."
    mvfs_mkdirs
    mvfs_adduser
    chmod 777 "$(dirname ${MVFS_MOUNT_DIR})"
    test -d "${MVFS_MOUNT_DIR}" && rmdir "${MVFS_MOUNT_DIR}"
    mkdir -p "${MVFS_MOUNT_DIR}" "${MVFS_USER}"

    local loglevel
    config_load dlnad
    config_get loglevel log mvfs_logLevel

    if [ -z $loglevel ]; then
      ${MVFS_FS} ${MVFS_MNTOPT} -o config=${MVFS_CONFIG} "${MVFS_MOUNT_DIR}"
    else
      ${MVFS_FS} ${MVFS_MNTOPT} -o config=${MVFS_CONFIG} "${MVFS_MOUNT_DIR}" -o l=$loglevel
    fi

    pid_mvfs=$(ps |grep $MVFS_BIN | grep -v grep | awk '{print $1}')
    echo $pid_mvfs > $MVFS_PID_FILE
  else
    _log "mvfsd not present."
  fi
}

stop()
{
  umount "${MVFS_MOUNT_DIR}" 2>/dev/null
  service_stop $MVFS_FS
  if [ -f $MVFS_CONFIG ]; then
    rm -f $MVFS_CONFIG
  fi

  if [ -f $MVFS_PID_FILE ]; then
    rm -f $MVFS_PID_FILE
  fi
  _log "mvfsd stopped."
}

reload()
{
  service_reload $MVFS_FS
}

mvfs_mkdirs()
{
  mkdir -p "${MVFS_CONFIG_DIR}"
  chmod -R 777 "${MVFS_CONFIG_DIR}"
  touch "${MVFS_CONFIG}"
  chmod 666 "${MVFS_CONFIG}"
}

mvfs_adduser()
{
  MVFS_GID=$(cat /etc/group | grep ${MVFS_GROUP} | cut -d : -f 3)
  if [ -z "$MVFS_GID" ]
  then
    addgroup "$MVFS_GROUP"
    MVFS_GID=$(cat /etc/group | grep ${MVFS_GROUP} | cut -d : -f 3)
    if [ -z "$MVFS_GID" ]
    then
      MVFS_GID=0
    fi
  fi
  if [ "$(id -un ${MVFS_USER} 2>/dev/null)" != "${MVFS_USER}" ]
  then
    echo "${MVFS_USER}:*:${MVFS_UID}:${MVFS_GID}::/:/bin/sh" >> /etc/passwd
  fi
}

add_volume()
{
  alias="$1"
  mountdir="$2"

  if [ ! -z "$alias" -a ! -z "$mountdir" ]
  then
    mvfs_mkdirs
    if [ ! $(grep -s "^${alias}:" "$MVFS_CONFIG") ]
    then
      p=$(realpath ${mountdir})
      if [ ! -z "$3" ]
      then
        db=$(realpath "$3")
      else
        db="${p}/${MVFS_TAGDB}"
      fi
      echo "${alias}:${p}:${db}" >> "$MVFS_CONFIG"
    fi
  fi
}

del_volume()
{
  alias="$1"

  if [ ! -z "$alias" -a -f "$MVFS_CONFIG" ]
  then
    if [ $(grep "^${alias}:" "$MVFS_CONFIG") ]
    then
      sed -i "/^${alias}:/d" "$MVFS_CONFIG"
    fi
  fi
}

