#!/bin/sh /etc/rc.common

START=96
STOP=04
USE_PROCD=1

DLNA_PID_FILE=/var/run/dlnad.pid
MVFS_PID_FILE=/var/run/mvfs.pid
MVFS_BIN=/usr/bin/mvfs
MVFS_GROUP="daemon"
MVFS_FS="/usr/bin/mvfs"
MVFS_MOUNT_DIR="/var/mvfs"
MVFS_CONFIG_DIR="/tmp/.mvfs"
MVFS_CONFIG="${MVFS_CONFIG_DIR}/mvfs.ini"
MVFS_TAGDB=".mvfs/tagdb"

_log(){
    logger -t mvfsd "$1"
}

start_service()
{
  if [ -f $MVFS_PID_FILE ]; then
    return 1
  fi
  local dlnad_enabled
  local dynamic_enabled
  local usb_detect
  config_load dlnad
  config_get dynamic_enabled config dynamic
  config_get dlnad_enabled config enabled
  [ -z "$dynamic_enabled" ] && dynamic_enabled="0"
  [ -z "$(ls -A /mnt/usb/)" ] && usb_detect="0" || usb_detect="1"
  if [[ "$dlnad_enabled" = "1" && "$dynamic_enabled" = "0" ]] ||  [[ "$dlnad_enabled" = "1"  && "$dynamic_enabled" = "1" && "$usb_detect" = "1" ]]; then
    if [ -x $MVFS_BIN ]; then
      _log "start mvfsd."
      mvfs_mkdirs
      test -d "${MVFS_MOUNT_DIR}" && rmdir "${MVFS_MOUNT_DIR}"
      mkdir -p "${MVFS_MOUNT_DIR}"

      local loglevel
      config_load dlnad
      config_get loglevel log mvfs_logLevel

      local args=" -o config=${MVFS_CONFIG} "${MVFS_MOUNT_DIR}""
      [ ! -z $loglevel ] && args=$args" -o l=$loglevel"

      procd_open_instance
      procd_set_param command $MVFS_FS ${MVFS_MNTOPT} $args
      procd_set_param pidfile ${MVFS_PID_FILE}
      procd_close_instance
    else
      _log "mvfsd not present."
    fi
  fi
}

stop_service()
{
    umount "${MVFS_MOUNT_DIR}" 2>/dev/null
    service_stop $MVFS_FS
    if [ -f $MVFS_PID_FILE ]; then
      rm -f $MVFS_PID_FILE
    fi
    if [ -f $MVFS_CONFIG ]; then
      rm -f $MVFS_CONFIG
    fi
    _log "mvfsd stopped."
}

reload_service()
{
  _log "reloading mvfsd"
  service_reload $MVFS_FS
}

mvfs_mkdirs()
{
  mkdir -p "${MVFS_CONFIG_DIR}"
  chmod -R 777 "${MVFS_CONFIG_DIR}"
  touch "${MVFS_CONFIG}"
  chmod 666 "${MVFS_CONFIG}"
}

