#!/bin/sh /etc/rc.common

START=21
STOP=89

start()
{
	$IPKG_INSTROOT/usr/lib/mwan/setup.sh start
	$IPKG_INSTROOT/usr/lib/mwan/load_balancer.sh start
}

stop()
{
	$IPKG_INSTROOT/usr/lib/mwan/setup.sh stop
	$IPKG_INSTROOT/usr/lib/mwan/load_balancer.sh stop
}

reload()
{
	$IPKG_INSTROOT/usr/lib/mwan/setup.sh stop
	$IPKG_INSTROOT/usr/lib/mwan/setup.sh start
	$IPKG_INSTROOT/usr/lib/mwan/load_balancer.sh reload
}

