#!/bin/sh /etc/rc.common
# Copyright (C) 2010 Jo-Philipp Wich

# @NETDUMA_iain: Changed from START=23 to 96, as at that early on in the
# boot process ubus is blocked and that is required by the NETDUMA
# http lua-handler.
START=96

REALM="ND3"
if [ "$(cat /dumaossystem/model)" = "LH1000" -o "$(cat /dumaossystem/model)" = "DJA0231" ];then
  SERVER_PORT="81"
else
  SERVER_PORT="80"
fi

if [ -f /tmp/sysinfo/board_name ]; then
  DEPENDENT_PARAMS="-u"
fi

PROG="ndhttpd"

if type procd 1>/dev/null
then
        USE_PROCD="1"
else
        SERVICE_DAEMONIZE="1"
        SERVICE_WRITE_PID="1"
fi

start_service() {
        procd_open_instance
        procd_set_param command $PROG -D -I ndindex.html -h /www $DEPENDENT_PARAMS -r ${REALM} -x /cgi-bin -l /apps -L /www/cgi-bin/url-routing.lua -t 80 -p 0.0.0.0:$SERVER_PORT
  if [ "$(cat /dumaossystem/model)" = "R2" ];then
          #Set core files size to unlimited
        procd_set_param limits core="unlimited"  # Set ulimit core files blocks
        sysctl -w "kernel.core_pattern=/tmp/%e.%p.%s.%t.core"
        if [ ! -e "/.init_enable_core"  ];then
                touch /.init_enable_core
                sync
        fi
  fi
        procd_set_param respawn
	procd_set_param pidfile /var/run/ndhttpd.pid
        procd_close_instance
}

stop_service() {
        /www/cgi-bin/ndhttpd.sh stop
}

start() {
	/www/cgi-bin/ndhttpd.sh start
	SET_PR=$(pgrep "$NDHTTPD_BIN" -l | cut -d' ' -f1)
        chrt -o -p 0 $SET_PR
}

stop() {
	/www/cgi-bin/ndhttpd.sh stop
}
