#!/bin/sh /etc/rc.common

# Copyright (C) 2010 Jo-Philipp Wich

# @NETDUMA_iain: Changed from START=23 to 96, as at that early on in the
# boot process ubus is blocked and that is required by the NETDUMA
# http lua-handler.

################
#    VARS      #
################
START=96
STOP=

if [ -d "/media/dumaos_output/dumaossystem" ];then
  BASEDIR="/media/dumaos_output/"
else
  BASEDIR="/"
fi

. /dumaos/api/libs/shell/dumaos_helper.sh

PROG="$BASEDIR/usr/sbin/ndhttpd"

REALM="ND3"
WEBROOT="$BASEDIR/www"
URLROUTE="$BASEDIR/www/cgi-bin/url-routing.lua"
SERVER_PORT=""
ALLOWED_ADDRESS_IPV4="127.0.0.1"
ALLOWED_ADDRESS_IPV6="[::1]"
FGFLAG=-f
ENABLE_COREDUMPS=""

if type procd > /dev/null 2>&1; then
  USE_PROCD=1
else
  SERVICE_DAEMONIZE=1
  SERVICE_WRITE_PID=1
  SERVICE_PID_FILE=/var/run/ndhttpd.pid
fi

if [ "${VENDOR}" = "TELSTRA" ] || [ "${MODEL}" = "XB7" ] || [ "${VENDOR}" = "BT" ] || [ "${MODEL}" = "XRE1200" ] || [ "${MODEL}" = "RPI3" ] || [ "${MODEL}" = "XR1000V2" ] || [ "${MODEL}" = "BEACON6" ];then
  SERVER_PORT="81"
else
  SERVER_PORT="80"
fi

if [ "${ODM}" = "SEAL" ]; then
	SERVER_PORT="$SEAL_PORT"
fi

if [ "$SERVER_PORT" != "80" ] && [ "$MODEL" != "BEACON6" ];then
	SERVER_ACCESS=" -p ${ALLOWED_ADDRESS_IPV4}:$SERVER_PORT -p ${ALLOWED_ADDRESS_IPV6}:$SERVER_PORT "
else
	SERVER_ACCESS=" -p 0.0.0.0:$SERVER_PORT -p [::]:$SERVER_PORT "
fi

if [ -f /tmp/sysinfo/board_name ]; then
  DEPENDENT_PARAMS="-u"
fi

# No platform is using our keys so commenting it
#if [ -f "/etc/ndhttpd.crt" ]; then
#  EXTRA_ARGS="-C /etc/ndhttpd.crt -K /etc/ndhttpd.key -s 0.0.0.0:443"
#fi

if [ "$MODEL" = "R2" ];then
    ENABLE_COREDUMPS=true
fi

################
#    FUNCS     #
################
set_up_coredumps(){
    #Set core files size to unlimited
    if [ -n "${USE_PROCD}" ];then
        procd_set_param limits core="unlimited"  # Set ulimit core files blocks
    else
        ulimit -c "unlimited"
    fi

    sysctl -w "kernel.core_pattern=/tmp/%e.%p.%s.%t.core"
    if [ ! -e "/.init_enable_core"  ];then
        touch /.init_enable_core
        sync
    fi
}

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_append_param command $FGFLAG
    procd_append_param command $DEPENDENT_PARAMS
    procd_append_param command -D -I ndindex.html -h $WEBROOT -r ${REALM} -x /cgi-bin -l /apps -L $URLROUTE -t 80 $SERVER_ACCESS
    procd_append_param command $EXTRA_ARGS
    [ -n "$ENABLE_COREDUMPS" ] && set_up_coredumps
    procd_set_param respawn
    procd_set_param pidfile /var/run/ndhttpd.pid
    procd_set_param stdout 0
    procd_set_param stderr 1
    procd_close_instance
}

start() {
    [ -n "$ENABLE_COREDUMPS" ] && set_up_coredumps
    if [ "${MODEL}" = "LH1000" ];then
      SET_PR=$(pgrep "$PROG" -l | cut -d' ' -f1)
      chrt -o -p 0 $SET_PR
    fi

    if [ "$(ps ww | grep "url-routing.lua" | grep -v grep | wc -l)" -lt 1 ];then
        service_start $PROG $FGFLAG $DEPENDENT_PARAMS -D -I ndindex.html -h "$WEBROOT" -r ${REALM} -x /cgi-bin -l /apps -L "$URLROUTE" -t 80 $SERVER_ACCESS $EXTRA_ARGS
    fi
}

stop() {
    service_stop "$PROG"
}

