#!/bin/sh /etc/rc.common

START=65
USE_PROCD=1

. "$IPKG_INSTROOT/lib/functions.sh"

start_service() {
	if [ "$(uci_get ndproxy config enabled 1)" = "1" ]; then
		procd_open_instance "ndproxy"
		procd_set_param command "ndproxy"
		procd_set_param respawn
		procd_set_param stderr 1
		procd_close_instance
	else
		logger -t "ndproxy" "service is disabled"
	fi
}
