#!/bin/sh /etc/rc.common

START=60
SERVICE_DAEMONIZE=1

start() {
	logger -t neighm "Starting neighbour monitor daemon"

	service_start /usr/bin/neighmd
}

stop() {
	logger -t neighm "Stopping neighbour monitor daemon"

	service_stop /usr/bin/neighmd
}
