#!/bin/sh /etc/rc.common

START=60
USE_PROCD=1

. $IPKG_INSTROOT/lib/functions/functions-tch.sh

service_triggers() {
	procd_add_reload_trigger "neighmon"
}

start_service() {
	logger -t neighm "Starting neighbour monitor daemon"

	load_hardware_info
	if [ "$VENDOR" = "Broadcom" ] ; then
	  local arg='-m 0x7'
	fi

	procd_open_instance
	procd_set_param command /usr/bin/neighmd ${arg}
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	stop
	start
}
