#!/bin/sh /etc/rc.common

START=99
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
APP=nfcd.lua
PID_FILE=/var/run/$APP.pid
RUNNING_FILE=/var/run/nfcd_running

start() {
  service_start /usr/sbin/nfcd
  start-stop-daemon -S -x $APP -p $PID_FILE -m -b
}

stop() {
  service_stop /usr/sbin/nfcd
  rm -rf $RUNNING_FILE
  start-stop-daemon -K -p $PID_FILE -s KILL
  rm -rf $PID_FILE
}
