#!/bin/sh /etc/rc.common

START=35
STOP=85

stop() {
	. /lib/functions/service.sh

	service_stop /usr/sbin/odhcpd
}

start() {
	. /lib/functions/service.sh

	SERVICE_DAEMONIZE=1

	service_start /usr/sbin/odhcpd
}
