#!/bin/sh /etc/rc.common

START=90
STOP=20
USE_PROCD=1

start_service() {
	if [ -f "/lib/modules/`uname -r`/sff8472_i2c.ko" ]; then
		insmod sff8472_i2c 2>/dev/null
		[ ! -d "/proc/i2c_bcmsfp_0/" ] && {
			echo "sff8472_i2c 0x50" > /sys/bus/i2c/devices/i2c-0/new_device
        		echo "sff8472_i2c 0x51" > /sys/bus/i2c/devices/i2c-0/new_device
		}
	fi
        procd_open_instance
        procd_set_param command /usr/sbin/opticald
        procd_set_param respawn
        procd_close_instance
}
