#!/bin/sh /etc/rc.common
#set -x

START=10

. $IPKG_INSTROOT/lib/functions/phypower.sh

phypower()
{
    cd /sys/class/net/
    for intf in *; do
      #filter virtual interface
      [ $intf == "bcmsw" ] && continue
      if ethctl $intf media-type &> /dev/null; then
        phypower_intf "$intf" "$1"
      fi
    done
}

start()
{
    phypower down
}

