#!/bin/sh /etc/rc.common
#set -x

START=10

. $IPKG_INSTROOT/lib/functions/phypower.sh

phypower()
{
    cd /sys/class/net/
    for intf in eth[0-9]; do
      phypower_intf "$intf" "$1"
    done
}

start()
{
    phypower down
}

