#!/bin/sh /etc/rc.common

START=11

start() {
        if [ -e /proc/bootloader/version ]; then
                uci set env.var.bootloader_version=`cat /proc/bootloader/version`
                uci commit env
        fi
}

