#!/bin/sh /etc/rc.common
#set -x
START=20

uci2onoff() {
    case "$1" in
        0) echo "off";;
        1) echo "on";;
        *) echo "Invalid UCI enable option: $1" 1>&2; echo "on";;
    esac
}

setup_eee() {
    config_get eee ethernet eee
    [ -n "$eee" ] && pwrctl config --eee `uci2onoff $eee`
}

setup_pci() {
    config_get pci ethernet pci
    [ -n "$pci" ] && pwrctl config --pci `uci2onoff $pci`
}

setup_net() {
    config_get net ethernet net
    [ -n "$net" ] && pwrctl config --net `uci2onoff $net`
}

setup_phy() {
    config_get phy ethernet phy
    [ -n "$phy" ] && pwrctl config --phy `uci2onoff $phy`
}

setup_apd() {
   config_get apd ethernet apd
   [ -n "$phy" ] && pwrctl config --apd `uci2onoff $apd`
}

setup_dgm() {
   config_get dgm ethernet dgm
   [ -n "$dgm" ] && pwrctl config --dgm `uci2onoff $dgm`
}

setup_cpuspeed() {
   config_get cpuspeed ethernet cpuspeed
   [ -n "$cpuspeed" ] && pwrctl config --cpuspeed `uci2onoff $cpuspeed`
}

setup_cpuwait() {
   config_get cpuwait ethernet cpuwait
   [ -n "$cpuwait" ] && pwrctl config --cpuwait `uci2onoff $cpuwait`
}

setup_avs() {
   config_get avs ethernet avs
   [ -n "$avs" ] && pwrctl config --avs `uci2onoff $avs`
}

setup() {
    config_load power
    setup_eee
    setup_pci
    setup_net
    setup_phy
    setup_apd
    setup_dgm
    setup_cpuspeed
    setup_cpuwait
    setup_avs
}

start() {
    setup
}

