#!/bin/sh /etc/rc.common

# Copyright (c) 2016 Technicolor
# All Rights Reserved
#
# This program contains proprietary information which is a trade
# secret of TECHNICOLOR and/or its affiliates and also is protected as
# an unpublished work under applicable Copyright laws. Recipient is
# to retain this program in confidence and is not permitted to use or
# make copies thereof other than as permitted in a written agreement
# with TECHNICOLOR, UNLESS OTHERWISE EXPRESSLY ALLOWED BY APPLICABLE LAWS.
#

START=60

. $IPKG_INSTROOT/lib/functions.sh
. $IPKG_INSTROOT/lib/functions/network.sh

PPPOE_RELAY_LOCKFILE='/var/lock/pppoe-relay-tch.lock'

pppoerelay_setup() {
  lock "${PPPOE_RELAY_LOCKFILE}"
  (. $IPKG_INSTROOT/usr/lib/pppoe-relay-tch/setup.sh ; pppoerelay_$1 )
  lock -u "${PPPOE_RELAY_LOCKFILE}"
}

start() {
  pppoerelay_setup start
}

stop() {
  pppoerelay_setup stop
}

restart() {
  pppoerelay_setup restart
}

reload() {
  pppoerelay_setup reload
}
