#!/bin/sh /etc/rc.common

START=11

start() {
	# Clear the prozone boot flags indicating to the BL that the boot was successful
	echo "0" > /proc/prozone/bootfail
	echo "0" > /proc/prozone/bootcounter
	echo "0" > /proc/prozone/bootbank
}
