#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=65

. $IPKG_INSTROOT/usr/lib/qos/functions.sh

exec_qos_mgr() {
  local action=$1
  local try=1 max_attempts=5
  PROD_ID=$(cat /proc/nvram/boardid)
  while ! /usr/bin/qos -q ${action} ; do
    try=$((try + 1))
    if [ ${try} -gt ${max_attempts} ] ; then
      echo Failed to $action qos after ${max_attempts} attempts
      break
    fi
    sleep 1s
  done
  if [ "$PROD_ID" = "VCNT-A" ]; then
     echo 8192 > /proc/sys/vm/min_free_kbytes
  fi
}

start() {
  /usr/lib/qos/generate.sh firewall start | sh
  local action
  qos_started && action=restart || action=start
  exec_qos_mgr ${action}
}

stop() {
  /usr/lib/qos/generate.sh firewall stop | sh
  exec_qos_mgr stop
}

restart() {
  /usr/lib/qos/generate.sh firewall start | sh
  exec_qos_mgr restart
}

reload() {
  /usr/lib/qos/generate.sh firewall start | sh
  local action
  qos_started && action=reload || action=restart
  exec_qos_mgr ${action}
}

