#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=65

boot() {
  /usr/lib/qos/generate.sh firewall | sh
  /usr/bin/qos -q start
}

start() {
  /usr/lib/qos/generate.sh firewall start | sh
  /usr/bin/qos -q start
}

stop() {
  /usr/lib/qos/generate.sh firewall stop | sh
  /usr/bin/qos -q stop
}

restart() {
  /usr/lib/qos/generate.sh firewall start | sh
  /usr/bin/qos -q restart
}

reload() {
  local action
  /usr/lib/qos/generate.sh firewall start | sh
  iptables -t mangle -L QoS_FW -n >/dev/null 2>&1 && action=reload || action=restart
  /usr/bin/qos -q ${action}
}

