#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=50

boot() {
	/usr/lib/qos/generate.sh firewall | sh
}

start() {
	/usr/lib/qos/generate.sh firewall start | sh
}

stop() {
	/usr/lib/qos/generate.sh firewall stop | sh
}
