#!/bin/sh /etc/rc.common
#set -x
START=18


start() {
     mkdir -p /tmp/qtn
     qual_wlan=`uci get env.qual.qual_wlan 2> /dev/null`

     ln -s /qtn/qtn-linux.lzma /tmp/qtn/qtn-linux.lzma
     ln -s /qtn/qtn-uboot /tmp/qtn/qtn-uboot
     ln -s /qtn/qtn_custo.sh /tmp/qtn/qtn_custo.sh

     if [ "$?" == "0" ] && [ "$qual_wlan" == "1" ]
     then
             cp /qtn/qtn_custo.env /tmp/qtn/qtn_custo.env
	     echo "QUAL_BUILD=1"  >> /tmp/qtn/qtn_custo.env
     else
             ln -s /qtn/qtn_custo.env /tmp/qtn/qtn_custo.env   
     fi

}

