#!/bin/sh /etc/rc.common

# must come after nginx!
START=85

boot() {
  if [ ! -z $(uci show web | grep "web.state_.*\.enabled=1") ]; then
    while true; do
      sleep 1
      wget -O /dev/null -q http://127.0.0.1 && return
    done
  fi
}
