#!/bin/sh /etc/rc.common
# This file is Confidential Information of Cujo LLC.
# Copyright (c) 2018 CUJO LLC. All rights reserved.
START=98
export CUJO_HOME=/opt/cujo
. "$CUJO_HOME/lib/rabid-functions.sh"

start() {
    config_load rabid
    config_get_bool enabled config enable 0
    if [ "$enabled" == 0 ]; then
        is_rabid_running >/dev/null && stop
        return
    fi

    local module
    for module in lunatik luadata luajson luabase64 nflua; do
        insmod $module
    done

    wait_for_correct_date
    is_rabid_running && exit 1

    iptables -t mangle -I PREROUTING 1 -p tcp -m connbytes --connbytes 0:16 --connbytes-mode packets --connbytes-dir both -j SKIPLOG
    ip6tables -t mangle -I PREROUTING 1 -p tcp -m connbytes --connbytes 0:16 --connbytes-mode packets --connbytes-dir both -j SKIPLOG

    start_rabid
}

stop() {
    iptables -t mangle -D PREROUTING -p tcp -m connbytes --connbytes 0:16 --connbytes-mode packets --connbytes-dir both -j SKIPLOG
    ip6tables -t mangle -D PREROUTING -p tcp -m connbytes --connbytes 0:16 --connbytes-mode packets --connbytes-dir both -j SKIPLOG

    stop_rabid

    local module
    for module in nflua luabase64 luajson luadata lunatik; do
        rmmod $module
    done
}

restart() {
    stop
    start
}
