#!/bin/sh /etc/rc.common

START=11

. $IPKG_INSTROOT/lib/functions.sh

boot() {
    # This platform uses TMP75 temperature sensors which are
    # not autodetected by the lm75 driver
    for addr in 0x48 0x4F; do
      echo "lm75 $addr" > /sys/bus/i2c/devices/i2c-0/new_device
    done
}

