#!/bin/sh /etc/rc.common


START=99
STOP=21

#service for sfp monitor currently only do insert sff8472_i2c ko, will do more in future

start() {

	local sfp_i2c_file_0="/proc/i2c_sfp/sfp_eeprom0"
	local sfp_i2c_file_1="/proc/i2c_sfp/sfp_eeprom1"
	if [ ! -f "$sfp_i2c_file_0" -a ! -f "$sfp_i2c_file_1" ]; then
		rmmod sff8472_i2c
		insmod sff8472_i2c
	fi
}

stop() {
        sfp_get.sh --reboot
}

