#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99


start () {
  local enabled
  local run_in_lxc
  local lxcpath
  config_load system
  config_get_bool enabled speedtest enabled 1
  config_get_bool run_in_lxc speedtest run_in_lxc 0
  [ $enabled -eq 0 ] && exit
  [ -n "$(netstat -na |grep 8889)" ] && echo "adb-speedtest is already running on port 8889." && exit

  lxcpath=$(cat /proc/self/cgroup |cut -d '/' -f 2)
  if [ -z $lxcpath ] || [ "$lxcpath" != "lxc" ]; then
    # enable cgroups adb for host environment
    # otherwise uses lxc based cpumem quota
    [ $run_in_lxc -eq 1 ] && exit
    echo 0 >> /cgroups/cpumemblk/adb/cpuset.cpus
    echo 0 >> /cgroups/cpumemblk/adb/cpuset.mems
  else
    [ $run_in_lxc -eq 0 ] && exit
  fi

  echo "Run cm..."

  [ ! -e /etc/ah ] && ln -s /etc_tss/ah /etc/ah
  [ ! -e /etc/cm ] && ln -s /etc_tss/cm /etc/cm
  [ ! -e /tmp/eh ] && mkdir /tmp/eh
  [ ! -e /tmp/ec_time ] && mkdir /tmp/ec_time

  /bin/cm >> /dev/null
  cmclient DOM Device /etc/cm/dom/ >> /dev/null
  cmclient DOM Device /etc/cm/domx/ >> /dev/null

  cmclient CONF /etc/cm/factory/ >> /dev/null
  cmclient CONF /etc/cm/version/ >> /dev/null
  cmclient CONF /etc/cm/conf/ >> /dev/null

  MACAddress=`cat /sys/class/net/br-lan/address`
  cmclient SET Ethernet.Interface.1.MACAddress "$MACAddress"
  cmclient SET X_ADB_FactoryData.BaseMACAddress "$MACAddress"
  cmclient SET IP.Diagnostics.X_ADB_Report.Interface Device.IP.Interface.1
  cmclient SET IP.Diagnostics.X_ADB_Report.Enable true >> /dev/null

  cmclient SET IP.Diagnostics.IPPing.Interface Device.IP.Interface.1
  cmclient SET IP.Diagnostics.DownloadDiagnostics.Interface Device.IP.Interface.1
  cmclient SET IP.Diagnostics.UploadDiagnostics.Interface Device.IP.Interface.1

  echo "Run ec..."
  if [ -z "$(ps | grep -e "ec2$")" ]; then
    ec2 & >> /dev/null
  else
    echo "adb-speedtest is already running in host or lxc, please check."
    exit
  fi

  echo "Run http deamon..."
  lighttpd -f /etc_tss/lighttpd/lighttpd.conf || lighttpd -f /etc_tss/lighttpd/lighttpd_lo.conf

  if [ -z $lxcpath ] || [ "$lxcpath" != "lxc" ]; then
    # why $! can get the last process id in bash??
    for id in $( ps | grep -e "/bin/cm$" -e "cmproxy$" -e "ec2$" -e "lighttpd" | grep -v grep | awk '{print $1}' )
    do
      echo $id >> /cgroups/cpumemblk/adb/tasks
    done
  elif [ -n $lxcpath ] && [ "$lxcpath" = "lxc" ]; then
    cat /dev/null > /var/run/adb-speedtest.pid
    for id in $( ps | grep -e "/bin/cm$" -e "cmproxy$" -e "ec2$" -e "lighttpd" | grep -v grep | awk '{print $1}' )
    do
      echo $id >> /var/run/adb-speedtest.pid
    done
  fi
}

stop () {
  local lxcpath
  # remove all tasks from adb cgroup
  lxcpath=$(cat /proc/self/cgroup |cut -d '/' -f 2)
  if [ -z $lxcpath ] || [ "$lxcpath" != "lxc" ]; then
    [ -e /cgroups/cpumemblk/adb ] && for id in $(cat /cgroups/cpumemblk/adb/tasks)
    do
      kill -9 $id
    done
  elif [ -n $lxcpath ] && [ "$lxcpath" = "lxc" ]; then
    [ -e /var/run/adb-speedtest.pid ] && for id in $(cat /var/run/adb-speedtest.pid)
    do
      kill -9 $id
    done
    cat /dev/null > /var/run/adb-speedtest.pid
  fi
  # seems the killall can not kill the ec2
  #killall cm
  #killall ec2
  #killall lighttpd
}
