#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99


start () {
  local enabled
  config_load system
  config_get_bool enabled speedtest enabled 1
  [ $enabled -eq 0 ] && exit

  # enable cgroups adb
  echo 0 >> /cgroups/cpumemblk/adb/cpuset.cpus
  echo 0 >> /cgroups/cpumemblk/adb/cpuset.mems

  echo "Run cm..."

  [ ! -e /etc/ah ] && ln -s /etc_tss/ah /etc/ah
  [ ! -e /etc/cm ] && ln -s /etc_tss/cm /etc/cm
  [ ! -e /tmp/eh ] && mkdir /tmp/eh
  [ ! -e /tmp/ec_time ] && mkdir /tmp/ec_time

  /bin/cm >> /dev/null
  cmclient DOM Device /etc/cm/dom/ >> /dev/null
  cmclient DOM Device /etc/cm/domx/ >> /dev/null

  cmclient CONF /etc/cm/factory/ >> /dev/null
  cmclient CONF /etc/cm/version/ >> /dev/null
  cmclient CONF /etc/cm/conf/ >> /dev/null

  MACAddress=`cat /sys/class/net/br-lan/address`
  cmclient SET Ethernet.Interface.1.MACAddress "$MACAddress"
  cmclient SET X_ADB_FactoryData.BaseMACAddress "$MACAddress"
  cmclient SET IP.Diagnostics.X_ADB_Report.Interface Device.IP.Interface.1
  cmclient SET IP.Diagnostics.X_ADB_Report.Enable true >> /dev/null

  cmclient SET IP.Diagnostics.IPPing.Interface Device.IP.Interface.1
  cmclient SET IP.Diagnostics.DownloadDiagnostics.Interface Device.IP.Interface.1
  cmclient SET IP.Diagnostics.UploadDiagnostics.Interface Device.IP.Interface.1

  echo "Run ec..."
  ec2 & >> /dev/null

  echo "Run http deamon..."
  lighttpd -f /etc_tss/lighttpd/lighttpd.conf || lighttpd -f /etc_tss/lighttpd/lighttpd_lo.conf

  #waiting 1 second for lighttpd launch
  sleep 1
  #send wanstatus to lighttpd
  echo "Send wanstatus to lighttpd..."
  curl http://localhost:8889/wanstatus?status=up

  # why $! can get the last process id in bash??
  for id in $( ps | grep -e "/bin/cm$" -e "cmproxy$" -e "ec2$" -e "lighttpd" | grep -v grep | awk '{print $1}' )
  do
    echo $id >> /cgroups/cpumemblk/adb/tasks
  done
}

stop () {
  # remove all tasks from adb cgroup
  [ -e /cgroups/cpumemblk/adb ] && for id in $(cat /cgroups/cpumemblk/adb/tasks)
  do
    kill -9 $id
  done
  # seems the killall can not kill the ec2
  #killall cm
  #killall ec2
  #killall lighttpd
}
