#!/bin/sh /etc/rc.common
START=19

start() {
  local enable

  config_load "hardwarecrypto"
  config_get_bool enable "global" "enable" 0

  [ "$enable" -eq 1 ] && spuctl start 2>&1 >/dev/null
}

stop() {
  logger -t spuctl "Right now SPU stop NOT supported!"
}

restart() {
  logger -t spuctl "Right now SPU restart NOT supported!"
}
