#!/bin/sh /etc/rc.common
START=19

start() {
  local enable

  if which spuctl >/dev/null ; then
    config_load "hardwarecrypto"
    config_get_bool enable "global" "enable" 0

    [ "$enable" -eq 1 ] && spuctl start
  fi
}

stop() {
  logger -t spuctl "Right now SPU stop is NOT supported!"
}

restart() {
  logger -t spuctl "Right now SPU restart is NOT supported!"
}
