#!/bin/sh /etc/rc.common
START=19

setup_enabled() {
	config_get hasspuctl crypto hasspuctl
	[ $hasspuctl -eq 1 ] && spuctl start
}

setup () {
	config_load hardwarecrypto
	setup_enabled
}

start(){
	setup
}
