#!/bin/sh /etc/rc.common

START=29
STOP=99
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/supervision.lua
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	ubus call supervision reload >/dev/null
}

