#!/bin/sh /etc/rc.common
#set -x
START=21

start() {
    local enabled
    config_load network
    config_get enabled bcmsw qosimppauseenable "0" 
    if [ $enabled -eq 1 ]; then
      ethswctl -c regaccess -v 0x28 -l 4 -n 0 -d 0x83ffff 
    else
      ethswctl -c regaccess -v 0x28 -l 4 -n 0 -d 0x800000

    fi
}

