#!/bin/sh /etc/rc.common
#set -x
START=21

# Function configures jumbo for the relevant switch (unit) using mdkshell,
# and also the internal switch using ethswctl
handle_switch_for_jumbo() {
    local switchname="$1"
    config_get unit $switchname unit "0"
    config_get jumbo $switchname jumbo "0"
    if [ $jumbo -eq 1 ]; then
        ethswctl -c jumbo -p 9 -v 1
        if [ "$unit" != "0" ] ; then
            for p in $(seq 0 8)
            do
                mdkshell $unit:port jumbo $p enable
            done
        fi
    else
        ethswctl -c jumbo -p 9 -v 0
        if [ "$unit" != "0" ] ; then
            for p in $(seq 0 8)
            do
                mdkshell $unit:port jumbo $p disable
            done
        fi
    fi
}

start() {
    local enabled
    config_load network

    config_get enabled bcmsw qosimppauseenable "0"
    if [ $enabled -eq 1 ]; then
      ethswctl -c regaccess -v 0x28 -l 4 -n 0 -d 0x83ffff
    else
      ethswctl -c regaccess -v 0x28 -l 4 -n 0 -d 0x800000
    fi

    # Configure jumbo for all switches
    config_foreach handle_switch_for_jumbo switch
}

