#!/bin/sh /etc/rc.common

START=15
STOP=93

start() {
        service_start /usr/bin/swmdk &>/dev/console
}

stop() {
        service_stop /usr/bin/swmdk
}

boot() {
       start
       . /etc/init.d/phypower
       phypower down
}
