#!/bin/sh /etc/rc.common

START=15
STOP=93

start() {
        service_start /usr/bin/swmdk &>/dev/console
}

stop() {
        service_stop /usr/bin/swmdk
}

boot() {
       local eth4lanwanmode
       config_load ethernet
       config_get eth4lanwanmode globals eth4lanwanmode
       ethswctl -c lanwan -p 1 -v $eth4lanwanmode
       start
       . /etc/init.d/phypower
       phypower down
}
