#!/bin/sh /etc/rc.common

START=15
STOP=93

start() {
        service_start /usr/bin/swmdk &>/dev/console
}

stop() {
        service_stop /usr/bin/swmdk
}

boot() {
       local eth4lanwanmode
       local ret
       config_load ethernet
       config_get eth4lanwanmode globals eth4lanwanmode
       ret=`ethswctl -c lanwan -p 1 2>/dev/null | grep AN`
       if ([ "$ret" = "WAN" ] || [ "$ret" = "LAN" ]) ; then
           ethswctl -c lanwan -p 1 -v $eth4lanwanmode
       fi
       start
       . /etc/init.d/phypower
       phypower down
}
