#!/bin/sh /etc/rc.common

START=12
STOP=96

log_filter_add() {
	local val=$1
	if [ "$val" = "--no-case" ] ; then
	    IGNORECASE=1
	elif [ "\\${val:0:1}" = "\\!" ] ; then
		if [ "${log_xfilter}" ] ; then
			log_xfilter="${log_xfilter}|(${val:1})"
		else
			log_xfilter="(${val:1})"
		fi
	else
		if [ "${log_filter}" ] ; then
			log_filter="${log_filter}|(${val})"
		else
			log_filter="(${val})"
		fi
	fi
}

logfilter_config() {
	local cfg="$1"
	IGNORECASE=''
	local args log_filter_ip log_port log_type log_file log_filter log_filter_file
	config_get log_filter_ip "$cfg" log_filter_ip
	config_get log_size $cfg log_size 16
	config_get log_port "$cfg" log_port 514
	if [ -x /etc/init.d/log ] ;then
		config_get log_file "$cfg" log_file
		[ -n "$log_file" ] && log_type="file"
	elif [ -x /sbin/syslogd ]; then
		config_get log_type "$cfg" log_type circular
		config_get log_file "$cfg" log_file "/var/log/messages"
	fi
	config_get log_filter_file "$cfg" log_filter_file "/var/log/filt_msg"
	config_list_foreach "$cfg" log_filter log_filter_add
	[ "${log_filter}" ] && log_filter="(${log_filter})"
	[ "${log_xfilter}" ] && log_xfilter="(${log_xfilter})"
	echo "syslog startup : filter:'${log_filter} ${log_xfilter}' filter_ip:'${log_filter_ip}' port:'${log_port}' type:'${log_type}' size:${log_size}kB file:'${log_file}' filter_file:'${log_filter_file}' IGNORECASE:'${IGNORECASE}'" >>/var/log/slfwd.txt
	if [ "${log_filter}" -o "${log_xfilter}" ] ; then
#		mkfifo ${log_filter_file}
		touch ${log_filter_file}
#		echo "Started..." >>${log_filter_file}
		if [ "$log_type" = "file" ] ; then
			tail -F -n +1 "${log_file}" | awk -v pattern="${log_filter}" -v xpattern="${log_xfilter}" -v outfile="${log_filter_file}" -v maxize="${log_size}" -v IGNORECASE="${IGNORECASE}" -f /etc/syslog_fwd/syslog_fwd.awk &
		else
			logread -f | awk -v pattern="${log_filter}" -v xpattern="${log_xfilter}" -v outfile="${log_filter_file}" -v maxize="${log_size}" -v IGNORECASE="${IGNORECASE}" -f /etc/syslog_fwd/syslog_fwd.awk &
		fi
	fi
#	echo "`ls -l ${log_filter_file}`" >>/var/log/slfwd.txt
}

start() {
    config_load system
    config_foreach logfilter_config system
}

stop() {
	filt_pids=$(ps | grep -v "/awk" | awk '/awk -v pattern/ {print $1}')
	logread_pids=$(ps | grep -v "/tail" | awk '/tail -F|logread -f/ {print $1}')
#	will also kill the corresponding (same group id) 'tail' or 'logread'
	for fpid in ${filt_pids}; do 
		pgrpid=$(cat /proc/${fpid}/stat|cut -d' ' -f5)
		kill -9 $fpid
		for lpid in ${logread_pids}; do
			if [ -r /proc/$lpid/stat -a "${pgrpid}" = "$(cat /proc/$lpid/stat|cut -d' ' -f5)" ]; then
				kill -9 ${lpid}
			fi
		done
	done
	rm -f ${log_filter_file}
}
