#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=98

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
SERVICE_PID_FILE=/var/run/sysntpd.pid

start() {
	local peers
	local args="-n"
	local enable_server
	local enable_client
	local prog

	config_load system
	config_get peers ntp server
	config_get prog ntp program
	config_get_bool enable_server ntp enable_server 0
	config_get_bool enable_client ntp enable_client 1

	if [ $enable_server -ne 0 ]; then
		append args "-l"
	fi

	if [ $enable_client -eq 1 -a -n "$peers" ]; then
		local peer
		for peer in $peers; do
			append args "-p $peer"
		done
	fi

	if [ -n "$prog" ]; then
		append args "-S $prog"
	fi

	if [ "$args" != "-n" ]; then
		service_start /usr/sbin/ntpd $args
	fi
}

stop() {
	service_stop /usr/sbin/ntpd
}
