#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

has_root_pwd() {
	local pwd=$([ -f "$1" ] && cat "$1")
	      pwd="${pwd#*root:}"
	      pwd="${pwd%%:*}"

	test -n "${pwd#[\!x]}"
}

get_root_home() {
	local homedir=$([ -f "$1" ] && cat "$1")
	homedir="${homedir#*:*:0:0:*:}"

	echo "${homedir%%:*}"
}

start() {
	if ! has_root_pwd /etc/passwd && [ "$(uci get telnet.general.enable)" == '1' ]
	then
		service_start /usr/sbin/telnetd -l /bin/login
	fi
}

stop() {
	service_stop /usr/sbin/telnetd
}
