#!/bin/sh /etc/rc.common

START=96
STOP=96
APP=tod.lua
PID_FILE=/var/run/$APP.pid
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
unset SERVICE_MATCH_EXEC

config_load "tod"

start() {
    local enabled
    config_get_bool enabled global enabled 0
    [ $enabled -eq 0 ] && return 0

    start-stop-daemon -S -x $APP -p $PID_FILE -m -b
}

stop() {
    start-stop-daemon -K -p $PID_FILE -s KILL

}
