#!/bin/sh /etc/rc.common

START=96
STOP=96
APP=tod.lua
TIMECHANGEMONITOR_APP=time_change_monitor.lua
PID_FILE=/var/run/$APP.pid
TIMECHANGEMONITOR_APP_PID_FILE=/var/run/$TIMECHANGEMONITOR_APP.pid
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
unset SERVICE_MATCH_EXEC

config_load "tod"

start() {
    local enabled
    config_get_bool enabled global enabled 0
    [ $enabled -eq 0 ] && return 0

    if [ -x /sbin/$TIMECHANGEMONITOR_APP ]; then
        start-stop-daemon -S -x $TIMECHANGEMONITOR_APP -p $TIMECHANGEMONITOR_APP_PID_FILE -m -b
    fi
        start-stop-daemon -S -x $APP -p $PID_FILE -m -b
}

stop() {
    if [ -x /sbin/$TIMECHANGEMONITOR_APP ]; then
        start-stop-daemon -K -p $TIMECHANGEMONITOR_APP_PID_FILE -s KILL
    fi
    start-stop-daemon -K -p $PID_FILE -s KILL

}
