#!/bin/sh /etc/rc.common

START=50
STOP=20
USE_PROCD=1
TRANSFORMER_PID_FILE=/var/run/transformer.pid

start_service() {
  procd_open_instance
  procd_set_param command /usr/bin/transformer
  procd_set_param pidfile "${TRANSFORMER_PID_FILE}"
  procd_close_instance
}

stop_service() {
  if [ -r ${TRANSFORMER_PID_FILE} ]; then
    kill -KILL $(cat ${TRANSFORMER_PID_FILE})
    rm -f ${TRANSFORMER_PID_FILE}
  fi
}
