#!/bin/sh /etc/rc.common

START=19

. $IPKG_INSTROOT/lib/network/vopi_intfs_operation.sh

start() {
	vopi_load_layer3_interfaces
}

stop() {
	vopi_unload_layer3_interfaces
}

restart() {
	/etc/init.d/qos stop
	vopi_unload_layer3_interfaces
	vopi_load_layer3_interfaces
	/etc/init.d/qos start
}

reload() {
	restart
}

