#!/bin/sh /etc/rc.common

START=50
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
unset SERVICE_MATCH_EXEC

start() {
	config_load wan_iptv
	config_get enable global enable "0"

	[ "$enable" == "0" ] && return

	service_start /usr/bin/wan_iptv.lua
}

stop() {
	service_stop /usr/bin/wan_iptv.lua && echo >/var/run/wan_iptv.lua.pid
}

