#!/bin/sh /etc/rc.common

START=30
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1
unset SERVICE_MATCH_EXEC

config_load "wansensing"

start() {
    local enable

    config_get_bool enable global enable 0
    [ $enable -eq 0 ] && return 0

    service_start /sbin/wansensing.lua
}

stop() {
    service_stop /sbin/wansensing.lua && echo >/var/run/wansensing.lua.pid
}
