#!/bin/sh /etc/rc.common

START=30
USE_PROCD=1
config_load "wansensing"

start_service() {
    local enable

    config_get_bool enable global enable 0
    [ $enable -eq 0 ] && return 0

    procd_open_instance
    procd_set_param command /sbin/wansensing.lua
    procd_set_param respawn  # defaults 3600,5,5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    local reload_event
    config_get_bool reload_event global reload_event 0

    # The old behaviour was to restart wansensing when it was reloaded so only send
    # an event if wansensing is explicitely configured to do so.
    if [ "$reload_event" -eq 1 ]; then
        ubus send wansensing '{"event": "reload"}'
    else
        restart
    fi
}

service_triggers() {
    procd_add_reload_trigger wansensing
}
