#!/bin/sh /etc/rc.common

START=30
APP=wansensing.lua
PID_FILE=/var/run/$APP.pid

config_load "wansensing"

start() {
    local enable

    config_get_bool enable global enable 0
    [ $enable -eq 0 ] && return 0

    start-stop-daemon -S -x $APP -p $PID_FILE -m -b
}

stop() {
    start-stop-daemon -K -n $APP -p $PID_FILE -s TERM
    rm -rf $PID_FILE
}
