#!/bin/sh /etc/rc.common

START=11
STOP=87

. $IPKG_INSTROOT/lib/functions/reboot_reason.sh

start() {
    . $IPKG_INSTROOT//lib/config/uci.sh

    tmpfile="$(mktemp)"
    # If reboot reason is PWR (default) check for panic data
    is_reboot_reason && cat "/proc/prozone/panic" > "$tmpfile"
    if [ -s "$tmpfile" ]; then
        if cat $tmpfile | grep -q "watchdog will restart system"; then
            set_reboot_reason WATCHDOG
        else
            set_reboot_reason CRASH
        fi
    fi

    uci_set_state system warmboot '' warmboot
    uci_set_state system warmboot reboot $(cat /proc/prozone/reboot)
# default : PWR ; will be set to other cause based on the event
    set_reboot_reason PWR
}

stop() {
# in case of 'reboot', set to CLI if no other then PWR reboot reason set
    is_reboot_reason && set_reboot_reason CLI
}

boot() {
    start
    local rebootReason=$(uci_get_state system warmboot reboot)
    local hw_reboot_count=$(uci_get system @system[0] hw_reboot_count 0)
    local sw_reboot_count=$(uci_get system @system[0] sw_reboot_count 0)
    # Reset the boot count in case of upgrade/rollback/switchover
    if [ "$rebootReason" = "$UPGRADE" -o "$rebootReason" = "$ROLLBACK" -o "$rebootReason" = "$SWOVER" ]; then
        hw_reboot_count="0"
        sw_reboot_count="1"
    # Incrementing the software boot count for each warm boot
    elif [ "$rebootReason" = "$PWR" -a "$sw_reboot_count" = "0" ] || [ "$rebootReason" != "$PWR" -a "$rebootReason" != "$DGASP" ]; then
        sw_reboot_count=$((sw_reboot_count + 1))
    # Incrementing the hardware boot count for each cold boot (PWR)
    elif [ "$rebootReason" = "$PWR" -o "$rebootReason" = "$DGASP" ]; then
        hw_reboot_count=$((hw_reboot_count + 1))
    fi
    uci_set system @system[0] hw_reboot_count $hw_reboot_count
    uci_set system @system[0] sw_reboot_count $sw_reboot_count
    uci_commit system
}
