#!/bin/sh /etc/rc.common

START=99

start() {

  STATE=`uci get wireless.global.wfa_testsuite_daemon 2> /dev/null`

  if [ "$?" = "0" ] && [ "$STATE" = "1" ]; then
    echo "Starting WFA Test Suite Daemon"
    wfa-testsuite-daemon -b -p 9000
  fi

}

stop() {
    killall wfa-testsuite-daemon
}

