#!/bin/sh /etc/rc.common

START=24
USE_PROCD=1
EXTRA_COMMANDS="$EXTRA_COMMANDS reconfigure"
EXTRA_HELP="reconfigure Forces the WPA supplicant config to be written back to UCI"
EXTRA_ARGS=""
unset args

wifi_ep_parse() {
  local ep="${1}"
  local iface=""
  local radio=""

  config_get iface "${ep}" iface


  if [ "${iface}" == "wl2" ]; then
      radio="radio2"
  else
      radio="radio_5G"
  fi

  channel=`uci get wireless.$radio.channel`
  if [ "$channel" == "auto" ]; then
      EXTRA_ARGS="--wait_for_scan $radio"
  fi
}

get_args() {
  . /lib/functions.sh

  config_load wireless
  config_foreach wifi_ep_parse wifi-ep
}

start_service() {
  get_args
  procd_open_instance
  procd_set_param command /usr/bin/wpa_supplicant_mgmt $EXTRA_ARGS
  procd_close_instance
}

reload_service()                                                         
{
	# reload all endpoints
	ubus call wireless.endpoint reload
} 

reconfigure() {
   /usr/sbin/update_wpa_config config
}
