#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

SERVICE_USE_PID=1

start() {
	local enabled
	config_load printersharing
	config_get_bool enabled config enabled 0
	if [ $enabled -eq 1 ]; then
	    service_start /usr/sbin/xinetd -pidfile /var/run/xinetd.pid
	else
	    service_stop /usr/sbin/xinetd
	fi
}

stop() {
	service_stop /usr/sbin/xinetd
}

