#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org

START=60

SERVICE_USE_PID=1
RUN_D="/var/run/xl2tpd"
PID_F="/var/run/xl2tpd.pid"

start() {
	rm -rf "$RUN_D"
	mkdir -p "$RUN_D"
	service_start /usr/sbin/xl2tpd
}

stop() {
	service_stop /usr/sbin/xl2tpd
	rm -rf "$RUN_D"
	rm -rf "$PID_F"
}
