#!/bin/sh /etc/rc.common

# Switch on LED for Fully Booted Indication in Production :
# Do a led action when board is fully booted (as last /etc/init.d script) during factory production test
# To make sure it is the last script in the sequence, give it a START value of 99, and let this script name begin with a 'z'
# Script should do nothing in a normal .bli build, but active in a .bls
# The .bls generation script should activate it by uncommenting the '#START=' line below, and make a '/etc/rc.d/S99zbip-led-on' link to it

#START=99

start() {
	leds_test.sh -l wps 
	echo -e "$(date)\nAll startup scripts processed; Gateway booting process finished !" >/var/log/booted
}

stop() {
	leds_test.sh -s 0 -l wps
}
