#!/bin/sh

# Copyright (C) 2009 OpenWrt.org
case "$ACTION" in
	add)
		# update LEDs
		sleep 1
                if [ -e /sys/bus/usb/drivers/usb/1-1 ] || [ -e /sys/bus/usb/drivers/usb/1-2 ]; then
                	ubus send usb.usb_led '{"status":"on"}'
                fi
		;;
	remove)
		# update LEDs
                if [ ! -e /sys/bus/usb/drivers/usb/1-1 ] && [ ! -e /sys/bus/usb/drivers/usb/1-2 ]; then
                	ubus send usb.usb_led '{"status":"off"}'
                fi
		;;
esac

