#!/bin/sh

# Copyright (C) 2009 OpenWrt.org

case "$ACTION" in
	add)
		# update LEDs
                [ -e /sys/bus/usb/drivers/usb/1-1 ] && [ -e /sys/class/leds/usb\:green/brightness ] && echo "1" > /sys/class/leds/usb\:green/brightness
		[ -e /sys/bus/usb/drivers/usb/1-1 ] && [ -e /sys/class/leds/usb\:green/device_name ] && echo "1-1" > /sys/class/leds/usb\:green/device_name
		[ -e /sys/bus/usb/drivers/usb/2-1 ] && [ -e /sys/class/leds/usb\:green/device_name ] && echo "2-1" > /sys/class/leds/usb\:green/device_name
		;;
	remove)
		# update LEDs
                if [ ! -e /sys/bus/usb/drivers/usb/1-1 ]; then
                        [ -e /sys/class/leds/usb\:green/brightness ] && echo "0" > /sys/class/leds/usb\:green/brightness
                fi
		if [ ! -e /sys/bus/usb/drivers/usb/1-1 ] && [ ! -e /sys/bus/usb/drivers/usb/2-1 ]; then
			[ -e /sys/class/leds/usb\:green/device_name ] && echo "" > /sys/class/leds/usb\:green/device_name
		elif [ -e /sys/bus/usb/drivers/usb/1-1 ]; then
			[ -e /sys/class/leds/usb\:green/device_name ] && echo "1-1" > /sys/class/leds/usb\:green/device_name
		elif [ -e /sys/bus/usb/drivers/usb/2-1 ]; then
			[ -e /sys/class/leds/usb\:green/device_name ] && echo "2-1" > /sys/class/leds/usb\:green/device_name
		fi
		;;
esac	
		
