#!/bin/sh

case "$ACTION" in
	add | remove)
              # mount USB stick and printer
            
              [ -n "${INTERFACE}" ] &&
              [ "$(expr substr ${INTERFACE} 1 2)" == "8/" -o "$(expr substr ${INTERFACE} 1 2)" == "7/" ]  && {
                /usr/bin/mount-usb "Y" &
              }

		;;
esac	
		
