#!/bin/sh

case "$ACTION" in
	add | remove)
              # mount USB stick
            
              [ -n "${INTERFACE}" ] &&
                      [ "$(expr substr ${INTERFACE} 1 2)" == "8/" ]  && { 
				/usr/bin/mount-usb "Y" &
                      } 

		;;
esac	
		
