#!/bin/sh

. /lib/functions/samba_printer.sh

case "$ACTION" in
	add | remove)
              # mount USB stick and printer
		[ -n "${INTERFACE}" ] &&
		if [ "$(expr substr ${INTERFACE} 1 2)" == "7/" ]; then
			reload_printers
		fi
	;;
esac	
		
