#!/bin/sh

case "$ACTION" in
	add | remove)
              # update content sharing info
            
              [ -n "${INTERFACE}" ] &&
                      [ "$(expr substr ${INTERFACE} 1 2)" == "8/" ]  && { 
				/usr/bin/content-sharing "Y" &
                      } 

		;;
esac	
		
