#!/bin/sh

QUECTEL="
    2c7c/125
"

if [ "$DEVTYPE" == "usb_device" ]; then
case "$ACTION" in
    add)
        for pidvid in $QUECTEL; do
            if [ $(expr match $PRODUCT $pidvid) != 0 ]; then
                insmod GobiNet
            fi
        done
    ;;
esac
fi
