#!/bin/sh

# Hotplug script which restarts minidlna when a USB disk gets attached or detached.

USB_ID=`echo $DEVICENAME | awk 'match($0, "[0-9]+\-[0-9]+[\.]?[0-9]?\:") { print substr($0, RSTART, RLENGTH)}'`

restart_minidlna(){

        # Remove database and log file
        rm -rf /var/run/minidlna
        rm -f /var/log/minidlna.log

        # Restart minidlna process
        # restart will be done in the mount-usb script because mount is not finished yet. 
        #/etc/init.d/minidlna restart &

	logger -t minidlna-hotplug "== DEBUG miniDLNA restarted by hotplug [$ACTION/$DEVICENAME]"
}

case "$ACTION" in
        add | remove)
		[ ! -z $USB_ID ]  && { 
			restart_minidlna
		}                 
                ;;
esac
