#!/bin/sh

if [ "$DEVTYPE" == "usb_device" ]; then
    case "$ACTION" in
        add)
            ubus send "mobiled" '{"event":"device_connected", "dev_desc":"'$DEVICENAME'"}'
        ;;
        remove)
            ubus send "mobiled" '{"event":"device_disconnected", "dev_desc":"'$DEVICENAME'"}'
        ;;
    esac
fi
