#!/bin/sh

if [ "$DEVTYPE" == "usb_device" ]; then
    case "$ACTION" in
        add)
            ubus send "mobiled" '{"event":"device_connected"}'
        ;;
        remove)
            ubus send "mobiled" '{"event":"device_disconnected"}'
        ;;
    esac
fi
