#!/bin/sh

. $IPKG_INSTROOT/lib/functions.sh
. $IPKG_INSTROOT/lib/functions/network.sh
. $IPKG_INSTROOT/usr/lib/hotspot/functions.sh

# $1: num_users
# $2: max_users

if [ $# -lt 2 ] || ! check_is_number "$1" || ! check_is_number "$2"; then
  exit 1
fi

if [ $1 -lt $2 ]; then
  hotspot_state_clear hotspotdaemon_maxauthreached
else
  hotspot_state_set hotspotdaemon_maxauthreached "1"
fi
hotspot_evaluate_state

exit 0
