#!/bin/sh

. $IPKG_INSTROOT/lib/functions.sh
. $IPKG_INSTROOT/lib/functions/network.sh
. $IPKG_INSTROOT/usr/lib/hotspot/functions.sh

hotspot_state_set hotspotdaemon "down"
hotspot_evaluate_state

exit 0
