#!/bin/sh
# Copyright (C) 2015 Technicolor Delivery Technologies, SAS

random_seed() {
	local seedfile=/etc/random-seed
	local poolfile=/proc/sys/kernel/random/poolsize
	local mtd_eripv2

	if [ -f $seedfile ]; then
		[ "$1" == "start" ] && cat $seedfile >/dev/urandom
	else
		touch $seedfile
		chmod 600 $seedfile
		mtd_eripv2=$(grep eripv2 /proc/mtd | cut -d ':' -f 1)
		[ -n "$mtd_eripv2" ] && dd if=/dev/$mtd_eripv2 of=/dev/urandom count=1 bs=1024
	fi
	[ -r $poolfile ] && bits=$(cat $poolfile) || bits=4096
	bytes=$(expr $bits / 8)
	dd if=/dev/urandom of=$seedfile count=1 bs=$bytes
}

random_seed "$@"
