#!/usr/bin/env lua
local os = os
local uci = require("uci")
local proxy = require("datamodel")
local cursor = uci.cursor(nil, "/var/state")

local enabled = cursor:get("system", "scheduledreboot", "enabled")
cursor:close()

-- Check if scheduledreboot_enabled is on, only then we need to initiate the reboot.
-- If scheduledreboot_enabled is off, we just remove the cron job

if enabled == "1" then
  -- Initiate reboot with reason as 'CLI'
  proxy.set({ ["rpc.system.reboot"] = "CLI" })
  proxy.apply()
end

-- Remove cron job if scheduledreboot_enabled is off or reboot has been triggered
os.execute("crontab -c /etc/crontabs/ -l | grep -v '/usr/sbin/scheduledreboot' | crontab -c /etc/crontabs/ -")
