#!/bin/sh

. $IPKG_INSTROOT/lib/functions.sh

pinter_path="/var/spool/samba"
smb_share() {
        local path
	config_get path $1 path
        pinter_path=$path
}

config_load samba
config_foreach smb_share sambashare
rm -rf $pinter_path
/etc/init.d/samba restart

