#!/bin/sh
#for telstra in common
set -x
#/bin/opkg install /usr/lib/ipk/Dependencies/*
#/bin/opkg install /usr/lib/ipk/THOR/*
#rm -rf /usr/lib/ipk/Dependencies/
#rm -rf /usr/lib/ipk/THOR/
/bin/opkg install /usr/lib/ipk/tls-vsparc_2.2.1a-dja0230.ipk
