#!/bin/sh

touch /etc/slicstate

/usr/bin/mmdetectslic || true

cat /etc/slicstate  | grep "isVoiceOn:"
if [ "$?" = 0 ]		#/etc/slicstate is not empty
then
  cat /etc/slicstate  | grep "isVoiceOn:1"
  if [ "$?" = 0 ]
  then
    echo "This is a voice platform...."
    fxoEpNumber=$(cat /etc/slicstate  | grep "fxoEpNumber"|awk '{print $3}')
    dectEpNumber=$(cat /etc/slicstate  | grep "dectEpNumber"|awk '{print $3}')
    if [ "$fxoEpNumber" = 0 ]
    then
      rm $(find /usr/share/transformer -name '*fxo*')
      rm $(find /etc/config -name '*fxo*')
    fi
    if [ "$dectEpNumber" = 0 ]
    then
      rm $(find /usr/share/transformer -name '*dect*')
      rm $(find /etc/config -name '*dect*')
      rm $(find /usr/lib/lua/tch -name 'mmpbxdect_backup.lua')
      rm $(find /etc/parameter_conversion -name 'conversion_dectemission')
      rm $(find /usr/lib/parameter_conversion -name 'mmpbx_dectemission.sh')
    fi
    if [ -f /usr/lib/mmpbx/libmmpbxrvsipdev.so ]
    then
      echo "sipDev supported in this platform...."
      sipDevSupported=1
    else
      echo "sipDev not supported in this platform...."
      sipDevSupported=0
      rm $(find /usr/share/transformer -name '*sipdev*')
      rm $(find /etc/config -name '*sipdev*')
    fi
    if [ -f /usr/lib/mmpbx/libmmpbxrefdev.so ]
    then
      echo "refDev supported in this platform...."
    else
      echo "refDev not supported in this platform...."
      rm $(find /etc/config -name '*refdev*')
    fi
    if [ "$dectEpNumber" = 0 ] || [ "$fxoEpNumber" = 0 ] || [ "$sipDevSupported" = 0 ]
    then
      #call lua script for cleaning mmpbx file.
      echo "dectEpNumber=$dectEpNumber fxoEpNumber=$fxoEpNumber sipDevSupported=$sipDevSupported"
      /usr/bin/lua /usr/lib/lua/tch/mmpbxcustocleanup.lua $dectEpNumber $fxoEpNumber $sipDevSupported
    fi
  else
    echo "This is not a voice platform, do the clean up ..."
    opkg remove --force-removal-of-dependent mmpbx
    opkg remove mmpbxfwctl
    opkg remove mmpbxipv6fwctl
    opkg remove --force-depends mappings-mmpbxd
    rm $(find /etc/config -name '*mmpbx*')
    rm $(find /etc/config -name mmdbd)
    uci del_list cwmpd.cwmpd_config.forcedinforms='Device.Services.VoiceService.1.VoiceProfile.1.Line.1.Enable'
    uci del_list cwmpd.cwmpd_config.forcedinforms='Device.Services.VoiceService.1.VoiceProfile.1.Line.2.Enable'
    uci del_list cwmpd.cwmpd_config.forcedactives='Device.Services.VoiceService.1.VoiceProfile.1.Line.1.Enable'
    uci del_list cwmpd.cwmpd_config.forcedactives='Device.Services.VoiceService.1.VoiceProfile.1.Line.2.Enable'
    uci commit
  fi
fi
