lxc.hook.pre-mount = /usr/share/lxc/hooks/pre-mount
lxc.mount.entry = /var/run/xtables.lock var/run/xtables.lock none ro,bind,create=file 0 0
lxc.mount.entry = /etc/shp_app_config_state var/state none rw,bind,create=dir,optional 0 0
lxc.mount.entry = /dev/net/tun dev/net/tun none bind,optional,create=file 0 0
lxc.mount.entry = /usr/lib/iptables/ usr/lib/iptables/ none ro,bind,create=dir 0 0
lxc.mount.entry = /tmp/resolv.conf.d/ var/resolv.conf.d/ none ro,bind,create=dir 0 0
lxc.mount.entry = /tmp/dhcp.leases var/dhcp.leases none ro,bind,create=file 0 0
